### ISSUE TITLE
Problem with RunCreateNetworkFromOSM.java

### ISSUE THREAD

**Issue by MarcinKinque** [matsim-org/matsim-code-examples#1170]
I found the code example src/main/java/org/matsim/codeexamples/network/RunCreateNetworkFromOSM.java and
inserted my file paths downloaded from Geofabrik.com

The code with the inserted paths:
```
package org.matsim.codeexamples.network;

import org.locationtech.jts.geom.prep.PreparedGeometry;
import org.matsim.api.core.v01.TransportMode;
import org.matsim.api.core.v01.network.Network;
import org.matsim.contrib.osm.networkReader.LinkProperties;
import org.matsim.contrib.osm.networkReader.OsmTags;
import org.matsim.contrib.osm.networkReader.SupersonicOsmNetworkReader;
import org.matsim.core.network.algorithms.NetworkCleaner;
import org.matsim.core.network.io.NetworkWriter;
import org.matsim.core.utils.geometry.CoordinateTransformation;
import org.matsim.core.utils.geometry.transformations.TransformationFactory;
import org.matsim.utils.gis.shp2matsim.ShpGeometryUtils;

import java.net.MalformedURLException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Example on how to convert osm data from e.g. http://download.geofabrik.de into a MATSim network. This example puts all
 * motorways and primary roads into the MATSim network. If a link is contained in the supplied shape, also minor and
 * residential roads are put into the MATSim network.
 * <p>
 * After parsing the OSM-data, unreachable areas of the network are removed by using the network cleaner
 */
public class RunCreateNetworkShape {

    // UTM32n (EPSG:25832) is a common projection system for parts of Europe
    private static String UTM32nAsEpsg = "EPSG:25832";

    // Input paths for the OSM and Shapefile data
    private static Path input = Paths.get("D:\\intelliJ\\Matsim_example\\matsim-example-project\\Einfaches_Beispiel_kleines_Netz\\stuttgart-regbez-latest.osm.pbf");
    private static Path filterShape = Paths.get("D:\\intelliJ\\Matsim_example\\matsim-example-project\\Einfaches_Beispiel_kleines_Netz\\stuttgart-regbez-latest-free.shp");

    public static void main(String[] args) throws MalformedURLException {
        new RunCreateNetworkShape().create();
    }

    private void create() throws MalformedURLException {

        // Choose an appropriate coordinate transformation. OSM Data is in WGS84. EPSG:25832 or EPSG:25833 is commonly used in central Europe
        CoordinateTransformation transformation = TransformationFactory.getCoordinateTransformation(
                TransformationFactory.WGS84, UTM32nAsEpsg
        );

        // Load the geometries from the Shapefile, which will be used to filter the network creation process
        List<PreparedGeometry> filterGeometries = ShpGeometryUtils.loadPreparedGeometries(filterShape.toUri().toURL());

        // Create an OSM network reader and set the coordinate transformation and link filtering
        SupersonicOsmNetworkReader reader = new SupersonicOsmNetworkReader.Builder()
                .setCoordinateTransformation(transformation)
                .setIncludeLinkAtCoordWithHierarchy((coord, hierarchyLevel) -> {

                    // Include all links that are motorways, trunks, or primary-streets regardless of their location
                    if (hierarchyLevel <= LinkProperties.LEVEL_PRIMARY) return true;

                    // Within the shape, include all links that are contained in the OSM file
                    return ShpGeometryUtils.isCoordInPreparedGeometries(coord, filterGeometries);
                })
                .setAfterLinkCreated((link, osmTags, direction) -> {

                    // If the original OSM link contains a cycleway tag, add bicycle as allowed transport mode
                    if (osmTags.containsKey(OsmTags.CYCLEWAY)) {
                        Set<String> modes = new HashSet<>(link.getAllowedModes());
                        modes.add(TransportMode.bike);
                        link.setAllowedModes(modes);
                    }
                })
                .build();

        // Read the OSM data and create the MATSim network
        Network network = reader.read(input.toString());

        // Clean the network to remove unconnected components where agents might get stuck
        new NetworkCleaner().run(network);

        // Write the network to a file
        new NetworkWriter(network).write("D:\\intelliJ\\Matsim_example\\matsim-example-project\\plans_output\\STGTnetwork.xml.gz");
    }
}


```

when I run this this output appears:

```
2024-10-07T23:01:32,209  WARN MGC:179 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
2024-10-07T23:01:33,280  WARN MGC:179 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
2024-10-07T23:01:33,742  INFO GeoFileReader:106 will try to read from /D:/intelliJ/Matsim_example/matsim-example-project/Einfaches_Beispiel_kleines_Netz/stuttgart-regbez-latest-free.shp/
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.geotools.data.FileDataStore.getFeatureSource()" because "dataStore" is null
	at org.matsim.core.utils.gis.GeoFileReader.getSimpleFeatures(GeoFileReader.java:118)
	at org.matsim.core.utils.gis.GeoFileReader.getAllFeatures(GeoFileReader.java:107)
	at org.matsim.utils.gis.shp2matsim.ShpGeometryUtils.loadPreparedGeometries(ShpGeometryUtils.java:44)
	at org.matsim.codeexamples.network.RunCreateNetworkShape.create(RunCreateNetworkShape.java:50)
	at org.matsim.codeexamples.network.RunCreateNetworkShape.main(RunCreateNetworkShape.java:39)

Process finished with exit code 1

```

what is the problem with it the .shp is a folder with different files like .shp .prj .cpg... do I understand it false or is there something else I am missing?

I would appreaciate every help.

Thank you!

**Comment by Janekdererste** [comment]
Indeed, the program crashes when it tries to load your filter shape file. The shape file format consists of one main file ending with `.shp` and several other files which you already enumerated. You should make sure that the other files are in the same folder as the `.shp` file and have the same filename except for the extension. 

> what is the problem with it the .shp is a folder with different files like .shp .prj .cpg...

I am not quite sure, what exactly you are trying to say here. The exact meaning might have been lost in translation.

**Comment by MarcinKinque** [comment]
Thank you for your response.

I downloaded the Stuttgart.pbf and Stuttgart.shp.zip files from http://download.geofabrik.de/europe/germany/baden-wuerttemberg.html.

After unzipping Stuttgart.shp.zip, a folder appears with various files. Linke this:

![IMG_0083](https://github.com/user-attachments/assets/103f4fe2-f122-49f2-b579-3df7791e1964)

Could you please guide me on how to use these files correctly with my network converter to convert the network into a MATSim network? Thank you!

**Comment by MarcinKinque** [comment]
Thank you I updated my code but now there is another problem.

I changed it like this:
```
public class RunCreateNetworkShape {

    // UTM32n (EPSG:25832) is a common projection system for parts of Europe
    private static String UTM32nAsEpsg = "EPSG:25832";

    // Input paths for the OSM and Shapefile data
    private static Path input = Paths.get("D:\\intelliJ\\Matsim_example\\matsim-example-project\\Einfaches_Beispiel_kleines_Netz\\stuttgart-regbez-latest.osm.pbf");
    private static Path filterShape = Paths.get("D:\\intelliJ\\Matsim_example\\matsim-example-project\\Einfaches_Beispiel_kleines_Netz\\stuttgart-regbez-latest-free\\gis_osm_roads_free_1.shp");

    public static void main(String[] args) throws MalformedURLException {
        new RunCreateNetworkShape().create();
    }

    private void create() throws MalformedURLException {
```

but now it just freezes at this point:

```

2024-10-08T12:24:26,729  WARN MGC:179 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
2024-10-08T12:24:27,579  WARN MGC:179 Assuming that coordinates are in longitude first notation, i.e. (longitude, latitude).
2024-10-08T12:24:28,073  INFO GeoFileReader:106 will try to read from /D:/intelliJ/Matsim_example/matsim-example-project/Einfaches_Beispiel_kleines_Netz/stuttgart-regbez-latest-free/gis_osm_roads_free_1.shp
Starting to read OSM data...
2024-10-08T12:24:36,118  INFO OsmNetworkParser:122 Added 20,002 ways
2024-10-08T12:24:36,205  INFO OsmNetworkParser:122 Added 30,000 ways
2024-10-08T12:24:36,206  INFO OsmNetworkParser:122 Added 30,000 ways
2024-10-08T12:24:36,299  INFO OsmNetworkParser:122 Added 40,000 ways
2024-10-08T12:24:36,415  INFO OsmNetworkParser:122 Added 50,001 ways
2024-10-08T12:24:36,479  INFO OsmNetworkParser:122 Added 60,000 ways
2024-10-08T12:24:36,551  INFO OsmNetworkParser:122 Added 70,000 ways
2024-10-08T12:24:36,681  INFO OsmNetworkParser:122 Added 80,000 ways
2024-10-08T12:24:36,943  INFO OsmNetworkParser:122 Added 90,000 ways
2024-10-08T12:24:37,083  INFO OsmNetworkParser:122 Added 100,000 ways
2024-10-08T12:24:37,445  INFO OsmNetworkParser:122 Added 110,000 ways
2024-10-08T12:24:37,682  INFO OsmNetworkParser:122 Added 120,000 ways
2024-10-08T12:24:37,942  INFO OsmNetworkParser:122 Added 130,000 ways
2024-10-08T12:24:38,377  INFO OsmNetworkParser:122 Added 140,000 ways
2024-10-08T12:24:38,760  INFO OsmNetworkParser:122 Added 150,000 ways
2024-10-08T12:24:39,010  INFO OsmNetworkParser:122 Added 160,000 ways
2024-10-08T12:24:39,441  INFO OsmNetworkParser:122 Added 170,000 ways
2024-10-08T12:24:39,681  INFO OsmNetworkParser:122 Added 180,000 ways
2024-10-08T12:24:39,741  INFO OsmNetworkParser:60 Finished reading ways
2024-10-08T12:24:39,742  INFO OsmNetworkParser:61 Starting to read nodes


```

Do I miss something ? what is the problem... 
I am sorry for that beginner questions...

**Comment by Janekdererste** [comment]
Parsing the osm file usually takes a lot of ram. Make sure to assign sufficient ram by setting `Xmx10G`, or however much you can spare on your machine.

**Comment by shairys88-Malmo** [comment]
Hi Janek, 

**Note:** I hope this is a suitable place since I have the same problem, but if needed, I can post this query as a new thread. 

**Scope:** I am trying to run a DRT scenario for Ulricehamn, with the database of 14 months from Ulricehamn Buss on Demand Pilot. 
**Problem:** During network extraction from OSM PBF to MATSim network code from matsim-code -examples; I am unable to produce a suitable network file having below: 
The whole of Sweden or nearby Ulricehamn major road networks and also all small link/roads/nodes in Ulricehamn, as you have in your case of Kelheim. 
**Your reference:** 
![Image](https://github.com/user-attachments/assets/a043c8ab-4796-4e1d-9d7c-9d71b069142b)

**My results:**_I am having this only (even after using different SHP files from the downloaded folder):_ 
![Image](https://github.com/user-attachments/assets/50e4c761-805a-46d7-9e04-e3b4efabe24e)

_Or this with osmium-bounded coordinates:_
![Image](https://github.com/user-attachments/assets/4f0905ec-3096-4b73-8e7d-c29cee59b236)

**NB:** 
I have downloaded PBF and SHP from here:
https://download.geofabrik.de/europe/sweden.html

I used this command for bounded PBF
`osmium extract --bbox=12.6,57.4,14.7,57.9 sweden-latest.osm.pbf -o ulricehamn.osm.pbf`

**Problem:** 
1. Please suggest whether I am using the code wrong or having/using the wrong SHP files. 
2. Do I need some extended SHP file (like paid) for this? 
3. Any other bug? I am sharing the code I used for me. 
4. Please help me resolve this.

Thanks in Advance.

`package org.matsim.codeexamples.network;

import org.locationtech.jts.geom.prep.PreparedGeometry;
import org.matsim.api.core.v01.TransportMode;
import org.matsim.api.core.v01.network.Network;
import org.matsim.contrib.osm.networkReader.LinkProperties;
import org.matsim.contrib.osm.networkReader.OsmTags;
import org.matsim.contrib.osm.networkReader.SupersonicOsmNetworkReader;
import org.matsim.core.network.algorithms.NetworkCleaner;
import org.matsim.core.network.io.NetworkWriter;
import org.matsim.core.utils.geometry.CoordinateTransformation;
import org.matsim.core.utils.geometry.transformations.TransformationFactory;
import org.matsim.utils.gis.shp2matsim.ShpGeometryUtils;

import java.net.MalformedURLException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Example on how to convert osm data from e.g. http://download.geofabrik.de into a MATSim network. This example puts all
 * motorways and primary roads into the MATSim network. If a link is contained in the supplied shape, also minor and
 * residential roads are put into the MATSim network.
 * <p>
 * After parsing the OSM-data, unreachable areas of the network are removed by using the network cleaner
 */
public class RunCreateNetworkFromOSM {

	// private static String UTM32nAsEpsg = "EPSG:25832";
	private static String UTM32nAsEpsg = "EPSG:3006";
	private static Path input = Paths.get("/Users/xx0000/matsim-code-examples/sweden/ulricehamn.osm.pbf");
	private static Path filterShape = Paths.get("/Users/xx0000/matsim-code-examples/sweden/sweden-latest-free.shp/gis_osm_roads_free_1.shp");

	public static void main(String[] args) throws MalformedURLException {
		new RunCreateNetworkFromOSM().create();
	}

	private void create() throws MalformedURLException {

		// choose an appropriate coordinate transformation. OSM Data is in WGS84. When working in central Germany,
		// EPSG:25832 or EPSG:25833 as target system is a good choice
		CoordinateTransformation transformation = TransformationFactory.getCoordinateTransformation(
				TransformationFactory.WGS84, UTM32nAsEpsg
		);

		// load the geometries of the shape file, so they can be used as a filter during network creation
		// using PreparedGeometry instead of Geometry increases speed a lot (usually)
		List<PreparedGeometry> filterGeometries = ShpGeometryUtils.loadPreparedGeometries(filterShape.toUri().toURL());

		// create an osm network reader with a filter
		SupersonicOsmNetworkReader reader = new SupersonicOsmNetworkReader.Builder()
				.setCoordinateTransformation(transformation)
				.setIncludeLinkAtCoordWithHierarchy((coord, hierarchyLevel) -> {

					// take all links which are motorway, trunk, or primary-street regardless of their location
					if (hierarchyLevel <= LinkProperties.LEVEL_PRIMARY) return true;

					// whithin the shape, take all links which are contained in the osm-file
					return ShpGeometryUtils.isCoordInPreparedGeometries(coord, filterGeometries);
				})
				.setAfterLinkCreated((link, osmTags, direction) -> {

					// if the original osm-link contains a cycleway tag, add bicycle as allowed transport mode
					// although for serious bicycle networks use OsmBicycleNetworkReader
					if (osmTags.containsKey(OsmTags.CYCLEWAY)) {
						Set<String> modes = new HashSet<>(link.getAllowedModes());
						modes.add(TransportMode.bike);
						link.setAllowedModes(modes);
					}
				})
				.build();

		// the actual work is done in this call. Depending on the data size this may take a long time
		Network network = reader.read(input.toString());

		// clean the network to remove unconnected parts where agents might get stuck
		new NetworkCleaner().run(network);

		// write out the network into a file
		new NetworkWriter(network).write("/Users/xx0000/matsim-code-examples/sweden/network.xml.gz");
	}
}
`

**Comment by Janekdererste** [comment]
As a first step to debugging, you could run the network converter with fewer parameters and see, whether everything you expect is included. For example:
```
SupersonicOsmNetworkReader reader = new SupersonicOsmNetworkReader.Builder()
 		.setCoordinateTransformation(transformation)
                .build();
Network network = reader.read(input.toString());
// write network to file without cleaning
 new NetworkWriter(network).write("/Users/xx0000/matsim-code-examples/sweden/network.xml.gz");
```
This should create a network that includes all roads in the `pbf` file, including small roads and footpaths. If this is the case, try adding more configuration steps to the converter, for example the filter geometry. This way you can figure out which parts don't work together correctly.

If the produced file does not include the expected roads, you should double check you input file.

**Comment by shairys88-Malmo** [comment]
Janek many thanks for this, you are magician :). I spent like two weeks to play with osm pbf and I was unsuccessful till today. 

This "if-scenario" is not working for me (I dont know why) but without it code runs like super sonic really.
And whenever I add it in my code it only gives highways etc. and takes higher computation time too. 

So for now I commented the block below: 
```
/*.setIncludeLinkAtCoordWithHierarchy((coord, hierarchyLevel) -> {

					// take all links which are motorway, trunk, or primary-street regardless of their location
					if (hierarchyLevel <= LinkProperties.LEVEL_PRIMARY) return true;

					// whithin the shape, take all links which are contained in the osm-file
					return ShpGeometryUtils.isCoordInPreparedGeometries(coord, filterGeometries);
				})*/
```
Here are my the results. 
![Image](https://github.com/user-attachments/assets/960e9a7e-582e-49a6-acf0-30ca7706dc25)

and this in zoom version
![Image](https://github.com/user-attachments/assets/2e89d27d-3413-4daf-9340-b58386fc6029)

I will discuss further working and issues in other threads too. 
Many thanks
~Malik

**Comment by DIPYAMANSINHA** [comment]
Hello @Janekdererste ! I have created a network in QGIS, selecting and editing some roads manually for a chosen admin boundary. Is there anyway I can convert this QGIS layer into the MATSIM network format in XML? The code in RunCreateNetworkFromOSM, I found in matsim-code-examples, converts files directly from osm.pbf to XML.

**Comment by JayitaCh** [comment]
@DIPYAMANSINHA I think you can use JOSM here. This allows you to convert .shp file to .osm.pbf. You may need to install the relevant plugins. You can use the above function to convert it into matsim ready network. That's the workflow I follow.
