### ISSUE TITLE
Simulation stop before the end (lastIteration = 500)

### ISSUE THREAD

**Issue by eBimPy** [matsim-org/matsim-code-examples#1193]
Hello,
I tried to run a simulation in eqasim-java for synthetic data ile-de-france. in the configuration file I set lastIteration = 500 but the simulation often stops at iteration 85, 86, 87 without reaching the requested 500.
for information: I set lastIteration = 50 to see and this time the simulation went to the end.
In the log file I have this error:

2024-12-19T12:09:25,886  INFO CountsWriterV2:45 Write Counts to simulation_output/ile-de-france-0.1pct/output_counts.xml.gz
2024-12-19T12:09:25,943  INFO ControlerListenerManagerImpl:135 calling notifyShutdown on org.matsim.analysis.ModeChoiceCoverageControlerListener with priority 0.0
2024-12-19T12:09:25,943  INFO ControlerListenerManagerImpl:135 calling notifyShutdown on org.matsim.analysis.ScoreStatsControlerListener with priority 0.0
2024-12-19T12:09:25,943  INFO ControlerListenerManagerImpl:135 calling notifyShutdown on org.matsim.analysis.IterationTravelStatsControlerListener with priority 0.0
2024-12-19T12:09:25,943  INFO PersonWriter:36 Writing all Persons to personscsv
2024-12-19T12:09:26,131  INFO PersonWriter:54 ...done
2024-12-19T12:09:26,131  INFO ControlerListenerManagerImpl:135 calling notifyShutdown on org.matsim.analysis.LinkStatsControlerListener with priority 0.0
2024-12-19T12:09:35,514  INFO ControlerListenerManagerImpl:135 calling notifyShutdown on org.matsim.contribs.discrete_mode_choice.modules.UtilitiesWriterHandler with priority 0.0
2024-12-19T12:09:35,535  INFO ControlerListenerManagerImpl:135 calling notifyShutdown on org.eqasim.core.simulation.analysis.AnalysisOutputListener with priority 0.0
2024-12-19T12:09:35,564  INFO ControlerListenerManagerImpl:138 all ControlerShutdownListeners called.
2024-12-19T12:09:35,564  INFO MatsimRuntimeModifications:103 S H U T D O W N   ---   shutdown completed.
2024-12-19T12:09:35,564  INFO OutputDirectoryLogging:172 closing the logfile, i.e. messages sent to the logger after this message are not written to the logfile.

Can someone explain to me where S H U T D O W N --- shutdown completed comes from.

Thanks

**Comment by sebhoerl** [comment]
Hello, the Java part of eqasim standardizes and configures MATSim for the available use cases of Paris, California, Sao Paulo, etc. The default `ConvergenceCriterion` in MATSim stops at the iteration that is indicated as `lastIteration` in the config. In eqasim, we define a more intelligent `ConvergenceCriterion` which checks the slope of the mode shares graphs and stops the simulation once the slope falls under a configurable threshold (eqasim:convergence module in the coniguration file). This way, we make sure that the simulation stops at a well-defined state. The `lastIteration` config only acts as an upper bound.

**Comment by kainagel** [comment]
For people who use this: one needs to be careful that this does not interact with scheduled annealing.  If scheduled annealing reduces the replanning rate over the iterations, then it is clear that the slope gets smaller, but it does not say anything about convergence.  We do not want to repeat the errors that earlier researchers made in static assignment (e.g. use MSA and then stop if the change rate falls underneath a fixed threshold).

**Comment by eBimPy** [comment]
Hello, 
First, thank you for your quick and clear answer. Do you have any documentation or a link on how the convergence slope is calculated?
Thanks

**Comment by sebhoerl** [comment]
Not yet, but the code is here: https://github.com/eqasim-org/eqasim-java/blob/develop/core/src/main/java/org/eqasim/core/simulation/termination/EqasimTerminationCriterion.java

Would be good to have an optional implementation of this in matsim-libs, something to keep in mind for the next developer meeting. 

@kainagel Yes, this is a good point. Btw, I emailed you on a relatively urgent matter, just a quick pointer in case you haven't seen it ;)

**Comment by eBimPy** [comment]
Hello,

Thanks for your quick reply.
I'm try to run the ile-de-france for 5% (and 20%) with eqasim-java in Intellij-idea-community (-Xmx100G). The execution stoped just a begining of iteration = 1. with error :

2025-01-31T14:39:33,614 ERROR AbstractMultithreadedModule$ExceptionHandler:211 Thread DiscreteModeChoiceAlgorithm.34 died with exception. Will stop after all threads finished.
java.lang.OutOfMemoryError: Java heap space
	at ch.sbb.matsim.routing.pt.raptor.SwissRailRaptorCore.exploreRoutes(SwissRailRaptorCore.java:715) ~[matsim-2025.0-PR3568.jar:?]
	at ch.sbb.matsim.routing.pt.raptor.SwissRailRaptorCore.calcLeastCostRoute(SwissRailRaptorCore.java:251) ~[matsim-2025.0-PR3568.jar:?]
	at ch.sbb.matsim.routing.pt.raptor.SwissRailRaptor.calcRoute(SwissRailRaptor.java:96) ~[matsim-2025.0-PR3568.jar:?]
	at ch.sbb.matsim.routing.pt.raptor.SwissRailRaptorRoutingModule.calcRoute(SwissRailRaptorRoutingModule.java:70) ~[matsim-2025.0-PR3568.jar:?]
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:182) ~[matsim-2025.0-PR3568.jar:?]
	at org.matsim.contribs.discrete_mode_choice.components.estimators.AbstractTripRouterEstimator.estimateTrip(AbstractTripRouterEstimator.java:67) ~[discrete_mode_choice-2025.0-PR3568.jar:?]
	at org.matsim.contribs.discrete_mode_choice.model.estimation.CachedTripEstimator.estimateTrip(CachedTripEstimator.java:42) ~[discrete_mode_choice-2025.0-PR3568.jar:?]
	at org.matsim.contribs.discrete_mode_choice.components.estimators.CumulativeTourEstimator.estimateTour(CumulativeTourEstimator.java:50) ~[discrete_mode_choice-2025.0-PR3568.jar:?]
	at org.matsim.contribs.discrete_mode_choice.model.tour_based.TourBasedModel.chooseModes(TourBasedModel.java:93) ~[discrete_mode_choice-2025.0-PR3568.jar:?]
	at org.matsim.contribs.discrete_mode_choice.replanning.DiscreteModeChoiceAlgorithm.run(DiscreteModeChoiceAlgorithm.java:54) ~[discrete_mode_choice-2025.0-PR3568.jar:?]
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:235) ~[matsim-2025.0-PR3568.jar:?]
	at java.base/java.lang.Thread.runWith(Thread.java:1588) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1575) [?:?]

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "DiscreteModeChoiceAlgorithm.48"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "DiscreteModeChoiceAlgorithm.3"

**Comment by sebhoerl** [comment]
As the error message says, you are "out of memory" ;) 
You have to increase memory using `-Xmx64g` with `64` to be replaced by how much memory (in GB) you want to give.

**Comment by eBimPy** [comment]
Yes, but for 100GO and 5% population I think sufusant !

**Comment by kainagel** [comment]
Maybe it needs to be "g" instead of "G"?

**Comment by eBimPy** [comment]
I try with "-Xmx100g"

**Comment by sebhoerl** [comment]
Yes, but do you have 100 GB memory?

**Comment by eBimPy** [comment]
yes of course?

Debian-12.8.0 system
Memory 128 00 GiB
Processors 16 (2 sockets, 8 cors) [x86-64-v2-AES]
Hard Disk (scsi()) sizre = 2TO

**Comment by eBimPy** [comment]
Hello,
I found the mistake! The problem came from the parameter in the global module (in config xml file) where the number of threads requested is greater than that of the computer : 
   <param name="numberOfThreads" value="14" />


Thanks to all for your help and especially for your reactivity
