### ISSUE TITLE
Error :  There exists already a node with id = 0.

### ISSUE THREAD

**Issue by LorenaBR** [matsim-org/matsim-code-examples#15]
Hello,
i've already run my simulation without Public Transport and it works fine, but when i tryed to add Transport Public I got this error below. 

_Existing node: [id=0][coord=[x=176431.458652][y=8246433.09168]][type=2][nof_inlinks=3][nof_outlinks=1]
Node to be added: [id=0][coord=[x=176431.458652][y=8246433.09168]][type=null][nof_inlinks=0][nof_outlinks=0].
Node is not added to the network._

However, the node id has already been assigned and added to the network. 
Anyone can help-me to fix this error? 

Thank you for any help!

**Comment by mrieser** [comment]
The error message shows that you try to add a node with the same Id and same coordinate a second time to the network. 

> Anyone can help-me to fix this error?

Don't add the node a second time.

It's hard to give better advice as long as we don't know what your code is actually doing. Is it happening within code you wrote yourself? Then please show us your code or we cannot help. Is it happening when running an unmodified MATSim release? Then please tell us what class you actually started and what you tried to do, otherwise we cannot say what should be changed.

**Comment by LorenaBR** [comment]
Follow attached my config file, my transitschedule (with only one busline, just to know if it's right) and my network with all nodes and links.


[config_defaultDF.gz](https://github.com/matsim-org/matsim-code-examples/files/2444435/config_defaultDF.gz)
[transitschedule.gz](https://github.com/matsim-org/matsim-code-examples/files/2444436/transitschedule.gz)
[networkpt.gz](https://github.com/matsim-org/matsim-code-examples/files/2444437/networkpt.gz)

Thank you so much in advance for any input!

**Comment by mrieser** [comment]
The network itself looks fine, it only contains one node with id 0.
What code, what class did you execute when the error message appears? Could you share the whole logfile?

**Comment by LorenaBR** [comment]
Error in custom provider, java.lang.IllegalArgumentException: There exists already a node with id = 0.
Existing node: [id=0][coord=[x=176431.458652][y=8246433.09168]][type=2][nof_inlinks=3][nof_outlinks=1]
Node to be added: [id=0][coord=[x=176431.458652][y=8246433.09168]][type=null][nof_inlinks=0][nof_outlinks=0].
Node is not added to the network.
  at org.matsim.core.scenario.ScenarioByConfigModule.createScenario(ScenarioByConfigModule.java:9) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.scenario.ScenarioByConfigModule)
  at org.matsim.core.scenario.ScenarioByConfigModule.createScenario(ScenarioByConfigModule.java:9) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.scenario.ScenarioByConfigModule)
  while locating org.matsim.api.core.v01.Scenario
    for the 1st parameter of org.matsim.core.scenario.ScenarioByInstanceModule.providePopulation(ScenarioByInstanceModule.java:43)
  while locating org.matsim.api.core.v01.population.Population
    for the 1st parameter of org.matsim.core.scenario.ScenarioByInstanceModule.providePopulationFactory(ScenarioByInstanceModule.java:47)
  while locating org.matsim.api.core.v01.population.PopulationFactory
    for field at org.matsim.core.router.FreespeedFactorRouting.populationFactory(FreespeedFactorRouting.java:18)
  at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:55) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$1 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.router.TripRouterModule)
Caused by: java.lang.IllegalArgumentException: There exists already a node with id = 0.
Existing node: [id=0][coord=[x=176431.458652][y=8246433.09168]][type=2][nof_inlinks=3][nof_outlinks=1]
Node to be added: [id=0][coord=[x=176431.458652][y=8246433.09168]][type=null][nof_inlinks=0][nof_outlinks=0].
Node is not added to the network.
	at org.matsim.core.network.NetworkImpl.addNode(NetworkImpl.java:179)
	at org.matsim.core.network.io.NetworkReaderMatsimV1.startNode(NetworkReaderMatsimV1.java:168)
	at org.matsim.core.network.io.NetworkReaderMatsimV1.startTag(NetworkReaderMatsimV1.java:78)
	at org.matsim.core.network.io.MatsimNetworkReader.startTag(MatsimNetworkReader.java:75)
	at org.matsim.core.utils.io.MatsimXmlParser.startElement(MatsimXmlParser.java:341)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.emptyElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:188)
	at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:164)
	at org.matsim.core.scenario.ScenarioLoaderImpl.loadNetwork(ScenarioLoaderImpl.java:134)
	at org.matsim.core.scenario.ScenarioLoaderImpl.loadScenario(ScenarioLoaderImpl.java:109)
	at org.matsim.core.scenario.ScenarioByConfigModule.createScenario(ScenarioByConfigModule.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.inject.internal.ProviderMethod$ReflectionProviderMethod.doProvision(ProviderMethod.java:292)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:402)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:402)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:54)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:132)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:93)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:80)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:80)
	at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:223)
	at com.google.inject.internal.Initializer.injectAll(Initializer.java:132)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:174)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236)
	at org.matsim.core.controler.Injector.createInjector(Injector.java:73)
	at org.matsim.core.controler.Controler.run(Controler.java:189)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)

**Comment by LorenaBR** [comment]
Hello, thanks for your answer, but i think i had fixed  the error when i changed some things in my Transit Schedule file. 
In fact I was not putting all the links that the bus line was going through, somehow I deleted some links.
 
Anyway, I have another question about the Transit Schedule file.

Is it really necessary to put the "DepartureOffset" in my stops (except in the last one)? 
From what I saw in the DTD it is not mandatory to use them, is just implied. But in the tutorials, they say it's mandatory. 
i'am asking that because i have no a idea how to collect these datas, and also because the traffic department does not have this information.
What should I do?
Thanks again!!

**Comment by mrieser** [comment]
departureOffset is required in all except the last one. The reason it's "implied" in the DTD is exactly that it not required in the last one. The departure offset says when the vehicle departs at that stop and usually comes from the schedule: If the vehicle starts at 08:05 at the first stop and at 08:07 at the second stop, the departure offset should be 00:02.
If you really don't have any actual schedule to deduct the times: Just assume some. As long as you set "awaitDeparture=false", the vehicle will just drive as fast as they can and might either be late or early if compared to the specified offsets, but it will not influence the simulation, only some delay analysis if you would do some.

**Comment by LorenaBR** [comment]
Thank you, it helped me a lot.
so I put the transitschedule in the validator and it worked, even left the message that the transit schedule was validated. 
however, when I run in matsim 8.0.1. jar, the following error appeared:
 
2018-10-19 13:43:34,797 ERROR QSim:316 got exception while cleaning up
java.lang.NullPointerException
	at org.matsim.core.mobsim.qsim.qnetsimengine.QNetsimEngine.afterSim(QNetsimEngine.java:246)
	at org.matsim.core.mobsim.qsim.QSim.cleanupSim(QSim.java:313)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:242)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:120)
	at org.matsim.core.controler.AbstractController$7.run(AbstractController.java:203)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:235)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:199)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:158)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:125)
	at org.matsim.core.controler.AbstractController.access$000(AbstractController.java:30)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:95)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:103)
	at org.matsim.core.controler.NewControler.run(NewControler.java:79)
	at org.matsim.core.controler.Controler.run(Controler.java:190)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2018-10-19 13:43:34,797 ERROR AbstractController:214 Mobsim did not complete normally! afterMobsimListeners will be called anyway.
java.lang.RuntimeException: UmlaufId could not be found. veh=null
	at org.matsim.pt.ReconstructingUmlaufBuilder.createUmlaeufe(ReconstructingUmlaufBuilder.java:80)
	at org.matsim.pt.ReconstructingUmlaufBuilder.build(ReconstructingUmlaufBuilder.java:71)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.getOrCreateUmlaufCache(TransitQSimEngine.java:145)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.createVehiclesAndDriversWithUmlaeufe(TransitQSimEngine.java:124)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.insertAgentsIntoMobsim(TransitQSimEngine.java:216)
	at org.matsim.core.mobsim.qsim.QSim.createAgents(QSim.java:273)
	at org.matsim.core.mobsim.qsim.QSim.prepareSim(QSim.java:258)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:219)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:120)
	at org.matsim.core.controler.AbstractController$7.run(AbstractController.java:203)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:235)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:199)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:158)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:125)
	at org.matsim.core.controler.AbstractController.access$000(AbstractController.java:30)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:95)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:103)
	at org.matsim.core.controler.NewControler.run(NewControler.java:79)
	at org.matsim.core.controler.Controler.run(Controler.java:190)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2018-10-19 13:43:34,797 ERROR MatsimRuntimeModifications:54 Getting uncaught Exception in Thread main
java.lang.RuntimeException: UmlaufId could not be found. veh=null
	at org.matsim.pt.ReconstructingUmlaufBuilder.createUmlaeufe(ReconstructingUmlaufBuilder.java:80)
	at org.matsim.pt.ReconstructingUmlaufBuilder.build(ReconstructingUmlaufBuilder.java:71)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.getOrCreateUmlaufCache(TransitQSimEngine.java:145)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.createVehiclesAndDriversWithUmlaeufe(TransitQSimEngine.java:124)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.insertAgentsIntoMobsim(TransitQSimEngine.java:216)
	at org.matsim.core.mobsim.qsim.QSim.createAgents(QSim.java:273)
	at org.matsim.core.mobsim.qsim.QSim.prepareSim(QSim.java:258)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:219)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:120)
	at org.matsim.core.controler.AbstractController$7.run(AbstractController.java:203)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:235)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:199)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:158)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:125)
	at org.matsim.core.controler.AbstractController.access$000(AbstractController.java:30)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:95)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:103)
	at org.matsim.core.controler.NewControler.run(NewControler.java:79)
	at org.matsim.core.controler.Controler.run(Controler.java:190)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2018-10-19 13:43:34,797 ERROR MatsimRuntimeModifications:60 ERROR --- This is an unexpected shutdown!
2018-10-19 13:43:34,797 ERROR MatsimRuntimeModifications:63 Shutdown possibly caused by the following Exception:
java.lang.RuntimeException: UmlaufId could not be found. veh=null
	at org.matsim.pt.ReconstructingUmlaufBuilder.createUmlaeufe(ReconstructingUmlaufBuilder.java:80)
	at org.matsim.pt.ReconstructingUmlaufBuilder.build(ReconstructingUmlaufBuilder.java:71)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.getOrCreateUmlaufCache(TransitQSimEngine.java:145)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.createVehiclesAndDriversWithUmlaeufe(TransitQSimEngine.java:124)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.insertAgentsIntoMobsim(TransitQSimEngine.java:216)
	at org.matsim.core.mobsim.qsim.QSim.createAgents(QSim.java:273)
	at org.matsim.core.mobsim.qsim.QSim.prepareSim(QSim.java:258)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:219)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:120)
	at org.matsim.core.controler.AbstractController$7.run(AbstractController.java:203)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:235)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:199)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:158)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:125)
	at org.matsim.core.controler.AbstractController.access$000(AbstractController.java:30)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:95)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:103)
	at org.matsim.core.controler.NewControler.run(NewControler.java:79)
	at org.matsim.core.controler.Controler.run(Controler.java:190)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2018-10-19 13:43:34,813 ERROR MatsimRuntimeModifications:78 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2018-10-19 13:43:34,813 ERROR MatsimRuntimeModifications:79 ERROR --- results should not be used for further analysis.
2018-10-19 13:43:34,813 ERROR MatsimRuntimeModifications:83 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.


Can you help-me with any ideas?

**Comment by LorenaBR** [comment]
In the documentation the vehicle identification is only implied (vehicleRefId), but when I try to run it always appears the error "veh = null". So i tried with just with one vehicle, one route/line, and one passenger, adding the vehicheRefId and it works.  
 
The problems is that here the buses serve different lines depending on their availability, so there's no way to know which bus serves which line, that's why i need to know if there is any possibility to replace the "VehicleRefId"?
Thanks one more time, MRieser. You've been very kind to me and helped me a lot!
