### ISSUE TITLE
Problems in running MATSim

### ISSUE THREAD

**Issue by yuh2017** [matsim-org/matsim-code-examples#16]
When I was running the equil example, I got the following error: javax.xml.bind.JAXB Class Not Found Exception. I am wondering if I should use java 8/9 rather than latest java

2018-10-01 22:33:30,652 ERROR MatsimRuntimeModifications$1:41 Getting uncaught Exception in Thread main
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException at org.matsim.core.controler.corelisteners.DumpDataAtEndImpl.dumpLanes(DumpDataAtEndImpl.java:199) at org.matsim.core.controler.corelisteners.DumpDataAtEndImpl.notifyShutdown(DumpDataAtEndImpl.java:130)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerShutdownEvent(ControlerListenerManagerImpl.java:122)
	at org.matsim.core.controler.AbstractController$1.shutdown(AbstractController.java:89)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:66)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 11 more

**Comment by mrieser** [comment]
Yes, this error is related to running MATSim with Java 10 or later. For the moment, it's best to run MATSim with Java 8 I think.
