### ISSUE TITLE
Attribute names

### ISSUE THREAD

**Issue by JWJoubert** [matsim-org/matsim-code-examples#186]
Maybe someone can help me with `Attribute`s. It seems only certain characters are allowed in the attribute name. I picked this up when running the `emissions` contrib. It successfully executed the simulation and created an events file with both the cold and warm emission events.

More specifically, in the `WarmEmissionEvent` we have two `Attribute`s: `CO2(rep)` and `CO2(total)`.

But when trying to parse the events file afterwards, I got the following error.

```
Attribute name "CO2" associated with an element type "event" must be followed by the ' = ' character.
Attribute name "CO2" associated with an element type "event" must be followed by the ' = ' character.
XML-FATAL: ./output/gauteng/output_events.xml.gz, line 7, column 140:
org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 140; Attribute name "CO2" associated with an element type "event" must be followed by the ' = ' character.
Exception in thread "main" org.matsim.core.utils.io.UncheckedIOException: org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 140; Attribute name "CO2" associated with an element type "event" must be followed by the ' = ' character.
        at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:199)
        at org.matsim.core.utils.io.MatsimXmlParser.readFile(MatsimXmlParser.java:149)
        at org.matsim.core.events.MatsimEventsReader.readFile(MatsimEventsReader.java:73)
        at org.matsim.csurtees.analysis.GautengGeneralGrid.processEvents(GautengGeneralGrid.java:92)
```

... any idea how to circumvent this error?

**Comment by mrieser** [comment]
Ouch. From what I've heard, they (@joemolloy ?) changed the code that it takes whatever attributes there are defined in the csv files. This poses a problem when they are directly used as xml attribute names in the events, as only a limited set of characters is allowed in attribute names, resulting in invalid XML event files.

We could catch this in the XML writer and replace the parentheses which likely cause the problem with other, supported characters. Then at least the file could (technically) be read back in. But this would pose other problems when reading the events, as now the emission types would no longer match and thus likely most emissions analyses would fail.

**Comment by joemolloy** [comment]
thats a tricky one, sorry your having so many issues with the module @JWJoubert 

This would either be a reason to go back to the enum method, or  to keep the flexibility of the csv attributes, the pollution events could be as so:
`<event ...... pollutants="C02;CO2(rep);PM10....` values="0.1;0.001;20;..." >

**Comment by joemolloy** [comment]
regarding the enums: 
The old pollutant enum only considered the following pollutants:
`CO("CO"), CO2_TOTAL("CO2_TOTAL"), FC("FC"), HC("HC"), NMHC("NMHC"), NOX("NOX"), NO2("NO2"), PM("PM"), SO2("SO2");`

and the test files for reading/writing emission events and the sample input files still reflect this, even though many more pollutants can now be processed.

**Comment by mrieser** [comment]
Alternative emissions syntax (proposal, to be discussed):
`<event .... emissions="CO2=0.1;CO2(rep)=0.001;PM10=20;..." />`

I understand the reasoning behind the `pollutants="..." values="..."` proposal that is is closer to a csv., but I somehow dislike having two lists where one has to take care of indices in order not to mix up things.

**Comment by kainagel** [comment]
Is it a totally stupid idea to consider to go back to enums?  Sometimes a good idea does not fly.  I moved the discussion to here: https://matsim.atlassian.net/browse/MATSIM-984 .
