### ISSUE TITLE
No route was found from node -103409 to node -361913

### ISSUE THREAD

**Issue by jiao1997** [matsim-org/matsim-code-examples#219]
Hello,
     I am doing mobsim on public transport,but when I run the MATSim GUI. I found a stop which has been shown below:

2019-10-17 22:19:31,816  WARN Dijkstra:307 No route was found from node -103409 to node -361913. Some possible reasons:
2019-10-17 22:19:31,816  WARN Dijkstra:308   * Network is not connected.  Run NetworkCleaner().
2019-10-17 22:19:31,817  WARN Dijkstra:309   * Network for considered mode does not even exist.  Modes need to be entered for each link in network.xml.
2019-10-17 22:19:31,817  WARN Dijkstra:310   * Network for considered mode is not connected to starting or ending point of route.  Setting insertingAccessEgressWalk to true may help.
2019-10-17 22:19:31,818  WARN Dijkstra:311 This will now return null, but it may fail later with a null pointer exception.
2019-10-17 22:19:31,842 ERROR QSim:314 got exception while cleaning up
java.lang.NullPointerException
	at org.matsim.core.mobsim.qsim.qnetsimengine.QNetsimEngine.afterSim(QNetsimEngine.java:240)
	at org.matsim.core.mobsim.qsim.QSim.cleanupSim(QSim.java:311)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:244)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:111)
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:192)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:224)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:188)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:147)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:114)
	at org.matsim.core.controler.AbstractController.access$0(AbstractController.java:112)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:84)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2019-10-17 22:19:31,907 ERROR AbstractController:203 Mobsim did not complete normally! afterMobsimListeners will be called anyway.
java.lang.RuntimeException: No route found from node -103409 to node -361913.
	at org.matsim.pt.UmlaufInterpolator.insertWenden(UmlaufInterpolator.java:50)
	at org.matsim.pt.UmlaufInterpolator.addUmlaufStueckToUmlauf(UmlaufInterpolator.java:38)
	at org.matsim.pt.ReconstructingUmlaufBuilder.createUmlaeufe(ReconstructingUmlaufBuilder.java:87)
	at org.matsim.pt.ReconstructingUmlaufBuilder.build(ReconstructingUmlaufBuilder.java:72)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.getOrCreateUmlaufCache(TransitQSimEngine.java:145)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.createVehiclesAndDriversWithUmlaeufe(TransitQSimEngine.java:124)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.insertAgentsIntoMobsim(TransitQSimEngine.java:216)
	at org.matsim.core.mobsim.qsim.QSim.createAgents(QSim.java:272)
	at org.matsim.core.mobsim.qsim.QSim.prepareSim(QSim.java:257)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:221)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:111)
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:192)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:224)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:188)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:147)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:114)
	at org.matsim.core.controler.AbstractController.access$0(AbstractController.java:112)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:84)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2019-10-17 22:19:31,912 ERROR MatsimRuntimeModifications:54 Getting uncaught Exception in Thread main
java.lang.RuntimeException: No route found from node -103409 to node -361913.
	at org.matsim.pt.UmlaufInterpolator.insertWenden(UmlaufInterpolator.java:50)
	at org.matsim.pt.UmlaufInterpolator.addUmlaufStueckToUmlauf(UmlaufInterpolator.java:38)
	at org.matsim.pt.ReconstructingUmlaufBuilder.createUmlaeufe(ReconstructingUmlaufBuilder.java:87)
	at org.matsim.pt.ReconstructingUmlaufBuilder.build(ReconstructingUmlaufBuilder.java:72)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.getOrCreateUmlaufCache(TransitQSimEngine.java:145)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.createVehiclesAndDriversWithUmlaeufe(TransitQSimEngine.java:124)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.insertAgentsIntoMobsim(TransitQSimEngine.java:216)
	at org.matsim.core.mobsim.qsim.QSim.createAgents(QSim.java:272)
	at org.matsim.core.mobsim.qsim.QSim.prepareSim(QSim.java:257)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:221)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:111)
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:192)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:224)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:188)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:147)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:114)
	at org.matsim.core.controler.AbstractController.access$0(AbstractController.java:112)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:84)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2019-10-17 22:19:31,912 ERROR MatsimRuntimeModifications:60 ERROR --- This is an unexpected shutdown!
2019-10-17 22:19:31,913 ERROR MatsimRuntimeModifications:63 Shutdown possibly caused by the following Exception:
java.lang.RuntimeException: No route found from node -103409 to node -361913.
	at org.matsim.pt.UmlaufInterpolator.insertWenden(UmlaufInterpolator.java:50)
	at org.matsim.pt.UmlaufInterpolator.addUmlaufStueckToUmlauf(UmlaufInterpolator.java:38)
	at org.matsim.pt.ReconstructingUmlaufBuilder.createUmlaeufe(ReconstructingUmlaufBuilder.java:87)
	at org.matsim.pt.ReconstructingUmlaufBuilder.build(ReconstructingUmlaufBuilder.java:72)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.getOrCreateUmlaufCache(TransitQSimEngine.java:145)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.createVehiclesAndDriversWithUmlaeufe(TransitQSimEngine.java:124)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.insertAgentsIntoMobsim(TransitQSimEngine.java:216)
	at org.matsim.core.mobsim.qsim.QSim.createAgents(QSim.java:272)
	at org.matsim.core.mobsim.qsim.QSim.prepareSim(QSim.java:257)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:221)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:111)
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:192)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:224)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:188)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:147)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:114)
	at org.matsim.core.controler.AbstractController.access$0(AbstractController.java:112)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:84)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)

Could anyone helps me ,I'll appreciate it.

**Comment by kainagel** [comment]
Hard to tell without looking at the specific case.  Normally, these are network coding problems.  Did you (indeed) run the network cleaner, as recommended in the log output?  It checks if the network is connected.  If that does not/did not help, remaining issues (which we should at some point integrate into the network cleaner) are:

* links of length zero lead to problems.  Make them larger; 1 meter is sufficient.

* There is a problem with the modal subnetworks.  I don't think that this is an issue here since pt (annoyingly and wrongly) routes on the car network, but it could still be the case that your overall network is connected but the modal subnetwork is not.  (The modal subnetwork is obtained by only retaining those links that belong to a certain mode).

---

All of the above things are fairly easy to integrate into a typical matsim startup script:
```
...
Scenario scenario = ScenarioUtils.loadScenario( config ) ;

for ( Link link : scenario.getNetwork().getLinks().values() ) {
   if ( link.getLength <= 0. ) {
      link.setLength(1.) ;
   }
}
...
```

However, you imply that you are using MATSim directly from the GUI, so you may have to do "by hand".  You could load your network into VIA and try to route between the above nodes.

---

And yes, it would make sense to integrate these data consistency checks into the matsim startup sequence.  Such things are, however, not _that_ easy, since there are always exceptions where it is ok to violate the general rules, and forbidding this then results in awkward modeling choices.  So we are a bit slow in doing this.

**Comment by jiao1997** [comment]
> Hard to tell without looking at the specific case. Normally, these are network coding problems. Did you (indeed) run the network cleaner, as recommended in the log output? It checks if the network is connected. If that does not/did not help, remaining issues (which we should at some point integrate into the network cleaner) are: * links of length zero lead to problems. Make them larger; 1 meter is sufficient. * There is a problem with the modal subnetworks. I don't think that this is an issue here since pt (annoyingly and wrongly) routes on the car network, but it could still be the case that your overall network is connected but the modal subnetwork is not. (The modal subnetwork is obtained by only retaining those links that belong to a certain mode).
> […](#)
> --- All of the above things are fairly easy to integrate into a typical matsim startup script: ``` ... Scenario scenario = ScenarioUtils.loadScenario( config ) ; for ( Link link : scenario.getNetwork().getLinks().values() ) { if ( link.getLength <= 0. ) { link.setLength(1.) ; } } ... ``` However, you imply that you are using MATSim directly from the GUI, so you may have to do "by hand". You could load your network into VIA and try to route between the above nodes.
> --- And yes, it would make sense to integrate these data consistency checks into the matsim startup sequence. Such things are, however, not _that_ easy, since there are always exceptions where it is ok to violate the general rules, and forbidding this then results in awkward modeling choices. So we are a bit slow in doing this.


Thank you a lot for your reply.I have checked my network.xml in VIA.I find that there are some nodes are not connected,such as the following pictures.I wander if it is the exact problem that caused the error.
![image](https://user-images.githubusercontent.com/35290093/67370959-2ecfdd80-f5ae-11e9-816e-f76f62168073.png)

**Comment by kainagel** [comment]
Hard to tell without legend.  But the blue dot looks more like an activity location.

Could you make your network available to me somehow (preferably, just upload to this issue tracker)?

**Comment by jiao1997** [comment]
> Hard to tell without legend. But the blue dot looks more like an activity location. Could you make your network available to me somehow (preferably, just upload to this issue tracker)?

I'm so sorry that I can't upload the network.xml because of the security. And could I ask another question that ,if my network are not connected,could the pt mobism run well?

**Comment by kainagel** [comment]
I don't know enough about the workings of the pt simulation to know if it will work or not with a disconnected network.  In principle it should since the routes are coded inside transitSchedule.  I have found out that MATSim actually works with disconnected networks as long as no agent tries to go from one part of the network to the other.  However, it is difficult to debug and thus, if at all, only advised to people who know MATSim will.

**Comment by jiao1997** [comment]
Dear Professor:
  Thank you very much! But in real cities, there may be disconnected roads, such as separated by buildings, or isolated roads. Can I set walking as the leg mode when agents try to cross these roads?
