### ISSUE TITLE
Configuring Vehicles with Vehicle Definitions

### ISSUE THREAD

**Issue by benjaminBrownlee** [matsim-org/matsim-code-examples#227]
I have been given a model that contains very detailed data regarding the nature, location, and duration of the activities and travels of each agent in a population and am tasked with tuning a simulation to fit it. For my first implementation of the model, I used only plans that contained only legs for single occupancy vehicles. I am now working on adding multimodal (for walking and biking modes) as well as vehicle definitions (for HOV modes). However, I am having problems trying to work the vehicle data into the input of the simulation.

Due to the nature of my sources data, I know which vehicle every agent is supposed to be in for any given trip, but I am not sure how to build a plans, configuration, and vehicles files to support sharable vehicles assigned to legs. The only documentation I can find for vehicle definitions for MATSim are [this community post](https://matsim.atlassian.net/wiki/spaces/MATPUB/pages/84246576/Mixed+traffic) and section 11.1 of the user guide. The former only provides an example definitions file/configuration where a vehicle id corresponds to an agent id, which is not helpful in the situation where a single vehicle is used by multiple agents or where a single agent utilizes multiple vehicles. The latter seems to hint at what I am trying to get when it describes a scenario in which "a vehicle may be shared between family members, but one member will be late in returning a vehicle", but its explanation for config file is minimal and the structure of the vehicle definitions and plans files nonexistent.

Could someone point me to some documentation regarding how to configure vehicle definitions for MATSim, especially given very detailed, disaggregate input data? Is what I'm trying to do even possible with the standard MATSim input and configuration files?

**Comment by JWJoubert** [comment]
Hi @benjaminBrownlee 
> Is what I'm trying to do even possible with the standard MATSim input

I believe it is, and even though I (unfortunately) do not have a quick answer for you, maybe just worth knowing: the entire machinery dealing with `Vehicle`s and `VehicleType`s has recently undergone significant changes. So documentation, per se, might not be updated to reflect these yet. Are you working on a full or weekly release? Or on the Head of the MATSim repository itself?

**Comment by benjaminBrownlee** [comment]
Thanks for the swift reply @JWJoubert 

I have been just using the most recent release of MATSim (11.0). Is it typical for those working with MATSim to use developmental builds of MATSim? Should I be using a developmental build?

I know that vehicles definitions are supported to some degree with MATSim, just all the use cases and documentation that I have seen has not detailed how to assign vehicles to agents or legs beyond assigning a single vehicle to a single agent. I had assumed that it could be as simple building a vehicles definition file, adding the file and its settings in the config, and then putting the vehicle ids on the input plans somewhere. However, neither the documentation (section 2.2.2.3) nor the [plans dtd file](http://www.matsim.org/files/dtd/plans_v4.dtd) mention vehicles in the input plans file structure.

**Comment by JWJoubert** [comment]
> Is it typical for those working with MATSim to use developmental builds of MATSim?

@benjaminBrownlee MATSim is a dynamic piece of machinery. The phrase _dynamic laboratory_ probably describes it better. New features, fixes, and code cleanups occur continuously, so you may want to look at the weekly builds: more stable than the head, and more of the recent features. I have, unfortunately, only used `Vehicle`s to the extent that I assign a (unique) vehicle _once_ at the start of the simulation. Hopefully, one of the others "in-the-know" can respond.

**Comment by kainagel** [comment]
@benjaminBrownlee (1) Using the release is the right way to go as long as you can live with it.  The most recent release is 11.0.  The remark regarding the `VehicleType` infrastructure should be read in the way that, if infrastructure with release 11.0 turns out to be insufficient for your needs, the improvements that are already in the development head may help you out.  One thing that is added for vehicle types v2 is "free form" attributes, i.e. you are not restricted to attributes that are in the dtd.  On the other hand, we try to be backwards compatible, so a vehicle type v1 file should remain readable.  

(2) The technical issue is that the vehicle is in the route, not in the leg.  So there is roughly
```
<leg ... >
   <route ... vehicleRefId="..." ... >... </route>
</leg>
```
You should be able to see this in some output plans file.  Possibly, leg would be better to memorize the vehicle, but that currently ain't the case.

Unfortunately, I would need to play around with it to figure out how all the elements of the implementation cooperate.  Could you please try the following:
1. run matsim from iteration 0 to iteration 0
1. check if you can make sense of the resulting output plans
1. replace vehicle IDs the way you need them
1. run again from iteration 0 to iteration 0 and see if it does what you need.  Then maybe from iteration 0 to iteration 1.  Etc.

There is also a `vehicleBehavior` switch in the qsim config group.  You probably want `wait` here ... but I would try with `teleportation` (= the default) first until what you get makes sense.

One issue probably is initial vehicle placement since the corresponding field is missing in the `vehicle` data structure.  I can't really say what that will do.  Realistically, you will have to pre-process your input somewhat; look e.g. at https://github.com/matsim-vsp/matsim-berlin/blob/5.5.x/src/main/java/org/matsim/run/drt/RunDrtOpenBerlinScenario.java how we construct your run scripts.

From here on, it depends on what you need.  If you only need route choice and time choice, you may be able to move forward.  If you also want mode choice, you run into the problem that it is not clear which vehicle people are supposed to use.

Please let us know how far this takes you.  If you make your code with a runnable example available on github, I would also try to help.  

If you figure it out, we would be very happy if you could contribute documentation.  In this case maybe best as a runnable example test case (which we then might want to include into the core).

**Comment by benjaminBrownlee** [comment]
Thanks for you help @kainagel 

I'm going to test what you are suggesting here (using the output plans format as the input) and see if I can get the multimodal and vehicle definitions running together well. The configuration file may take some troubleshooting, but I'll let you know how it goes. I have my code on github, but I actually just run MATSim from a standard standalone jar and construct all the input files (plans, config, vehicles, etc.) by pulling data from a MySQL server and formatting into files using Python. I certainly can create a gist to the input files I am using on if that helps you help me.

**Comment by kainagel** [comment]
It would help me help you. :-)

**Comment by benjaminBrownlee** [comment]
I just had a couple quick questions for inital debug, and then I can get you my files if issues persist (as they most likely will).

1. How do I specify that a mode has a routable subnetwork but does not need a vehicle definition? In my case, I only define vehicles for the purpose for controlling vehicle sharing, so walk and bike modes clearly don't need defined vehicles and should be assigned vehicle ids in the default manner (clearly walk should be null). However, these modes are still considered main modes since there exists a network for them, but these networks operate at a more simplified form simulation in which agents inside these modes do not interact with each other or other modes (if my understanding of the multimodal features are correct). I guess I'm just getting confused since I specify modes in several modules (`qsim`, `planscalcroute`) and I'm starting to get confused between main modes, seep modes, network modes, etc.

2. Biking and walking modes would not be considered teleported modes even though they lack the queue and lane simulation properties that the vehicular network has, correct? Or is this how multimodal defines the behavior of these network modes?

3. You suggested using an output plans files with the "vehicleRefId" attribute modified as the input plans file. Would it be equally valid it use an input plans with empty route tags having the vehicle attribute, or will defining the route tag require I specify the initial routing?

For item 3, an example fo what I'm suggesting would be,
```xml
<plan>
   <act ... ... />
   <leg ... ... >
      <route vehicleRefId="x"></route>
   </leg>
   <act ... ... />
   ....
```

**Comment by kainagel** [comment]
I think that I had already pointed to Chapter 7 of MATSim user guide (pdf)<http://ci.matsim.org:8080/job/MATSim-Book/ws/partOne-latest.pdf> , haven't I?

Re 1.: All network modes need vehicles, even walk.  This makes implementation more straightforward.  Think about it as a device to specify maximum speed, space consumption, and capacity consumption.

"main" mode in the qsim is a misnomer; it should be "network" mode.  We are always somewhat (but not totally) hesitant to change config names since they break older config files.  Maybe we should change this one as well.

You can route a mode on a network (planscalcroute) but not execute it on the network.  The other way round is not possible (if you think about it).  So you can do (using approximate syntaxi)

<planscalcroute>
    <networkModes="bike,car"/>
</planscalcroute>
<qsim>
   <mainModes="car"/>
</qsim>

but not

<planscalcroute>
    <networkModes="car"/>
</planscalcroute>
<qsim>
   <mainModes="bike,car"/> // bike will fail since not routed on the network
</qsim>

So I think that your approach would be

(a) annotate network links for all modes that you want to have routed
(b) specify mode vehicles for all modes that you want to have routed
(c) specify all modes that you want to have routed in planscalcroute
(d) specify only the modes that you want to have congested in qsim

Seep mode is a different thing, best ignore (means that bicycles can seep past congested cars).

Note that "pt" and "drt" are _not_ routed network modes, so they follow other logic.  Please initially debug without them.  (You can still have both of them as "teleported" modes.)

Re 2: answered above

Re 3: I can't say, sorry.  I know that we need to find a better solution for this, but so far we have never used this feature (instead, my group went into "mobility as a service") so we put elements of private vehicle sharing in when we encountered corresponding code for other reasons, but never fully plugged it together.  My expectation would be that what you suggest would _not_ work, since (1) routes need start and end link (which you could provide), and (2) matsim takes existing routes for granted, even if they are empty.  And will complain later that they do not physically connect start link and end link.

**Comment by kainagel** [comment]
Are you using the matsim GUI, or using matsim out of an IDE?  (I may have asked that question before.). If using out of an IDE, would you mind putting it into a github repo and give me access?  Then I could try to help with the "vehicle sharing within same household" aspect (your item 3).

**Comment by benjaminBrownlee** [comment]
@kainagel Sorry for the wait. I had to change a lot of the input data processing to be ready for both multimodal and vehicle sharing, that and work, school, and research keeps a man busy. I have here a 0.01% sample (240 agents) of my simulation which includes at least one of each type of travel. I was able to run the simulation without the per route vehicle definitions (just vehicle type definitions), but when I tried running the output plans of that run merged with my vehicle data as the input plans, I got a null pointer exception that I'm not sure how to remedy. I have the input and log files available here: https://github.com/ChesterIcarus/SimulationDebug.

Thanks a lot for offering to help me.

**Comment by kainagel** [comment]
Dear @benjaminBrownlee , thank you for making material available to me.  Unfortunately, I am still not clear if you are using the MATSim GUI, or are working from an IDE.  Could you please let me know?  Thanks ...

**Comment by benjaminBrownlee** [comment]
@kainagel Sorry, I'm definitely working from an IDE (running from terminal). I was unaware that MATSim came with a GUI tool. I've also just added the network that I am using to the repository I shared earlier.

**Comment by kainagel** [comment]
@benjaminBrownlee : I couldn't push back to your repo so I pushed to https://github.com/kainagel/SimulationDebug .  You could either pull from there, or give me permission for your repo.

I added all the files from matsim-example-project.  You should be able to maven-import the whole repo into your IDE.  See https://matsim.org/downloads/ (which actually also explains the GUI thing).  Let me know if you like or don't like the maven-import; at this point we can still switch to the GUI.

I then added a test case, `RunMatsimTest`.  It will run your `config_formatted.xml`.  I modified the path names so that it correctly loads all the other items.  

The code eventually stops with error message

`
java.lang.RuntimeException: java.lang.RuntimeException: could not find requested vehicle 2696060 in simulation for agent org.matsim.core.mobsim.qsim.agents.BasicPlanAgentImpl@792364e9 with id 4025493 on link 331359 at time 45702.0. aborting `

And indeed, no vehicle with ID 2696060 is in the vehicles file.

Maybe when generating the sample something went wrong?  If there is a "full" vehicles file, might be easiest to just push that; there is no problem if there are many unused vehicles.

**Comment by benjaminBrownlee** [comment]
This was definitely the first thing I checked when this error popped up. Just to double check, I just now went to https://github.com/kainagel/SimulationDebug/blob/master/vehicles_formatted.xml and searched for "2696060" and found this on line 205:

![image](https://user-images.githubusercontent.com/29786277/69100507-9268f180-0a1a-11ea-81ef-3be2d06bd27e.png)

Is this not correct? I assumed it had something more to do with when or how vehicles were spanned into the simulation, which I had no idea of how to control.

**Comment by kainagel** [comment]
Sorry, my fault, not sure what I looked at.

**Comment by kainagel** [comment]
Found it.  Its a bug.  :-( The complicated logic that retrofits our so-called mode-vehicles (in `PopulationAgentSource`) in fact does not allow a second vehicle for the same mode.

Can't say how long a fix might take ...

First step would be to throw out these cases and see if it works without them.

Possibility to proceed might be to define modes "car2", "car3", etc., and use them for those trips where a second/3rd/4th car is used.  I have no intuition which ramifications this will have. 

---

I just fixed it in the development head.  You would need to go to 12.0-SNAPSHOT, and eventually to a weekly release.  

I also backported it to the 11.x branch, but I would need to find someone who deploys, I don't really have time to do this myself. 

And let's see what the regression tests say.

PS: You seem to have some cases where the routes are not consistent with the network.  Or at least that is the meaning of "Cannot move vehicle xxx from link aaa to link bbb."  Or there is another bug.

**Comment by Janekdererste** [comment]
As a site note, this was not a bug but a feature :-) @kainagel we decided to have only one vehicle per mode and agent in favour of having a simpler data structure. This way we have a simple vehicle map with mode -> Vehicle.

If we would allow multiple vehicles per mode the data structure would become more cumbersome since it would be mode -> List<Vehicle> which, we thought back then, would not be necessary for most use cases. In addition it adds the problem of coming up with a method for selecting the right vehicle for routing.

**Comment by benjaminBrownlee** [comment]
@kainagel  I ran the simulation again using the most recent snapshot available and was able to run the simulation for a few iterations before getting another fatal error. This one appears to be related to the network. As you pointed out earlier, I seemed to be having other network related issues, so I'm going to regenerate and clean a new network for this simulation.

```
2019-11-20 09:13:37,485  INFO GenericPlanStrategyImpl:125 Plan-Strategy finished, 218 plans handled. Strategy: BestPlanSelector
2019-11-20 09:13:37,485  INFO AbstractMultithreadedModule:141 [PlanRouter] starting 20 threads, handling 22 plans
2019-11-20 09:13:37,970  WARN AStarEuclidean:171 finding totalCost=0.0; this will often (or always?) lead to a null pointer exception later.  In my own case, it was related to a network having freespeed infinity at places.  kai, jan'18
2019-11-20 09:13:37,985 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.15 died with exception. Will stop after all threads finished.
java.lang.NullPointerException
        at org.matsim.core.router.AStarEuclidean.addToPendingNodes(AStarEuclidean.java:176)
        at org.matsim.core.router.Dijkstra.relaxNodeLogic(Dijkstra.java:423)
        at org.matsim.core.router.Dijkstra.relaxNode(Dijkstra.java:394)
        at org.matsim.core.router.AStarLandmarks.relaxNode(AStarLandmarks.java:138)
        at org.matsim.core.router.Dijkstra.searchLogic(Dijkstra.java:318)
        at org.matsim.core.router.Dijkstra.calcLeastCostPath(Dijkstra.java:237)
        at org.matsim.core.router.AStarLandmarks.calcLeastCostPath(AStarLandmarks.java:125)
        at org.matsim.core.router.NetworkRoutingModule.calcRoute(NetworkRoutingModule.java:95)
        at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:200)
        at org.matsim.core.router.PlanRouter.run(PlanRouter.java:90)
        at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

---

@Janekdererste If the single vehicle per mode per agent was an intended feature, will it remain to be such a feature going forward? By that I mean should I expect MATSim to behave like what kainagel has done in the most recent snapshot, or should I implement the alternative solution of creating redundant vehicle definitions to prevent modes from conflicting? The latter is certainly achievable, I would just need to figure out how to resolve all the potential conflicts (ie a vehicle is an agent's second vehicle but another's third or fourth).

**Comment by kainagel** [comment]
Thanks for the reminder.  I remember dimly.  ...  However, I don't think that that needs to prevent us from loading all vehicles that are in the vehicles file in the qsim. Which is what I put into the suggested bugfix.

**Comment by benjaminBrownlee** [comment]
@kainagel Is it appropriate to continue this thread as I try to implement public transit alongside multimodial (recall you suggested we initially debug without it), or should I open a new issue? I have been trying to follow [this tutorial](https://matsim.atlassian.net/wiki/spaces/MATPUB/pages/83099693/Transit+Tutorial) but have ran into some problems, and I'm not sure if they are related to the multimodial aspects of my configuration. I can update the multimodial repository with my new public transit version.
