### ISSUE TITLE
"No Bean Validation provider could be found" when running GUI

### ISSUE THREAD

**Issue by rutym** [matsim-org/matsim-code-examples#230]
Hi all.
I'm trying to run MATsim using IntelliJ. I've downloaded MATsim's entire project directory and am using Java8 as required.
Since it's my first time running MATSim, I wanted to play a bit with examples and use the GUI to do so. I've build the dependencies from the maven 'pom' file and am trying to run the GUI. The GUI opens up and I am able to choose a configuration file, but when clicking the 'start MATsim' button, I get the following error:
`Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.matsim.core.config.consistency.ConfigConsistencyCheckerImpl.checkConsistency(ConfigConsistencyCheckerImpl.java:55)
	at org.matsim.core.config.Config.checkConsistency(Config.java:225)
	at org.matsim.core.controler.Controler.run(Controler.java:228)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
Caused by: javax.validation.NoProviderFoundException: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:291)
	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:103)
	at org.matsim.core.config.consistency.BeanValidationConfigConsistencyChecker.<clinit>(BeanValidationConfigConsistencyChecker.java:41)
	... 5 more`

A quick lookup online suggest I'm missing a maven dependency, but I have all required dependencies for the validation:
`<dependency>
  <groupId>javax.validation</groupId>
  <artifactId>validation-api</artifactId>
  <version>2.0.1.Final</version>
</dependency>
<dependency>
  <groupId>org.hibernate.validator</groupId>
  <artifactId>hibernate-validator</artifactId>
  <version>6.0.9.Final</version>
</dependency>
<dependency>
  <groupId>org.hibernate.validator</groupId>
  <artifactId>hibernate-validator-annotation-processor</artifactId>
  <version>6.0.9.Final</version>
</dependency>
<dependency>
  <groupId>org.glassfish</groupId>
  <artifactId>javax.el</artifactId>
  <version>3.0.1-b10</version>
</dependency>`

What am I missing? I assumed that using the GUI, I don't need to pass any more paramters. Am I suppose to Add a validator definition to one of the 'Controller' files?
Any other ideas?
Thanks
Ruty

**Comment by kainagel** [comment]
Hello,

could you please describe a bit more how you are using matsim?  In general, the recommended way is to _not_ download matsim, but use it as a maven dependency.  See matsim.org/downloads<http://matsim.org/downloads> .

However, your problem "feels" more like a maven problem.  I have to say that the bean validator is (I think) not in the 10.0 release but only in the development head, so we don't have experiences with it yet.  Maybe the missing dependency is added as a "compile" but _not_ a "runtime" dependency?

Maybe someone else has more intuition here than I do ...

Best wishes, Kai

**Comment by michalmac** [comment]
I was not able to reproduce this with 11.0 or the current development snapshot. Try updating maven dependencies.
