### ISSUE TITLE
Error in reading Config v2

### ISSUE THREAD

**Issue by JWJoubert** [matsim-org/matsim-code-examples#232]
Hi, I have code that was running, and after dependency updates, oops. I tried to resolve it locally, but it seems to be an inconsistency. In the config (v2) file there is a module:

```	
<module name="TimeAllocationMutator" >
	<!-- Default:true; Defines whether time mutation changes an activity's duration. -->
	<param name="mutationAffectsDuration" value="true" />
	<!-- Default:1800.0; Defines how many seconds a time mutation can maximally shift a time. -->
	<param name="mutationRange" value="1800.0" />
	<!-- false; Use individual settings for each subpopulation. If enabled but no settings are found, regular settings are uses as fallback. -->
	<param name="useIndividualSettingsForSubpopulations" value="false" />
</module>
```

But when executing I get the following error thrown by the `ReflectiveConfigGroup`
```
2019-11-04 20:24:21,879  INFO MatsimXmlParser:275 Trying to load http://www.matsim.org/files/dtd/config_v2.dtd. In some cases (e.g. network interface up but no connection), this may take a bit.
Exception in thread "main" java.lang.IllegalArgumentException: Module TimeAllocationMutator of type org.matsim.core.config.groups.TimeAllocationMutatorConfigGroup doesn't accept unkown parameters. Parameter useIndividualSettingsForSubpopulations is not part of the valid parameters: [mutationRange, mutationAffectsDuration]
        at org.matsim.core.config.ReflectiveConfigGroup.addParam(ReflectiveConfigGroup.java:225)
        at org.matsim.core.config.ConfigReaderMatsimV2.startParameter(ConfigReaderMatsimV2.java:71)
        at org.matsim.core.config.ConfigReaderMatsimV2.startTag(ConfigReaderMatsimV2.java:61)
        at org.matsim.core.config.ConfigReader.startTag(ConfigReader.java:67)
        at org.matsim.core.utils.io.MatsimXmlParser.startElement(MatsimXmlParser.java:346)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
```

Removing the `TimeAllocationMutator` works, but I don't think the error is correct.

**Comment by kainagel** [comment]
I switched off XML usage of "useIndividualSettingsForSubpopulations", since I was/am sceptical if/that we should support such things.  If we do, IMO we will end up with PTV-style behaviorally homogeneous groups, and all the overhead that that implies.  The switch is still there for people who use it "in code".  If someone has a convincing use case for having it "in xml", we can clearly put it back (and memorize the use case inside the code).

In your case, the solution is simply to remove the "useIndividualSettingsForSubpopulations" setting since "false" is the default.
