### ISSUE TITLE
Congestion Pricing Help

### ISSUE THREAD

**Issue by RMJcar** [matsim-org/matsim-code-examples#24]
Hello,

I've been having trouble getting the congestion pricing module to work.
I executed the config file using eclipse, MATSIM 9.0, running configurations on RunRoadPricingUsingTollFactorExample.java using the config file as the input.

I got all the input to the point where it will run, but the second that the congestion pricing goes into affect, the below error is thrown and the simulation stops.

java.lang.NullPointerException
	at org.matsim.roadpricing.run.RunRoadPricingUsingTollFactorExample$1.getTollFactor(RunRoadPricingUsingTollFactorExample.java:61)
	at org.matsim.roadpricing.RoadPricingSchemeUsingTollFactor.getLinkCostInfo(RoadPricingSchemeUsingTollFactor.java:73)
	at org.matsim.roadpricing.CalcPaidToll$CordonTollBehaviour.handleEvent(CalcPaidToll.java:292)
	at org.matsim.roadpricing.CalcPaidToll.handleEvent(CalcPaidToll.java:100)
	at org.matsim.core.events.EventsManagerImpl.callHandlerFast(EventsManagerImpl.java:291)
	at org.matsim.core.events.EventsManagerImpl.computeEvent(EventsManagerImpl.java:222)
	at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:136)
	at org.matsim.core.events.SimStepParallelEventsManagerImpl$ProcessEventsRunnable.run(SimStepParallelEventsManagerImpl.java:329)
	at java.lang.Thread.run(Thread.java:745)
2018-10-21 04:30:02,816 ERROR AbstractController:210 Mobsim did not complete normally! afterMobsimListeners will be called anyway.
java.lang.RuntimeException: Exception while processing events. Cannot guarantee that all events have been fully processed.
	at org.matsim.core.events.SimStepParallelEventsManagerImpl.finishProcessing(SimStepParallelEventsManagerImpl.java:211)
	at org.matsim.core.mobsim.qsim.QSim.cleanupSim(QSim.java:319)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:243)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:120)
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:199)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:231)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:195)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121)
	at org.matsim.core.controler.AbstractController.access$0(AbstractController.java:119)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:91)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:99)
	at org.matsim.core.controler.NewControler.run(NewControler.java:79)
	at org.matsim.core.controler.Controler.run(Controler.java:205)
	at org.matsim.roadpricing.run.RunRoadPricingUsingTollFactorExample.main(RunRoadPricingUsingTollFactorExample.java:79)
Caused by: java.lang.NullPointerException
	at org.matsim.roadpricing.run.RunRoadPricingUsingTollFactorExample$1.getTollFactor(RunRoadPricingUsingTollFactorExample.java:61)
	at org.matsim.roadpricing.RoadPricingSchemeUsingTollFactor.getLinkCostInfo(RoadPricingSchemeUsingTollFactor.java:73)
	at org.matsim.roadpricing.CalcPaidToll$CordonTollBehaviour.handleEvent(CalcPaidToll.java:292)
	at org.matsim.roadpricing.CalcPaidToll.handleEvent(CalcPaidToll.java:100)
	at org.matsim.core.events.EventsManagerImpl.callHandlerFast(EventsManagerImpl.java:291)
	at org.matsim.core.events.EventsManagerImpl.computeEvent(EventsManagerImpl.java:222)
	at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:136)
	at org.matsim.core.events.SimStepParallelEventsManagerImpl$ProcessEventsRunnable.run(SimStepParallelEventsManagerImpl.java:329)

One of the possible reasons is that when I try tried to run the config file including the scenario module, but it would error out right away. 
<module name="scenario">
   <param name="useRoadpricing" value="true" />
 </module> 

Any suggestions on how to get it it working?

**Comment by kainagel** [comment]
Hello, could you please attach the full logfile?  Thanks ...

**Comment by RMJcar** [comment]
Thank you!
[BUILT.logfile.log](https://github.com/matsim-org/matsim-code-examples/files/2523018/BUILT.logfile.log)

**Comment by kainagel** [comment]
Sorry, somehow didn't get a notification when you attached the logfile, or overlooked it.  Unfortunately, doesn't help much.  Assuming that you are running from an unchanged `RunRoadPricingUsingTollFactorExample`, then line 61 is
```
if ( scenario.getVehicles().getVehicles().get( vehicleId ).getType().equals( someVehicleType ) ) {
```
You need to find out where the null pointer exception is coming from, by testing each component individually.  Possibly the `vehicleId` does not exist in the `official` vehicles container.  This could, for example, be a bus from the public transit module.  What I would try then is to make sure that the pt bus is a different vehicle type than the vehicles that you want to charge toll on, and exclude it in the if condition before.  Maybe something like
```
Vehicle vehicle = scenario.getVehicles().getTransitVehicles().get( vehicleId ) ;
if ( vehicle!=null ) {  //it's a transit vehicle, it will not be in the "normal" vehicles container
  ... 
```

You could also put a minimal working example, including some small version of input files, into a public repo at github and I could (try to) have a look
