### ISSUE TITLE
DrtRoute issues

### ISSUE THREAD

**Issue by MAlbertini95** [matsim-org/matsim-code-examples#263]
Hello everybody,
I'm trying to run a Drt scenario, but I get this kind of error. I don't know where to start for solving it, since the code script and the config fil seems ok. Can anybody help? thanks for attention, best regards. 

> 2019-12-29 21:37:03,999 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.10 died with exception. Will stop after all threads finished.
java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.contrib.drt.routing.DrtRoute
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.createDrtRoute(DrtMainLegRouter.java:111)
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.calcRoute(DrtMainLegRouter.java:94)
	at org.matsim.contrib.dvrp.router.DvrpRoutingModule.calcRoute(DvrpRoutingModule.java:114)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:173)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:95)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Unknown Source)
2019-12-29 21:37:03,999 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.3 died with exception. Will stop after all threads finished.
java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.contrib.drt.routing.DrtRoute
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.createDrtRoute(DrtMainLegRouter.java:111)
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.calcRoute(DrtMainLegRouter.java:94)
	at org.matsim.contrib.dvrp.router.DvrpRoutingModule.calcRoute(DvrpRoutingModule.java:114)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:173)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:95)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Unknown Source)
2019-12-29 21:37:04,031 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.1 died with exception. Will stop after all threads finished.
java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.contrib.drt.routing.DrtRoute
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.createDrtRoute(DrtMainLegRouter.java:111)
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.calcRoute(DrtMainLegRouter.java:94)
	at org.matsim.contrib.dvrp.router.DvrpRoutingModule.calcRoute(DvrpRoutingModule.java:114)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:173)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:95)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Unknown Source)
2019-12-29 21:37:04,031 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.0 died with exception. Will stop after all threads finished.
java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.contrib.drt.routing.DrtRoute
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.createDrtRoute(DrtMainLegRouter.java:111)
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.calcRoute(DrtMainLegRouter.java:94)
	at org.matsim.contrib.dvrp.router.DvrpRoutingModule.calcRoute(DvrpRoutingModule.java:114)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:173)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:95)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Unknown Source)
2019-12-29 21:37:04,031 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.2 died with exception. Will stop after all threads finished.
java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.contrib.drt.routing.DrtRoute
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.createDrtRoute(DrtMainLegRouter.java:111)
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.calcRoute(DrtMainLegRouter.java:94)
	at org.matsim.contrib.dvrp.router.DvrpRoutingModule.calcRoute(DvrpRoutingModule.java:114)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:173)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:95)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Unknown Source)
2019-12-29 21:37:04,046 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.11 died with exception. Will stop after all threads finished.
java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.contrib.drt.routing.DrtRoute
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.createDrtRoute(DrtMainLegRouter.java:111)
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.calcRoute(DrtMainLegRouter.java:94)
	at org.matsim.contrib.dvrp.router.DvrpRoutingModule.calcRoute(DvrpRoutingModule.java:114)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:173)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:95)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Unknown Source)
2019-12-29 21:37:04,062 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.8 died with exception. Will stop after all threads finished.
java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.contrib.drt.routing.DrtRoute
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.createDrtRoute(DrtMainLegRouter.java:111)
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.calcRoute(DrtMainLegRouter.java:94)
	at org.matsim.contrib.dvrp.router.DvrpRoutingModule.calcRoute(DvrpRoutingModule.java:114)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:173)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:95)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Unknown Source)
2019-12-29 21:37:04,062 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.6 died with exception. Will stop after all threads finished.
java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.contrib.drt.routing.DrtRoute
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.createDrtRoute(DrtMainLegRouter.java:111)
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.calcRoute(DrtMainLegRouter.java:94)
	at org.matsim.contrib.dvrp.router.DvrpRoutingModule.calcRoute(DvrpRoutingModule.java:114)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:173)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:95)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Unknown Source)
2019-12-29 21:37:04,078 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.5 died with exception. Will stop after all threads finished.
java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.contrib.drt.routing.DrtRoute
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.createDrtRoute(DrtMainLegRouter.java:111)
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.calcRoute(DrtMainLegRouter.java:94)
	at org.matsim.contrib.dvrp.router.DvrpRoutingModule.calcRoute(DvrpRoutingModule.java:114)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:173)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:95)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Unknown Source)
2019-12-29 21:37:04,093 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.7 died with exception. Will stop after all threads finished.
java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.contrib.drt.routing.DrtRoute
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.createDrtRoute(DrtMainLegRouter.java:111)
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.calcRoute(DrtMainLegRouter.java:94)
	at org.matsim.contrib.dvrp.router.DvrpRoutingModule.calcRoute(DvrpRoutingModule.java:114)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:173)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:95)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Unknown Source)
2019-12-29 21:37:04,109 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.4 died with exception. Will stop after all threads finished.
java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.contrib.drt.routing.DrtRoute
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.createDrtRoute(DrtMainLegRouter.java:111)
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.calcRoute(DrtMainLegRouter.java:94)
	at org.matsim.contrib.dvrp.router.DvrpRoutingModule.calcRoute(DvrpRoutingModule.java:114)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:173)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:95)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Unknown Source)
2019-12-29 21:37:04,109 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.9 died with exception. Will stop after all threads finished.
java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.contrib.drt.routing.DrtRoute
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.createDrtRoute(DrtMainLegRouter.java:111)
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.calcRoute(DrtMainLegRouter.java:94)
	at org.matsim.contrib.dvrp.router.DvrpRoutingModule.calcRoute(DvrpRoutingModule.java:114)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:173)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:95)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Unknown Source)
2019-12-29 21:37:04,109 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
java.lang.RuntimeException: Some threads crashed, thus not all plans may have been handled.
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule.finishReplanning(AbstractMultithreadedModule.java:159)
	at org.matsim.core.replanning.GenericPlanStrategyImpl.finish(GenericPlanStrategyImpl.java:121)
	at org.matsim.core.replanning.GenericStrategyManager.run(GenericStrategyManager.java:222)
	at org.matsim.core.replanning.StrategyManager.run(StrategyManager.java:191)
	at org.matsim.core.replanning.StrategyManager.run(StrategyManager.java:173)
	at org.matsim.core.controler.corelisteners.PlansReplanningImpl.notifyReplanning(PlansReplanningImpl.java:58)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerReplanningEvent(ControlerListenerManagerImpl.java:206)
	at org.matsim.core.controler.AbstractController$3.run(AbstractController.java:140)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:230)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:137)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:113)
	at org.matsim.core.controler.AbstractController.access$100(AbstractController.java:29)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.trento.run.RunTrentoDRTATaxi.main(RunTrentoDRTATaxi.java:98)
Caused by: java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.contrib.drt.routing.DrtRoute
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.createDrtRoute(DrtMainLegRouter.java:111)
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.calcRoute(DrtMainLegRouter.java:94)
	at org.matsim.contrib.dvrp.router.DvrpRoutingModule.calcRoute(DvrpRoutingModule.java:114)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:173)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:95)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Unknown Source)
2019-12-29 21:37:04,109 ERROR MatsimRuntimeModifications:81 ERROR --- This is an unexpected shutdown!
2019-12-29 21:37:04,109 ERROR MatsimRuntimeModifications:84 Shutdown possibly caused by the following Exception:
java.lang.RuntimeException: Some threads crashed, thus not all plans may have been handled.
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule.finishReplanning(AbstractMultithreadedModule.java:159)
	at org.matsim.core.replanning.GenericPlanStrategyImpl.finish(GenericPlanStrategyImpl.java:121)
	at org.matsim.core.replanning.GenericStrategyManager.run(GenericStrategyManager.java:222)
	at org.matsim.core.replanning.StrategyManager.run(StrategyManager.java:191)
	at org.matsim.core.replanning.StrategyManager.run(StrategyManager.java:173)
	at org.matsim.core.controler.corelisteners.PlansReplanningImpl.notifyReplanning(PlansReplanningImpl.java:58)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerReplanningEvent(ControlerListenerManagerImpl.java:206)
	at org.matsim.core.controler.AbstractController$3.run(AbstractController.java:140)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:230)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:137)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:113)
	at org.matsim.core.controler.AbstractController.access$100(AbstractController.java:29)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.trento.run.RunTrentoDRTATaxi.main(RunTrentoDRTATaxi.java:98)
Caused by: java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.contrib.drt.routing.DrtRoute
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.createDrtRoute(DrtMainLegRouter.java:111)
	at org.matsim.contrib.drt.routing.DrtMainLegRouter.calcRoute(DrtMainLegRouter.java:94)
	at org.matsim.contrib.dvrp.router.DvrpRoutingModule.calcRoute(DvrpRoutingModule.java:114)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:173)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:95)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Unknown Source)
2019-12-29 21:37:04,249 ERROR MatsimRuntimeModifications:99 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2019-12-29 21:37:04,249 ERROR MatsimRuntimeModifications:100 ERROR --- results should not be used for further analysis.
2019-12-29 21:37:04,249 ERROR MatsimRuntimeModifications:104 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.

**Comment by michalmac** [comment]
1. make sure a DrtRouteFactory is registered for DrtRoutes, e.g. https://github.com/matsim-org/matsim/blob/6f240e5e721e3b65bf8c69273161e81f2a2033db/contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtControlerCreator.java#L46

2. if the input file with plans contains drt legs with routes, make sure the type of these routes is set to "drt"

**Comment by MAlbertini95** [comment]
Ok, thank you for response, so I cheked: 

1. DrtRouteFactory seem registered, the DrtControlerCreator is the same, from the dependency.
2. The plans do not contain drt legs, as I'm introducing as a new mode.

So I'll attach here the main code, maybe can help finding the error:

> 
import org.matsim.api.core.v01.Scenario;
import org.matsim.api.core.v01.TransportMode;
import org.matsim.contrib.av.robotaxi.fares.drt.DrtFareConfigGroup;
import org.matsim.contrib.av.robotaxi.fares.drt.DrtFareModule;
import org.matsim.contrib.av.robotaxi.fares.taxi.TaxiFareModule;
import org.matsim.contrib.drt.run.DrtConfigGroup;
import org.matsim.contrib.drt.run.DrtModeModule;
import org.matsim.contrib.drt.run.MultiModeDrtConfigGroup;
import org.matsim.contrib.drt.run.MultiModeDrtModule;
import org.matsim.contrib.dvrp.run.DvrpConfigGroup;
import org.matsim.contrib.dvrp.run.DvrpModule;
import org.matsim.contrib.dvrp.run.DvrpQSimComponents;
import org.matsim.contrib.roadpricing.RoadPricingConfigGroup;
import org.matsim.contrib.roadpricing.RoadPricingModule;
import org.matsim.contrib.taxi.run.TaxiConfigGroup;
import org.matsim.core.config.Config;
import org.matsim.core.config.ConfigUtils;
import org.matsim.core.controler.AbstractModule;
import org.matsim.core.controler.Controler;
import org.matsim.core.controler.OutputDirectoryHierarchy;
import org.matsim.core.gbl.Gbl;
import org.matsim.core.scenario.ScenarioUtils;
import ch.sbb.matsim.config.SwissRailRaptorConfigGroup;
import ch.sbb.matsim.routing.pt.raptor.SwissRailRaptorModule;

public class RunTrentoDRTATaxi{
	public static void main(String[] args) {
		if ( args.length==0 ) {
			args = new String [] { "scenarios/AT_drt introduction/AT_DRTConfig.xml" } ;
		} else {
			Gbl.assertIf( args[0] != null && !args[0].equals( "" ) );
		}

		Config config = ConfigUtils.loadConfig( args, new DvrpConfigGroup(),new MultiModeDrtConfigGroup(),
				new DrtFareConfigGroup(), new RoadPricingConfigGroup(), new SwissRailRaptorConfigGroup() ) ;
		
		config.controler().setOverwriteFileSetting( OutputDirectoryHierarchy.OverwriteFileSetting.deleteDirectoryIfExists );
		config.checkConsistency();

		String mode = DrtConfigGroup.getSingleModeDrtConfig(config).getMode();
		
		Scenario scenario = ScenarioUtils.loadScenario(config) ;

		Controler controler = new Controler( scenario ) ;
		
		controler.addOverridingModule( new SwissRailRaptorModule() );
		controler.addOverridingModule( new DrtFareModule() );
		controler.addOverridingModule( new DvrpModule() );
        controler.addOverridingModule( new MultiModeDrtModule() );
		controler.addOverridingModule( new RoadPricingModule() ); 
		controler.configureQSimComponents(DvrpQSimComponents.activateModes(mode));
		
		controler.addOverridingModule( new AbstractModule() {
			@Override
			public void install() {
				addTravelTimeBinding( TransportMode.ride ).to( networkTravelTime() );
				addTravelDisutilityFactoryBinding( TransportMode.ride ).to( carTravelDisutilityFactoryKey() );
			}
		} ); 
          		
		controler.run();
	}
	
}

**Comment by michalmac** [comment]
Try this:
```
Scenario scenario = DrtControlerCreator.createScenarioWithDrtRouteFactory(config);
ScenarioUtils.loadScenario(scenario);
```
instead of
```
Scenario scenario = ScenarioUtils.loadScenario(config);
```

**Comment by MAlbertini95** [comment]
Perfect! Thank you! Worked.
Just to better understand, it is advisable to make something similar also in a taxi scenario? ( working by now, still have some minor problems on mode share stats as I said in another issue )

**Comment by michalmac** [comment]
A few days ago, I added distance and travel time calculation for taxi trips. Please check if that solves the issues you had.

**Comment by MAlbertini95** [comment]
Seems like a more general problem, also bike trips are not recognized. But thank you again with the Drt Issue

**Comment by michalmac** [comment]
Just curious: what stats do you mean?

**Comment by MAlbertini95** [comment]
I have an output population with the following modal share ( car 40%, bike 22% walk 8% pt 20% ride 10% ). So when I try to run with this population, I get errors telling me there are not registered access/egress walks ( which were just ignored in MATSim 11.0 ). So I can only define them to make it run, but these access/egress are now analyzed in the modal share even if I set different "_analyzedModes_".. But the most strange thing is that at iteration 0, modal stats are something like ( walk %8 car 20% pt 20% ride 0% bike 0% ) which is clearly wrong. Leg histograms are instead correct ( there's people using bike and ride ). So I cannot analyze properly the introduction of drt/taxi fleet.

**Comment by kainagel** [comment]
Hello, not sure if this still is an issue.  We have always recommended to write your own mode analysis, based on the events output.  One reason is that the definition of modes varies from country to country; in Germany, for example, a trip that is 100km by car followed by 10km by train is counted as a train trip. -- One issue complicating this is that the "mode of a trip from a transport planning perspective" is not the same as the "mode of a trip from a computing/software perspective" (the infamous "pure transit_walk" of MATSim).  We have recently introduced "routingMode", which denotes the mode from the computing/software perspective.  Meaning that we now can finally provide plugins plus reasonable defaults for the "mode of a trip from a transport planning perspective".  So I hope that in the near future we will provide plausible analysis for intermodal trips.  But we ain't there yet, I know.   For the time being ... see my second sentence.
