### ISSUE TITLE
Matsim running error - java main class.

### ISSUE THREAD

**Issue by prvnpandey** [matsim-org/matsim-code-examples#267]
please help me to find the error i am not able to recognize where is the problem thanks and regards.
i am running scenario from java class.

2020-01-13 00:41:48,845  INFO Gbl:63 JVM: 13.0.1; Oracle Corporation; mixed mode, sharing; 64-bit
2020-01-13 00:41:48,846  INFO Gbl:67 OS: Windows 10; 10.0; amd64
2020-01-13 00:41:48,846  INFO Gbl:70 CPU cores: 8
2020-01-13 00:41:48,847  INFO Gbl:71 max. Memory: 2020.0MB (2118123520B)
2020-01-13 00:41:48,848  INFO Gbl:109 MATSim-Build: rfb60e5ba361f2e5555974eafef84eafcc3dcc96d (2019-12-02 03:21:25)
2020-01-13 00:41:48,852  INFO ControlerListenerManagerImpl:107 calling notifyStartup on org.matsim.guice.DependencyGraphControlerListener
2020-01-13 00:41:48,857  INFO MemoryObserver:41 used RAM: 106 MB  free: 62 MB  total: 169 MB
2020-01-13 00:41:48,990  INFO ControlerListenerManagerImpl:107 calling notifyStartup on org.matsim.counts.CountsControlerListener
2020-01-13 00:41:48,991  INFO ControlerListenerManagerImpl:107 calling notifyStartup on org.matsim.analysis.ModeStatsControlerListener
2020-01-13 00:41:49,113  INFO PreProcessDijkstra:118 nodes in dead ends: 1270 (total nodes: 23262). Done in 119 ms
2020-01-13 00:41:49,114  WARN PreProcessEuclidean:59 There are links with stored length smaller than their Euclidean distance in this network. Thus, A* cannot guarantee to calculate the least-cost paths between two nodes.
2020-01-13 00:41:49,137  INFO PreProcessLandmarks:112 Putting landmarks on network...
2020-01-13 00:41:49,155  INFO LandmarkerPieSlices:96 Filling sectors...
2020-01-13 00:41:49,316  INFO LandmarkerPieSlices:107 Refining landmarks...
2020-01-13 00:41:49,318  INFO LandmarkerPieSlices:109 done
2020-01-13 00:41:49,318  INFO PreProcessLandmarks:115 done in 181 ms
2020-01-13 00:41:49,319  INFO PreProcessLandmarks:117 Initializing landmarks data
2020-01-13 00:41:49,339  INFO PreProcessLandmarks:129 Calculating distance from each node to each of the 16 landmarks using 2 threads...
2020-01-13 00:41:49,342  INFO PreProcessLandmarks:139 wait for landmarks Calculator to finish...
2020-01-13 00:41:49,885  INFO PreProcessLandmarks:161 done in 546 ms
2020-01-13 00:41:49,890  INFO NetworkImpl:166  node # 1
2020-01-13 00:41:49,890  INFO NetworkImpl:166  node # 4
2020-01-13 00:41:49,890  INFO NetworkImpl:166  node # 16
2020-01-13 00:41:49,891  INFO NetworkImpl:166  node # 64
2020-01-13 00:41:49,891  INFO NetworkImpl:166  node # 256
2020-01-13 00:41:49,892  INFO NetworkImpl:166  node # 1024
2020-01-13 00:41:49,894  INFO NetworkImpl:166  node # 4096
2020-01-13 00:41:49,901  INFO NetworkImpl:166  node # 16384
2020-01-13 00:41:49,905  INFO NetworkImpl:162  link # 1
2020-01-13 00:41:49,905  INFO NetworkImpl:162  link # 4
2020-01-13 00:41:49,906  INFO NetworkImpl:162  link # 16
2020-01-13 00:41:49,906  INFO NetworkImpl:162  link # 64
2020-01-13 00:41:49,908  INFO NetworkImpl:162  link # 256
2020-01-13 00:41:49,911  INFO NetworkImpl:162  link # 1024
2020-01-13 00:41:49,920  INFO NetworkImpl:162  link # 4096
2020-01-13 00:41:49,972  INFO NetworkImpl:162  link # 16384
2020-01-13 00:41:50,049 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.NullPointerException
  at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:66) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.router.TripRouterModule)
  while locating org.matsim.core.router.RoutingModule annotated with @com.google.inject.name.Named(value=car)
  while locating org.matsim.core.router.RoutingModule annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=92, type=MAPBINDER, keyType=java.lang.String)
  at org.matsim.core.router.TripRouter.<init>(TripRouter.java:109)
  while locating org.matsim.core.router.TripRouter

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at org.matsim.analysis.ModeStatsControlerListener.notifyStartup(ModeStatsControlerListener.java:113)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerStartupEvent(ControlerListenerManagerImpl.java:108)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:77)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.test_scenerio.RunMatsimwithLogs.main(RunMatsimwithLogs.java:37)
Caused by: java.lang.NullPointerException
	at org.matsim.core.router.costcalculators.RandomizingTimeDistanceTravelDisutilityFactory.logWarningsIfNecessary(RandomizingTimeDistanceTravelDisutilityFactory.java:81)
	at org.matsim.core.router.costcalculators.RandomizingTimeDistanceTravelDisutilityFactory.createTravelDisutility(RandomizingTimeDistanceTravelDisutilityFactory.java:49)
	at org.matsim.core.router.NetworkRoutingProvider.get(NetworkRoutingProvider.java:116)
	at org.matsim.core.router.NetworkRoutingProvider.get(NetworkRoutingProvider.java:42)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:104)
	at com.google.inject.multibindings.MapBinder$RealMapBinder$ValueProvider.get(MapBinder.java:821)
	at org.matsim.core.router.TripRouter.<init>(TripRouter.java:113)
	at org.matsim.core.router.TripRouter$$FastClassByGuice$$40b051f1.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 9 more
2020-01-13 00:41:50,053  INFO MatsimRuntimeModifications:79 S H U T D O W N   ---   start shutdown.
2020-01-13 00:41:50,053 ERROR MatsimRuntimeModifications:81 ERROR --- This is an unexpected shutdown!
2020-01-13 00:41:50,053 ERROR MatsimRuntimeModifications:84 Shutdown possibly caused by the following Exception:
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.NullPointerException
  at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:66) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.router.TripRouterModule)
  while locating org.matsim.core.router.RoutingModule annotated with @com.google.inject.name.Named(value=car)
  while locating org.matsim.core.router.RoutingModule annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=92, type=MAPBINDER, keyType=java.lang.String)
  at org.matsim.core.router.TripRouter.<init>(TripRouter.java:109)
  while locating org.matsim.core.router.TripRouter

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at org.matsim.analysis.ModeStatsControlerListener.notifyStartup(ModeStatsControlerListener.java:113)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerStartupEvent(ControlerListenerManagerImpl.java:108)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:77)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.test_scenerio.RunMatsimwithLogs.main(RunMatsimwithLogs.java:37)
Caused by: java.lang.NullPointerException
	at org.matsim.core.router.costcalculators.RandomizingTimeDistanceTravelDisutilityFactory.logWarningsIfNecessary(RandomizingTimeDistanceTravelDisutilityFactory.java:81)
	at org.matsim.core.router.costcalculators.RandomizingTimeDistanceTravelDisutilityFactory.createTravelDisutility(RandomizingTimeDistanceTravelDisutilityFactory.java:49)
	at org.matsim.core.router.NetworkRoutingProvider.get(NetworkRoutingProvider.java:116)
	at org.matsim.core.router.NetworkRoutingProvider.get(NetworkRoutingProvider.java:42)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:104)
	at com.google.inject.multibindings.MapBinder$RealMapBinder$ValueProvider.get(MapBinder.java:821)
	at org.matsim.core.router.TripRouter.<init>(TripRouter.java:113)
	at org.matsim.core.router.TripRouter$$FastClassByGuice$$40b051f1.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 9 more
2020-01-13 00:41:50,054  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.EventsHandlingImpl
2020-01-13 00:41:50,054  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.DumpDataAtEndImpl
2020-01-13 00:41:50,054  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ModeStatsControlerListener
2020-01-13 00:41:50,055  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ScoreStatsControlerListener
2020-01-13 00:41:50,055  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.TravelDistanceStatsControlerListener
2020-01-13 00:41:50,840  INFO ControlerListenerManagerImpl:129 all ControlerShutdownListeners called.
2020-01-13 00:41:50,840 ERROR MatsimRuntimeModifications:99 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2020-01-13 00:41:50,840  INFO MatsimRuntimeModifications:102 S H U T D O W N   ---   shutdown completed.
2020-01-13 00:41:50,840 ERROR MatsimRuntimeModifications:100 ERROR --- results should not be used for further analysis.
2020-01-13 00:41:50,840 ERROR MatsimRuntimeModifications:104 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.NullPointerException
  at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:66) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.router.TripRouterModule)
  while locating org.matsim.core.router.RoutingModule annotated with @com.google.inject.name.Named(value=car)
  while locating org.matsim.core.router.RoutingModule annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=92, type=MAPBINDER, keyType=java.lang.String)
  at org.matsim.core.router.TripRouter.<init>(TripRouter.java:109)
  while locating org.matsim.core.router.TripRouter

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at org.matsim.analysis.ModeStatsControlerListener.notifyStartup(ModeStatsControlerListener.java:113)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerStartupEvent(ControlerListenerManagerImpl.java:108)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:77)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.test_scenerio.RunMatsimwithLogs.main(RunMatsimwithLogs.java:37)
Caused by: java.lang.NullPointerException
	at org.matsim.core.router.costcalculators.RandomizingTimeDistanceTravelDisutilityFactory.logWarningsIfNecessary(RandomizingTimeDistanceTravelDisutilityFactory.java:81)
	at org.matsim.core.router.costcalculators.RandomizingTimeDistanceTravelDisutilityFactory.createTravelDisutility(RandomizingTimeDistanceTravelDisutilityFactory.java:49)
	at org.matsim.core.router.NetworkRoutingProvider.get(NetworkRoutingProvider.java:116)
	at org.matsim.core.router.NetworkRoutingProvider.get(NetworkRoutingProvider.java:42)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:104)
	at com.google.inject.multibindings.MapBinder$RealMapBinder$ValueProvider.get(MapBinder.java:821)
	at org.matsim.core.router.TripRouter.<init>(TripRouter.java:113)
	at org.matsim.core.router.TripRouter$$FastClassByGuice$$40b051f1.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 9 more

**Comment by prvnpandey** [comment]
I am very new to matsim and i am trying to learn for building project, right now i was trying to run from java class and build my controller to run the code and the error i am getting i am not able to understand please help to understand why it persisted @kainagel @JWJoubert

**Comment by JWJoubert** [comment]
I suggest you start with a basic (working) example @politogroup20... it is not clear WHAT you are running: config, network, population, etc. From the log message, it just seems that you do not have a router configured (or "bound" to the car mode). I suggest you first work through the tutorial. If you are not comfortable coding/scripting, you will be limited (or that's what I would suggest) to running MATSim using the GUI (that too is explained) in the tutorial.

**Comment by prvnpandey** [comment]
thank you very much, i have gone through the tutorial and now my simulation is running.
i have created population file in which i have not assigned any route but simulation is running and its showing the error also which is:
  ERROR BasicPlanAgentImpl:151 The agent 7264273 has no route in its leg.  Setting agent state to ABORT.
for every agent i am not understanding if i assign any route in starting what is its purpose, because according to my (x,y) coordinates its going to find the nearest link so exactly why its important to assign the route in population file please clear my doubt thank you very much  @kainagel @JWJoubert
