### ISSUE TITLE
Try to use avparking but failed

### ISSUE THREAD

**Issue by mirony0** [matsim-org/matsim-code-examples#273]
Hi. I tried to use the avparking module from https://github.com/matsim-org/matsim/tree/610b1b65cd8f1551668a7bf4d8b66cf05c520e89/contribs/vsp/src/main/java/playground/vsp/avparking but it comes out with error that i can't figure out the reason. Is that means this module is not applicable any more since i notice that some of these codes can not be used like the picture.  Thanks a lot if you could give me some suggestions!
<img width="759" alt="微信图片_20200123124030" src="https://user-images.githubusercontent.com/59462570/72957179-9e3bb000-3ddd-11ea-9708-ac1f6ff596d1.png">

Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Explicit bindings are required and org.matsim.core.router.util.TravelTime annotated with @com.google.inject.name.Named(value=dvrp_estimated) is not explicitly bound.
  while locating org.matsim.core.router.util.TravelTime annotated with @com.google.inject.name.Named(value=dvrp_estimated)
    for field at org.matsim.contrib.dvrp.router.DvrpModeRoutingModule$DefaultMainLegRouterProvider.travelTime(DvrpModeRoutingModule.java:63)
  at org.matsim.contrib.dvrp.router.DvrpModeRoutingModule.install(DvrpModeRoutingModule.java:51) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.contrib.taxi.run.MultiModeTaxiModule -> org.matsim.contrib.taxi.run.TaxiModeModule -> org.matsim.contrib.dvrp.router.DvrpModeRoutingModule)

2) Explicit bindings are required and org.matsim.core.router.util.TravelTime annotated with @com.google.inject.name.Named(value=dvrp_estimated) is not explicitly bound.
  while locating org.matsim.core.router.util.TravelTime annotated with @com.google.inject.name.Named(value=dvrp_estimated)
    for field at org.matsim.contrib.dvrp.router.DvrpModeRoutingModule$GenericRouteCreatorProvider.travelTime(DvrpModeRoutingModule.java:82)
  at org.matsim.contrib.dvrp.run.AbstractDvrpModeModule.bindModal(AbstractDvrpModeModule.java:56) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.contrib.taxi.run.MultiModeTaxiModule -> org.matsim.contrib.taxi.run.TaxiModeModule -> org.matsim.contrib.dvrp.router.DvrpModeRoutingModule)

3) No implementation for org.matsim.core.router.RoutingModule annotated with @com.google.inject.name.Named(value=car) was bound.
  at playground.vsp.avparking.DvrpParkingModule.install(DvrpParkingModule.java:106) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> playground.vsp.avparking.ParkingTaxiModule -> playground.vsp.avparking.DvrpParkingModule)

4) An exception was caught and reported. Message: org.matsim.contrib.dvrp.router.DvrpModeRoutingModule cannot be cast to org.matsim.core.router.RoutingModule
  at playground.vsp.avparking.ParkingTaxiModule.install(ParkingTaxiModule.java:45) (via modules: playground.vsp.avparking.ParkingTaxiModule -> playground.vsp.avparking.DvrpParkingModule)

5) Explicit bindings are required and org.matsim.contrib.parking.parkingsearch.manager.ParkingSearchManager  .
  while locating org.matsim.contrib.parking.parkingsearch.manager.ParkingSearchManager
    for field at playground.vsp.avparking.PrivateAVFleetGenerator.manager(PrivateAVFleetGenerator.java:51)
  at playground.vsp.avparking.RunAvParking$1.install(RunAvParking.java:83) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> playground.vsp.avparking.RunAvParking$1)
5 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236)
	at org.matsim.core.controler.Injector.createInjector(Injector.java:74)
	at org.matsim.core.controler.Controler.run(Controler.java:245)
	at playground.vsp.avparking.RunAvParking.run(RunAvParking.java:90)
	at playground.vsp.avparking.RunAvParking.main(RunAvParking.java:58)
Caused by: java.lang.ClassCastException: org.matsim.contrib.dvrp.router.DvrpModeRoutingModule cannot be cast to org.matsim.core.router.RoutingModule
	at playground.vsp.avparking.DvrpParkingModule.install(DvrpParkingModule.java:106)
	at org.matsim.core.controler.AbstractModule.configure(AbstractModule.java:118)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at org.matsim.core.controler.AbstractModule.install(AbstractModule.java:129)
	at playground.vsp.avparking.ParkingTaxiModule.install(ParkingTaxiModule.java:45)
	at org.matsim.core.controler.AbstractModule.configure(AbstractModule.java:118)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:198)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at org.matsim.core.controler.AbstractModule$4.install(AbstractModule.java:250)
	at org.matsim.core.controler.AbstractModule.configure(AbstractModule.java:118)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at org.matsim.core.controler.AbstractModule$4.install(AbstractModule.java:250)
	at org.matsim.core.controler.AbstractModule.configure(AbstractModule.java:118)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at org.matsim.core.controler.AbstractModule$4.install(AbstractModule.java:250)
	at org.matsim.core.controler.AbstractModule.configure(AbstractModule.java:118)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:198)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at org.matsim.core.controler.AbstractModule$4.install(AbstractModule.java:250)
	at org.matsim.core.controler.AbstractModule.configure(AbstractModule.java:118)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.util.Modules$CombinedModule.configure(Modules.java:128)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.util.Modules$CombinedModule.configure(Modules.java:128)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	... 6 more

**Comment by michalmac** [comment]
This code was experimental (it is in the playground package) and is not supported any more.

For parking simulation, please have a look at this example: https://github.com/matsim-org/matsim/blob/f1b4c89bd7c8bda893de89247a4cb8f0a1a4f944/contribs/parking/src/main/java/org/matsim/contrib/parking/parkingsearch/RunParkingSearchExample.java#L45

@jfbischoff @kainagel Shall I remove the `playground.vsp.avparking` package?

**Comment by jfbischoff** [comment]
I have no objections against removing it. This has never been an officially supported feature and was well-hidden in the playgrounds :-) 
I think the last one who used it might have been @tschlenther as a blueprint for his own code.

**Comment by mirony0** [comment]
@jfbischoff Hi.Dear sir. 
Sorry to bothering you. But i want to know is if this module runnable in the newest Matsim version 12.0 SNAPSHOT? As i find many code here is not supported like the **dynroutingmodule**, which is deleted, and others. I want to use this module so i try to edit some of these codes but with errors like above. Any good suggestions for making it workable? or this module is hard to edit in the nowadays matsim environment so it is not suggested to use? THANKS!

**Comment by jfbischoff** [comment]
You can try to make it runnable, but there is no one actively supporting it (it was an experimental work hidden somewhere deep in the playgrounds). 
It might be easier to revert to the MATSim 11 release state for both simulations. 
Miracously it has now appeared in the contribs, though I never intended it to be there.

**Comment by michalmac** [comment]
The VSP playground was moved to matsim contribs a few months ago (so it will not be available in matsim 11). Actually, the AV parking stuff was probably already non-functional at the time of migration.

The optimiser package is OK, but the infrastructure side (coupling things together) was already obsolete (there have been lots of changes in recent years), so quite recently, I have removed the infrastructure code. Now I am going to remove the optimiser package as well to avoid any further confusion.

==

The only way to run it is to checkout some old revisions of both matsim and vsp-playgrounds (somewhere around 2017).

**Comment by mirony0** [comment]
@jfbischoff  Hi. If i use the matsim 11.0. it also comes with the error listed below. I can't figure out the reason for such NullPointerException... Any good suggstions?
Thanks a lot.

Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.NullPointerException
  at org.matsim.contrib.dvrp.run.AbstractDvrpModeModule.bindModal(AbstractDvrpModeModule.java:50) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.contrib.taxi.run.TaxiModule -> org.matsim.contrib.taxi.run.TaxiModeModule -> org.matsim.contrib.dvrp.fleet.FleetModule)
  at org.matsim.contrib.dvrp.run.AbstractDvrpModeModule.bindModal(AbstractDvrpModeModule.java:50) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.contrib.taxi.run.TaxiModule -> org.matsim.contrib.taxi.run.TaxiModeModule -> org.matsim.contrib.dvrp.fleet.FleetModule)
  while locating org.matsim.contrib.dvrp.fleet.FleetSpecification annotated with @org.matsim.contrib.dvrp.run.DvrpMode(value=taxi)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236)
	at org.matsim.core.controler.Injector.createInjector(Injector.java:74)
	at org.matsim.core.controler.Controler.run(Controler.java:227)
	at playground.vsp.avparking.RunAvParking.run(RunAvParking.java:111)
	at playground.vsp.avparking.RunAvParking.main(RunAvParking.java:79)
Caused by: java.lang.NullPointerException
	at org.matsim.core.config.ConfigGroup.getInputFileURL(ConfigGroup.java:244)
	at org.matsim.contrib.dvrp.fleet.FleetModule.lambda$install$0(FleetModule.java:55)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	... 7 more

**Comment by mirony0** [comment]
[berlin-v5.4-1pct.logfileWarningsErrors.log](https://github.com/matsim-org/matsim-code-examples/files/4113414/berlin-v5.4-1pct.logfileWarningsErrors.log)
@jfbischoff  Dear sir
Hi.I try to run this in Matsim 11.0. And Here is my warning log. The main problem here is the 
**Explicit bindings are required and java.lang.String is not explicitly bound.**
I have no idea of such problem. Is it because the code itself is not complete or something else? If you have any good suggestions to solve that. Please tell me about that. Thank you so much!

Or if you have any test case for the avparking module? If such example could be used by other person. I am wondering if you could send this to me so i can see what could be the possible reason for these errors. Anyway, Thanks.
