### ISSUE TITLE
pt simulation error

### ISSUE THREAD

**Issue by jiao1997** [matsim-org/matsim-code-examples#291]
Dear all:
         There are some problems when I am trying to use pt simulation. The errors are:
ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.1 died with exception while handling events.
org.matsim.core.router.TripRouter$UnknownModeException: unregistered main mode |car,pt|: does not pertain to [egress_walk, pt, car, transit_walk, access_walk, ride, walk, bike, undefined]
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:235)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:90)
	at org.matsim.core.population.algorithms.PersonPrepareForSim.run(PersonPrepareForSim.java:157)
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils$PersonAlgoThread.run(ParallelPersonAlgorithmUtils.java:145)
	at java.lang.Thread.run(Thread.java:748)

    By the way, I have set the leg mode="car,pt" in the plans.xml , is it correct? Here is my config file and plans file. Hope to get your sincere help.
[configPT.txt](https://github.com/matsim-org/matsim-code-examples/files/4208514/configPT.txt)
[plans500.txt](https://github.com/matsim-org/matsim-code-examples/files/4208515/plans500.txt)

**Comment by jfbischoff** [comment]
You must set the leg mode to either car or pt in the plans file. If you want agents to change their mode in between iterations, use SubtourModechoice as a replanning strategy.

**Comment by jiao1997** [comment]
> You must set the leg mode to either car or pt in the plans file. If you want agents to change their mode in between iterations, use SubtourModechoice as a replanning strategy.

Thanks a lot for your reply. I have set the leg mode to car and use SubtourModechoice. But I have found another error which is:  
WARN Dijkstra:307 No route was found from node -634723 to node -149726. Some possible reasons:
  WARN Dijkstra:308   * Network is not connected.  Run NetworkCleaner().
  WARN Dijkstra:309   * Network for considered mode does not even exist.  Modes need to be entered for each link in network.xml.
 * Network for considered mode is not connected to starting or ending point of route.  Setting insertingAccessEgressWalk to true may help.
 This will now return null, but it may fail later with a null pointer exception.
ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.0 died with exception while handling events.
java.lang.RuntimeException: No route found from node -634723 to node -149726 by mode car.
	at org.matsim.core.router.NetworkRoutingModule.calcRoute(NetworkRoutingModule.java:97)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:222)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:90)
	at org.matsim.core.population.algorithms.PersonPrepareForSim.run(PersonPrepareForSim.java:157)
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils$PersonAlgoThread.run(ParallelPersonAlgorithmUtils.java:145)
	at java.lang.Thread.run(Thread.java:748)

 My network is connected, and I  wonder  if you know how to set insertingAccessEgressWalk. 
 Hope to get your early reply.

**Comment by whizkid-25** [comment]
@jiao1997 

Hi, are you using cadyts to calibrate your network?

**Comment by jiao1997** [comment]
> @jiao1997
> 
> Hi, are you using cadyts to calibrate your network?

Hi , I haven't do that.
