### ISSUE TITLE
Signal System Error

### ISSUE THREAD

**Issue by ahmad-fz89** [matsim-org/matsim-code-examples#292]
Hi all,

I am currently trying to run Signal System example that can be found here: https://github.com/matsim-org/matsim/tree/master/contribs/signals/examples/tutorial/singleCrossingScenario

The problem is I am using MATSim Graphical User Interface (GUI) to run the Config file, but I am getting this error:

2020-02-18 18:34:36,324 ERROR MatsimRuntimeModifications:54 Getting uncaught Exception in Thread main
java.lang.RuntimeException: Unmaterialized config group: signalsystems
	at org.matsim.core.config.consistency.UnmaterializedConfigGroupChecker.checkConsistency(UnmaterializedConfigGroupChecker.java:11)
	at org.matsim.core.config.Config.checkConsistency(Config.java:227)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:65)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2020-02-18 18:34:36,325 ERROR MatsimRuntimeModifications:60 ERROR --- This is an unexpected shutdown!
2020-02-18 18:34:36,325 ERROR MatsimRuntimeModifications:63 Shutdown possibly caused by the following Exception:
java.lang.RuntimeException: Unmaterialized config group: signalsystems
	at org.matsim.core.config.consistency.UnmaterializedConfigGroupChecker.checkConsistency(UnmaterializedConfigGroupChecker.java:11)
	at org.matsim.core.config.Config.checkConsistency(Config.java:227)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:65)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2020-02-18 18:34:36,337 ERROR MatsimRuntimeModifications:78 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2020-02-18 18:34:36,337 ERROR MatsimRuntimeModifications:79 ERROR --- results should not be used for further analysis.
2020-02-18 18:34:36,337 ERROR MatsimRuntimeModifications:83 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
Exception in thread "main" java.lang.RuntimeException: Unmaterialized config group: signalsystems
	at org.matsim.core.config.consistency.UnmaterializedConfigGroupChecker.checkConsistency(UnmaterializedConfigGroupChecker.java:11)
	at org.matsim.core.config.Config.checkConsistency(Config.java:227)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:65)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)

The simulation did not run properly. Error/Exit code: 1

I have reviewed previous questions posted, such as https://github.com/matsim-org/matsim-code-examples/wiki/faq-89260053. but none of them solved my problem. It looks like available answers can fix the Java source files instead of .XML files.

The only thing is if I run the fixed time signal example through the Java source codes (https://github.com/matsim-org/matsim/tree/master/contribs/signals/src/main/java/org/matsim/codeexamples/fixedTimeSignals), it would work. 

I don't know what's wrong with the .XML files that they cannot be run through MATSim GUI. 

Thanks in advance,

Ahmad

**Comment by tthunig** [comment]
Dear Ahmad, 

the signals example was not meant to be run by a GUI. As you see for example in the other question that you referred to (and also in the code in [RunSignalSystemsExample.java](https://github.com/matsim-org/matsim-libs/blob/master/contribs/signals/src/main/java/org/matsim/codeexamples/fixedTimeSignals/RunSignalSystemsExample.java)), some modifications to the scenario and controler are necessary to be able to simulate traffic signals in MATSim. The standard MATSim GUI does not account for this modifications. 

I just added a fixed-time signal specific GUI for you in the [code examples directory for fixed-time signals](https://github.com/matsim-org/matsim/tree/master/contribs/signals/src/main/java/org/matsim/codeexamples/fixedTimeSignals).

Let me know if you have further questions or problems.

Cheers
Theresa
