### ISSUE TITLE
Getting NullPointerException while Replanning

### ISSUE THREAD

**Issue by paud0** [matsim-org/matsim-code-examples#297]
Hello, 

I am simulating a quite big scenario and run into a problem while replanning after the 12th iteration. 

The error in the log is:

`java.lang.NullPointerException
	at org.matsim.pt.router.TransitLeastCostPathTree.relaxNode(TransitLeastCostPathTree.java:422)
	at org.matsim.pt.router.TransitLeastCostPathTree.expandNodeData(TransitLeastCostPathTree.java:183)
	at org.matsim.pt.router.TransitLeastCostPathTree.<init>(TransitLeastCostPathTree.java:140)
	at org.matsim.pt.router.TransitRouterImpl.calcRoute(TransitRouterImpl.java:138)
	at org.matsim.core.router.TransitRouterWrapper.calcRoute(TransitRouterWrapper.java:79)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:196)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:90)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Thread.java:748)
` 

I am only using MATSim standart replanning modules (BestScore, ReRoute).

The only solution for this problem I could find is an uncleaned network with nodes without outgoing nodes, but this is not the case for me. 

The only thing I could imagine is that this happens due to problems with network modes during replanning. Could the problem occur due to links that only allow pt and no cars, so my car agents are manoeuvering themselves into "car" dead ends while replanning, which are not as easy to find as "standart" dead ends.

Thanks for your help and kind regards
Paul Dowideit

**Comment by paud0** [comment]
I tried to reproduce and got a similiar but different error:

`Caused by: java.lang.IncompatibleClassChangeError
	at org.matsim.pt.router.TransitLeastCostPathTree.relaxNodeLogic(TransitLeastCostPathTree.java:433)
	at org.matsim.pt.router.TransitLeastCostPathTree.relaxNode(TransitLeastCostPathTree.java:423)
	at org.matsim.pt.router.TransitLeastCostPathTree.expandNodeData(TransitLeastCostPathTree.java:183)
	at org.matsim.pt.router.TransitLeastCostPathTree.<init>(TransitLeastCostPathTree.java:140)
	at org.matsim.pt.router.TransitRouterImpl.calcRoute(TransitRouterImpl.java:138)
	at org.matsim.core.router.TransitRouterWrapper.calcRoute(TransitRouterWrapper.java:79)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:196)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:90)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Thread.java:748)`

Any ideas?

**Comment by kainagel** [comment]
No idea, sorry.  `IncompatibleClassChangeError` sounds like incompatible binary versions.  It should not be possible to get this when compiling with maven; maybe re-try with "mvn clean ...".  Also, the null pointer exception should not be possible when looking at the code; when going up a bit in the calling hierarchy, there is no normal execution path that allows one of the objects in relaxNode(...) to be null.  (Or I am overlooking it.). Which also rather points to a consistency problem with binaries.

I don't know how you are running, and I myself don't have much experience with running on large machines.  We usually recommend "mvn package" to obtain a "jar-file-with-dependencies" and just use that one.

**Comment by paud0** [comment]
I am using a shaded maven jar to combine my code with the matsim code (from azure artifact) in one single jar file. 
That should basically be a jar-file-with-dependencies.
I cleaned and repackaged and am trying again.

The weird thing is that I did no code changes since this problem is occuring. I only changed my plans file and started the simulation with my usual jar file. But since I am able to run some iterations and do only use rerouting strategies I am really confused right now about where the problem might come from...

**Comment by kainagel** [comment]
Hm.

The other thing I should say is that we are not really using the "standard" public transport router any more.  We have switched in most cases to the "SwissRailRaptor".  That is not yet included in matsim 11, but it has been in the development version for a couple of months now.  You could use a weekly build to try out and still have some code stability. -- I don't know where there is documentation for the raptor; hopefully someone who knows can chip in.  The calling syntax is something like
```
controller.addOverridingModule( new SwissRailRaptorModule() );
```
There are also config options; not sure if one needs to touch them for a first trial.

I can't say anything about azure artifacts.  Our official deployments go to bintray and to jfrog.  I can't say if there is a chance that it gets corrupted from bintray/jfrog (or from whereever it comes) to azure.  The maven shade plugin certainly also works with the bintray/jfrog versions.

**Comment by paud0** [comment]
I think I found my issue which was most likely caused by bus stops on links with nodes containing not only numbers.

I build the matsim jar files myself and deployed them to azure. 

What are the differences between the standart pt router and the "SwissRailRaptor"?
Is adding the overriding module all I have to do?

**Comment by paud0** [comment]
I will open a seperate issue concerning my SwissRailRaptor questions since this issue is solved. (https://github.com/matsim-org/matsim-code-examples/issues/301)

**Comment by kainagel** [comment]
IDs are backed by Strings, so they should allow characters that go beyond numbers.

They may have problems with "unusual" characters, such as empty spaces.  Could that have been the reason?

Thanks for opening a separate ticket for the SwissRailRaptor.

**Comment by paud0** [comment]
Well if that is the case I have no clue what the problem could have been.

But since my change to the node ids I was not able to reproduce it again...

**Comment by kainagel** [comment]
I would see the theoretical possibility that last time with your jar generation, something went wrong.  As usual, that should not happen, but ...  That would also be an IMO consistent explanation of the problems you saw.  --  Let's hope it does not come back.
