### ISSUE TITLE
Travel mode definition consistency in config.xml

### ISSUE THREAD

**Issue by antboy** [matsim-org/matsim-code-examples#317]
I have a scenario involving many travel modes, most of which are not transit mode, but of which 2 are, and I am having difficulty running Matsim without crashing, due to some config being present when it should not be, or absent when it should not be, or inconsistent somehow.

The difficulty seems to be having:
`<module name="transit" >    <param name="transitModes" value="railway,subway" /> ...`

and where else those modes should bet set or not, and their associated data.
e.g. for qsim, planscalcroute, travelTimeCalculator, planCalcScore/modeParams, changeMode/modes .
There are a lot of permutations!

Help would be much appreciated.

Regards,
John

___________________

I mainly have two different sets of errors:
Either:
___________________
2020-04-07 16:48:55,635 WARN  [main] org.matsim.core.config.consistency.ConfigConsistencyCheckerImpl:61 AnalyzedModes in travelTimeCalculator config is not superset of network routing modes.  Will fail later except when defined by other means.
2020-04-07 16:48:57,841 ERROR [main] org.tsc.demand.MatSimDeMAND:113 com.google.inject.CreationException: Unable to create injector, see the following errors:

1) A binding to org.matsim.core.router.RoutingModule annotated with @com.google.inject.name.Named(value=railway) was already configured at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:66) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.router.TripRouterModule).
  at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:71) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.router.TripRouterModule)

2) A binding to org.matsim.core.router.RoutingModule annotated with @com.google.inject.name.Named(value=subway) was already configured at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:66) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.router.TripRouterModule).
  at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:71) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.router.TripRouterModule)
___________________

Or:
___________________
1) Error injecting constructor, java.lang.NullPointerException
  at org.matsim.pt.router.TransitRouterImplFactory.<init>(TransitRouterImplFactory.java:44)
  at org.matsim.pt.router.TransitRouterImplFactory.class(TransitRouterImplFactory.java:34)
  while locating org.matsim.pt.router.TransitRouterImplFactory
  while locating org.matsim.pt.router.TransitRouter
    for the 1st parameter of org.matsim.core.router.Transit.<init>(Transit.java:20)
  while locating org.matsim.core.router.Transit
  while locating org.matsim.core.router.RoutingModule annotated with @com.google.inject.name.Named(value=subway)
  while locating org.matsim.core.router.RoutingModule annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=116, type=MAPBINDER, keyType=java.lang.String)
  at org.matsim.core.router.TripRouter.<init>(TripRouter.java:108)
  while locating org.matsim.core.router.TripRouter
    for field at org.matsim.core.scoring.ScoringFunctionsForPopulation.tripRouter(ScoringFunctionsForPopulation.java:73)
  at org.matsim.core.scoring.PlansScoringModule.install(PlansScoringModule.java:10) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.corelisteners.ControlerDefaultCoreListenersModule -> org.matsim.core.scoring.PlansScoringModule)
  while locating org.matsim.core.scoring.ScoringFunctionsForPopulation
    for field at org.matsim.core.scoring.PlansScoringImpl.scoringFunctionsForPopulation(PlansScoringImpl.java:47)
  at org.matsim.core.scoring.PlansScoringImpl.class(PlansScoringImpl.java:47)
  while locating org.matsim.core.scoring.PlansScoringImpl
  while locating org.matsim.core.controler.corelisteners.PlansScoring
    for the 10th parameter of org.matsim.core.controler.NewControler.<init>(NewControler.java:64)
  while locating org.matsim.core.controler.NewControler
  at org.matsim.core.controler.NewControlerModule.install(NewControlerModule.java:8) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.NewControlerModule)
  while locating org.matsim.core.controler.ControlerI
___________________

**Comment by mrieser** [comment]
Regarding the first error:

> AnalyzedModes in travelTimeCalculator config is not superset of network routing modes

The modes for travelTimeCalculator are for network-based modes only, essentially for those listed as `mainModes` in the qsim configuration. `railway` should not be one of it, as it is a mode for public transport which uses a router based on the schedule.

**Comment by antboy** [comment]
Thanks Marcel.

I found the following comment about "pt" needing to be present for reasons of backward compatibility, and this seems to have resolved things, at least it now runs to normal termination.

https://github.com/matsim-org/matsim-code-examples/issues/83#issuecomment-463136892
