### ISSUE TITLE
Null Pointer Exception 

### ISSUE THREAD

**Issue by whizkid-25** [matsim-org/matsim-code-examples#322]
I am seeing the following error when I am trying to run the carsharing module 

![Error](https://user-images.githubusercontent.com/60205511/79529758-7d30d700-803b-11ea-9b2e-f9e9b8703354.JPG)

 java.lang.NullPointerException at org.matsim.contrib.carsharing.replanning.CarsharingSubTourPermissableModesCalculator.getPermissibleModes(CarsharingSubTourPermissableModesCalculator.java:54) at org.matsim.core.population.algorithms.ChooseRandomLegModeForSubtour.run(ChooseRandomLegModeForSubtour.java:116) at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
 java.lang.Thread.run(Unknown Source)

I have attached my config file below: 

[config file.txt](https://github.com/matsim-org/matsim-code-examples/files/4490812/config.file.txt)

How can I solve this issue?

**Comment by whizkid-25** [comment]
This problem is only arising when I am using "CarsharingSubtourModeChoiceStrategy" as strategy!

**Comment by whizkid-25** [comment]
@jfbischoff can you tell me how can I solve this ?

**Comment by jfbischoff** [comment]
Sorry, I have no ideas about working with that extension. Perhaps @balacmi could help.

**Comment by whizkid-25** [comment]
@michalmac can you please help me in this regard?
