### ISSUE TITLE
Main transport modes other than car

### ISSUE THREAD

**Issue by J15t98J** [matsim-org/matsim-code-examples#327]
I'm building a model using only pt/walk and getting the following:

2020-04-28 23:59:36,127 ERROR MatsimRuntimeModifications:54 Getting uncaught Exception in Thread main
java.lang.RuntimeException: Object is null; follow stack trace
	at org.matsim.core.gbl.Gbl.assertNotNull(Gbl.java:205)
	at org.matsim.core.controler.PrepareForSimImpl.getMode2VehicleType(PrepareForSimImpl.java:252)
	at org.matsim.core.controler.PrepareForSimImpl.run(PrepareForSimImpl.java:126)
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:106)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:83)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)

Following it back, it seems that [PrepareForSimImpl.java forces mode "car"](https://github.com/matsim-org/matsim-libs/blob/0.10.x/matsim/src/main/java/org/matsim/core/controler/PrepareForSimImpl.java#L79)  on multi-modal networks which then fails as my model has no cars/car links? There's a TODO right above that about adapting that code to allow other modes, dated October 2015, so am I to infer that MATSim simply doesn't support such models at the moment, or am I doing something very wrong?

**Comment by kainagel** [comment]
I think that your observation is correct.  Because this is so deeply ingrained into matsim, I have started to interpret this as the "postal address".  I would say that it should not hurt your model to also have a car network, i.e. some number of links that only have "car" as mode.

You will have to switch access/egress legs on since otherwise the simulation will hick up on persons trying to do "walk" but only being connected to "car" links.

And there is something weird with the "walk" mode; you may have to try around with a "walk2" mode instead.

Let us know how it goes; it _should_ work; but it may not be totally straightforward, sorry.
