### ISSUE TITLE
org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.core.population.routes.NetworkRoute

### ISSUE THREAD

**Issue by emilymorey** [matsim-org/matsim-code-examples#332]
Hello - I'm working on my 4th year research project and I am using MatSim to model people evacuating from a building I have designed. I have successfully created a model for 1 type of agent but I am now trying to create a model using 3 agent types, however I now get an error when I run MatSim. I have looked at the multi-mode example but cannot see where I have gone wrong. The MatSim error log is shown below and I have uploaded my project files as a ZIP. Any suggestions would be greatly appreciated. Thanks Emily

FILES
[my files.zip](https://github.com/matsim-org/matsim-code-examples/files/4605982/my.files.zip)

WARNINGS & ERRORS
`2020-05-10 16:25:32,123  WARN MatsimXmlParser:155 starting to parse xml from url file:/C:/matsim/1%20School%201365%20multi/config.xml ...
2020-05-10 16:25:32,538  WARN PlanCalcScoreConfigGroup$ActivityParams:859 Setting minimalDuration different from zero is discouraged.  It is probably implemented correctly, but there is as of now no indication that it makes the results more realistic.  KN, Sep'08 This message given only once.
2020-05-10 16:25:33,594  WARN MatsimXmlParser:155 starting to parse xml from url file:/C:/matsim/1%20School%201365%20multi/network.xml ...
2020-05-10 16:25:34,129  WARN MatsimXmlParser:155 starting to parse xml from url file:/C:/matsim/1%20School%201365%20multi/plans.xml ...
2020-05-10 16:25:34,507  WARN MatsimXmlParser:155 starting to parse xml from url file:/C:/matsim/1%20School%201365%20multi/vehicles.xml ...
2020-05-10 16:25:35,480  WARN PreProcessEuclidean:59 There are links with stored length smaller than their Euclidean distance in this network. Thus, A* cannot guarantee to calculate the least-cost paths between two nodes.
2020-05-10 16:25:35,501  WARN PreProcessEuclidean:59 There are links with stored length smaller than their Euclidean distance in this network. Thus, A* cannot guarantee to calculate the least-cost paths between two nodes.
2020-05-10 16:25:35,520  WARN PreProcessEuclidean:59 There are links with stored length smaller than their Euclidean distance in this network. Thus, A* cannot guarantee to calculate the least-cost paths between two nodes.
2020-05-10 16:25:35,537  WARN PreProcessEuclidean:59 There are links with stored length smaller than their Euclidean distance in this network. Thus, A* cannot guarantee to calculate the least-cost paths between two nodes.
2020-05-10 16:25:35,627 ERROR MatsimRuntimeModifications:54 Getting uncaught Exception in Thread main
java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.core.population.routes.NetworkRoute
	at org.matsim.core.controler.PrepareForSimImpl.run(PrepareForSimImpl.java:134)
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:106)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:83)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2020-05-10 16:25:35,628 ERROR MatsimRuntimeModifications:60 ERROR --- This is an unexpected shutdown!
2020-05-10 16:25:35,628 ERROR MatsimRuntimeModifications:63 Shutdown possibly caused by the following Exception:
java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.core.population.routes.NetworkRoute
	at org.matsim.core.controler.PrepareForSimImpl.run(PrepareForSimImpl.java:134)
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:106)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:83)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2020-05-10 16:25:35,631 ERROR MatsimRuntimeModifications:78 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2020-05-10 16:25:35,631 ERROR MatsimRuntimeModifications:79 ERROR --- results should not be used for further analysis.
2020-05-10 16:25:35,632 ERROR MatsimRuntimeModifications:83 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
Exception in thread "main" java.lang.ClassCastException: org.matsim.core.population.routes.GenericRouteImpl cannot be cast to org.matsim.core.population.routes.NetworkRoute
	at org.matsim.core.controler.PrepareForSimImpl.run(PrepareForSimImpl.java:134)
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:106)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:83)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)

The simulation did not run properly. Error/Exit code: 1`

**Comment by emilymorey** [comment]
Hello - since posting the above message I have revisited the multi modal examples and noticed that the PLANS file does not contain any ROUTE information - whereas mine does. While this was not a problem for my single mode model (and MATSim ran fine), changing over to multi mode example caused an issue. Once I removed the ROUTE information, it ran perfectly! Best wishes Emily.
