### ISSUE TITLE
Can't run the Transit Schedule Validator

### ISSUE THREAD

**Issue by alexanderbachev** [matsim-org/matsim-code-examples#348]
Dear guys, 

I am struggling with running the Transit Schedule validator. I am building on the matsim-example-project. The validator option does not appear in the GUI under Tools as is described in the MATSim manual. I've tried running the class from Terminal with the command provided in the manual (with relative or absolute paths):

`java -Xmx512m -cp ../.m2/repository/org/matsim/matsim/11.0/matsim-11.0.jar org.matsim.pt.utils.TransitScheduleValidator scenarios/sofia/pt2matsim/transitSchedule_mapped.xml scenarios/sofia/pt2matsim/network_Sofia_oblast_multimodal_mapped.xml`

I get the following error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/log4j/Logger
        at org.matsim.core.config.Config.<clinit>(Config.java:112)
        at org.matsim.core.config.ConfigUtils.createConfig(ConfigUtils.java:58)
        at org.matsim.pt.utils.TransitScheduleValidator.main(TransitScheduleValidator.java:297)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 3 more
```
The path to the matsim-11.0.jar I have provided is the one to the local maven directory, where the dependancies are stored. I have peeked into the jar and indeed couldn't find org/apache directory at all. Do I have to download another richer matsim library/jar?

**Comment by alexanderbachev** [comment]
In case somebody runs into the same problem, one needs to download the zipped version of the matsim release (from here: https://www.matsim.org/downloads/) and point to the matsim-12.0.jar in the command from above. For some reason, when I point to the same jar but inside the local maven directory where it is downloaded, the above mentioned exception is raised.
