### ISSUE TITLE
AbstractQsim in SBB Transit

### ISSUE THREAD

**Issue by gregmacfarlane** [matsim-org/matsim-code-examples#36]
I am trying to put the PTIntermodalRouting example into a scenario where I already have the SBB Raptor transit router involved. This creates some kind of conflict in the QSim. From the example:

```java


        Controler controler = new Controler(scenario);

        // Use Swiss Rail RAPTOR transit router
        controler.addOverridingModule(new AbstractModule() {
            @Override
            public void install() {
                install(new SBBQSimModule());
                install(new SwissRailRaptorModule());
            }
        });

        controler.addQSimModule(new TaxiQSimModule());
        controler.addOverridingModule(DvrpModule.createModule(mode,
                Collections.<Class<? extends MobsimListener>>singleton(TaxiOptimizer.class)));

        controler.addOverridingModule(new TaxiModule());
```

Running this throws an error, 

```
Nov 16, 2018 10:44:09 AM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.lang.ClassNotFoundException: org.matsim.core.mobsim.qsim.AbstractQSimPlugin
java.lang.TypeNotPresentException: Type org.matsim.core.mobsim.qsim.AbstractQSimPlugin not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.MethodRepository.getReturnType(MethodRepository.java:68)
	at java.lang.reflect.Method.getGenericReturnType(Method.java:255)
	at com.google.inject.TypeLiteral.getReturnType(TypeLiteral.java:339)
	at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:263)
	at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:144)
	at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:123)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:349)
	at org.matsim.core.controler.AbstractModule.install(AbstractModule.java:129)
	at org.matsim.codeexamples.router.intermodalTaxi.RunTaxiPTIntermodalExample$1.install(RunTaxiPTIntermodalExample.java:107)
```

Is there something else I need to do in order to implement these two extensions together? Are they not compatible?

Edit: copying @josiekre

**Comment by gregmacfarlane** [comment]
To be clear, I have cobbled together this example in a fork at [https://github.com/gregmacfarlane/matsim-code-examples/blob/0.11.x/src/main/java/org/matsim/codeexamples/router/intermodalTaxi/RunTaxiPTIntermodalExample.java](https://github.com/gregmacfarlane/matsim-code-examples/blob/0.11.x/src/main/java/org/matsim/codeexamples/router/intermodalTaxi/RunTaxiPTIntermodalExample.java)

**Comment by vsp-gleich** [comment]
Are you only interested in the SBB Raptor Transit Router (faster/better routing for pt agents) or do you also want to use the Deterministic PT Simulation (public transit vehicles stick closer to the timetable, do not arrive earlier than planned)? You are loading both and I could imagine that you only want the transit router. In that case just delete the line "install(new SBBQSimModule());"

Now some speculation why that error actually occurs: A few months ago AbstractQSimPlugin was replaced with AbstractQSimModule in the matsim-0.11.0-Snapshot. The current "production release" of the SBB Matsim Extensions was built for matsim-0.10.0 and uses AbstractQSimPlugin. However, if you use the current matsim-0.11.0-Snapshot (or weekly release), there is no longer a class AbstractQSimPlugin and that is actually what the error message is saying. If you want to use the Deterministic PT Simulation have a look at the "development version" (no warranty whatsoever ;-) ) of the SBB matsim extensions: [https://github.com/simunto/matsim-sbb-extensions/tree/0.11.0-SNAPSHOT](https://github.com/simunto/matsim-sbb-extensions/tree/0.11.0-SNAPSHOT).
