### ISSUE TITLE
Unable to initialize 'javax.el.ExpressionFactory' when using ConfigUtils.loadConfig()

### ISSUE THREAD

**Issue by Janekdererste** [matsim-org/matsim-code-examples#366]
I am trying to load a config via ```ConfigUtils.loadConfig("some-path");``` but I get the following error

```
java.lang.ExceptionInInitializerError
	at org.matsim.core.config.Config.addCoreModules(Config.java:218)
	at org.matsim.core.config.ConfigUtils.loadConfig(ConfigUtils.java:147)
	at org.matsim.core.config.ConfigUtils.loadConfig(ConfigUtils.java:73)
	at org.matsim.contribs.analysis.EventsTest.testConfigUtils(EventsTest.java:161)
	... [some more]
Caused by: javax.validation.ValidationException: HV000183: Unable to initialize 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.buildExpressionFactory(ResourceBundleMessageInterpolator.java:206)
	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.<init>(ResourceBundleMessageInterpolator.java:94)
	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.getDefaultMessageInterpolator(AbstractConfigurationImpl.java:559)
	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.getDefaultMessageInterpolatorConfiguredWithClassLoader(AbstractConfigurationImpl.java:759)
	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.getMessageInterpolator(AbstractConfigurationImpl.java:468)
	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:147)
	at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38)
	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.buildValidatorFactory(AbstractConfigurationImpl.java:435)
	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:103)
	at org.matsim.core.config.consistency.BeanValidationConfigConsistencyChecker.<clinit>(BeanValidationConfigConsistencyChecker.java:41)
	... 30 more
```

I am using my own project with matsim 12.0 as a dependency. When I look into the maven dependency tree, only matsim depends on this module. The dependency is used within ```BeanValidationConfigConsistencyChecker``` which was created by @michalmac . 

Maybe anyone has seen this error?

**Comment by Janekdererste** [comment]
Solved the issue myself. I found out that some a dependency (hadoop-common) had a dependency on javax.servlet.jsp:jsp-api which has its own ExpressionFactory and is not compatible whit Hibernate's validator. 

Adding:
```
<exclusions>
    <exclusion>
        <groupId>javax.servlet.jsp</groupId>
        <artifactId>jsp-api</artifactId>
    </exclusion>
</exclusions>
```
To the hadoop dependency solved it. Just writing it down, so someone can google this :-)
