### ISSUE TITLE
NullPointerException in OsmBicycleReader

### ISSUE THREAD

**Issue by ctchervenkov** [matsim-org/matsim-code-examples#373]
I recently wanted to use the OSMBicycleReader to read in a .osm.pbf file for San Francisco (also tried for Zurich), but each time ran into the following error.

```shell
2020-07-02T16:46:01,584  INFO SupersonicOsmNetworkReader:67 starting convertion 🚀
2020-07-02T16:46:01,627  INFO NetworkImpl:163  node # 1
2020-07-02T16:46:01,627  INFO NetworkImpl:159  link # 1
2020-07-02T16:46:01,628  INFO NetworkImpl:159  link # 4
2020-07-02T16:46:01,628  INFO NetworkImpl:163  node # 4
...
Exception in thread "main" java.lang.NullPointerException
	at org.matsim.contrib.osm.networkReader.SupersonicOsmNetworkReader.createWaySegments(SupersonicOsmNetworkReader.java:98)
	at org.matsim.contrib.osm.networkReader.SupersonicOsmNetworkReader.lambda$convert$0(SupersonicOsmNetworkReader.java:77)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3605)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.matsim.contrib.osm.networkReader.SupersonicOsmNetworkReader.convert(SupersonicOsmNetworkReader.java:79)
	at org.matsim.contrib.osm.networkReader.SupersonicOsmNetworkReader.read(SupersonicOsmNetworkReader.java:68)
	at org.matsim.contrib.osm.networkReader.SupersonicOsmNetworkReader.read(SupersonicOsmNetworkReader.java:59)
	at org.eqasim.conferences.sf_trb2021.network.RunOSMBikeNetworkReader.main(RunOSMBikeNetworkReader.java:22)
```

**Comment by Janekdererste** [comment]
Could you provide your pom.xml as well, so that I can see which matsim version you are using? 

Also, please have a look at https://github.com/matsim-org/matsim-code-examples/issues/362#issuecomment-648628710 whether you've included the necessary dependencies.

If you provide me a link to the input osm file, I will try running it myself

**Comment by ctchervenkov** [comment]
Just added in the 2 repos you mentioned.
I will send you the simple OSM files via email.

```shell
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.eqasim.conferences</groupId>
    <artifactId>sf-trb2021</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <matsim.version>12.0</matsim.version>
        <swiss_rail.version>11.2</swiss_rail.version>
    </properties>

    <repositories>
        <repository>
            <id>osgeo</id>
            <name>Geotools repository</name>
            <url>https://repo.osgeo.org/repository/release/</url>
        </repository>
        <repository>
            <id>matsim</id>
            <url>http://dl.bintray.com/matsim/matsim</url>
        </repository>
        <repository>
            <id>matsim-eth</id>
            <url>http://dl.bintray.com/matsim-eth/matsim</url>
        </repository>
        <repository>
            <id>swiss-rail</id>
            <url>https://schweizerischebundesbahnen.bintray.com/simba.mvn</url>
        </repository>
        <repository>
            <id>pt2matsim</id>
            <url>http://dl.bintray.com/polettif/matsim</url>
        </repository>
        <repository>
            <id>topobyte</id>
            <url>http://mvn.topobyte.de</url>
        </repository>
        <repository>
            <id>slimjars</id>
            <url>http://mvn.slimjars.com</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
            <version>2.9.9</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.9.10.4</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-math3</artifactId>
            <version>3.6.1</version>
        </dependency>

        <dependency>
            <groupId>org.matsim</groupId>
            <artifactId>matsim</artifactId>
            <version>${matsim.version}</version>
        </dependency>

        <dependency>
            <groupId>org.matsim.contrib</groupId>
            <artifactId>osm</artifactId>
            <version>${matsim.version}</version>
        </dependency>

        <dependency>
            <groupId>ch.sbb</groupId>
            <artifactId>matsim-sbb-extensions</artifactId>
            <version>${swiss_rail.version}</version>
        </dependency>

        <dependency>
            <groupId>ch.ethz.matsim</groupId>
            <artifactId>discrete_mode_choice</artifactId>
            <version>1.0.8-matsim11</version>
        </dependency>

        <dependency>
            <groupId>org.matsim</groupId>
            <artifactId>pt2matsim</artifactId>
            <version>20.5</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```

**Comment by Janekdererste** [comment]
I ran your example with the provided input file. It seems like you have a way (id: 47426217) in your file which references nodes that are not included in your file. (I only checked for the first node with id 259836994)

I'd recommend to download a suitable osm file from geofabrik. In your case probably this one https://download.geofabrik.de/europe/switzerland.html and then filter only the links you want to have in your matsim network. You can find an example in the contrib https://github.com/matsim-org/matsim-libs/blob/master/contribs/osm/src/main/java/org/matsim/contrib/osm/examples/RunFullyConfiguredNetworkReader.java which uses all the functionality of the reader. Your spatial filter could be plugged into the reader through the 'includeLinkAtCoordWithHierarchy' callback.

A real world example from the last project I prepared using a shape file to filter out certain links within an area can be found here: https://github.com/matsim-scenarios/matsim-ruhrgebiet/blob/1f997b97cbd38e030b2adedbbde05048762afa93/src/main/java/org/matsim/ruhrgebiet/prepare/PrepareNetworkAndPt.java#L75

**Comment by ctchervenkov** [comment]
Ok, thanks for your help. I will take a look at your last link. I had downloaded the Switzerland osm file from geofabrik and then simply cut out the city of Zurich using osmosis. This cutting obviously produced the issue of links with missing nodes. When we run such cut networks through pt2matsim, these cases are taken care of and so I did not think of it.

**Comment by ctchervenkov** [comment]
FYI, I am able to run the reader now. The only issue now is regarding the cycleway tag. Currently, you only look for `cycleway`, but there are also `cycleway:both=*`, `cycleway:left=*`, `cycleway:right=*` tags, which sometimes are even more common than the simply `cycleway` tag. Now, I wanted to add them in myself in branch, but loading the project into Intellij, I get the following:

`Cannot resolve org.matsim.contrib:osm:13.0-SNAPSHOT`

which is the version in the pom.

**Comment by Janekdererste** [comment]
It would be great if you'd contribute a pull request. 

If you just checkout the whole matsim project (https://github.com/matsim-org/matsim-libs) and import it as maven project into eclipse or intellij, you should be fine. 

At least for Intellij, if you've already imported the project you can right click on your pom.xml -> maven -> Reload project. That triggers Intellij to re-resolve your dependencies. I don't know how this would work in eclipse though

**Comment by anezkap** [comment]
Hey hey, very late to the party, but I believe the cycleway tag issue was not addressed anywhere yet.

So just in case anyone else is looking for *inspiration* on how to do this, changing `setCycleWay` in `OsmBycicleReader` to this worked for me:

```
    private static void setCycleWay(Link link, Map<String, String> tags) {
        if (tags.containsKey(OsmTags.CYCLEWAY))
            link.getAttributes().putAttribute(OsmTags.CYCLEWAY, tags.get(OsmTags.CYCLEWAY));
        else if (tags.containsKey("cycleway:both"))
            link.getAttributes().putAttribute(OsmTags.CYCLEWAY, tags.get("cycleway:both"));

        // For right-hand traffic (e.g. Belgium): the right side of the road corresponds to the
        // forward direction, and the left side to the reverse direction.
        // If the cycleway is only on one side, only apply it to the forward or reverse link accordingly.
        else if (tags.containsKey("cycleway:right") && link.getId().toString().endsWith("f"))
            link.getAttributes().putAttribute(OsmTags.CYCLEWAY, tags.get("cycleway:right"));
        else if (tags.containsKey("cycleway:left") && link.getId().toString().endsWith("r"))
            link.getAttributes().putAttribute(OsmTags.CYCLEWAY, tags.get("cycleway:left"));

        // Add cycleway for oneway roads that have reverse cycleway
        else if (tags.containsKey("cycleway:left") && link.getId().toString().endsWith("_bike-reverse"))
            link.getAttributes().putAttribute(OsmTags.CYCLEWAY, tags.get("cycleway:left"));
    }
```

I only tested it on a small scenario, so maybe I missed something and it could definitely be made cleaner, but it is an attempt.

If I have some time, I will try to test it and clean up properly and will create a PR.
