### ISSUE TITLE
XML_FATAL but XML document is fine 

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#377]
Hi everyone, I came across this exception when running MATSim.

```
XML-FATAL: file:/E:/MATSim%2012.0/scenarios/testQConfig/test-profiles/personAttributes.xml, line 21361, column 9:
org.xml.sax.SAXParseException; systemId: file:/E:/MATSim%2012.0/scenarios/testQConfig/test-profiles/personAttributes.xml; lineNumber: 21361; columnNumber: 9; The end-tag for element type "object" must end with a '>' delimiter.
Exception in thread "main" org.matsim.core.utils.io.UncheckedIOException: org.xml.sax.SAXParseException; systemId: file:/E:/MATSim%2012.0/scenarios/testQConfig/test-profiles/personAttributes.xml; lineNumber: 21361; columnNumber: 9; The end-tag for element type "object" must end with a '>' delimiter.
	at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:199)
	at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:169)
	at org.matsim.core.scenario.ScenarioLoaderImpl.parseObjectAttributesToAttributable(ScenarioLoaderImpl.java:360)
	at org.matsim.core.scenario.ScenarioLoaderImpl.loadPopulation(ScenarioLoaderImpl.java:213)
	at org.matsim.core.scenario.ScenarioLoaderImpl.loadScenario(ScenarioLoaderImpl.java:115)
	at org.matsim.core.scenario.ScenarioUtils.loadScenario(ScenarioUtils.java:79)
	at org.matsim.project.RunMatsim.main(RunMatsim.java:49)
Caused by: org.xml.sax.SAXParseException; systemId: file:/E:/MATSim%2012.0/scenarios/testQConfig/test-profiles/personAttributes.xml; lineNumber: 21361; columnNumber: 9; The end-tag for element type "object" must end with a '>' delimiter.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:196)
	... 6 more
```

**It mentioned something wrong with my personAttributes file. Which is weird because the last line (which is also the line that exception occurred) is written as `</objectAttributes>` . 
The personAttributes file is generated through a population generation pipeline. MATSim works perfectly with the previous example personAttributes file, the last line of that one is also `</objectAttributes>` .  So I suppose there shouldn't be any problem with the format. 

I'm wondering if anyone has any idea or past experience about this exception? Thanks very much for your help in advance!**

**Comment by HubbleCommand** [comment]
Would it be possible for you to upload the XML file? There might be an object in <objectAttributes></objectAttributes> that isn't properly terminated. Although as it's generated for you I doubt that's the problem.

I don't have much experience with MATSim, and have never encountered that error, but from the log it seems to me that something is not properly formatted in your XML.

**Comment by jingjunL** [comment]
> Would it be possible for you to upload the XML file? There might be an object in that isn't properly terminated. Although as it's generated for you I doubt that's the problem.
> 
> I don't have much experience with MATSim, and have never encountered that error, but from the log it seems to me that something is not properly formatted in your XML.

Hello Hubble. Thanks for your reply. Sure, here is the XML file I am using. Since Git doesn't support XML upload, I have change that to txt format. Thanks again!
[personAttributes.txt](https://github.com/matsim-org/matsim-code-examples/files/4877912/personAttributes.txt)

**Comment by jingjunL** [comment]
> Would it be possible for you to upload the XML file? There might be an object in that isn't properly terminated. Although as it's generated for you I doubt that's the problem.
> 
> I don't have much experience with MATSim, and have never encountered that error, but from the log it seems to me that something is not properly formatted in your XML.

Hello Hubble, I did found a problem with my population pipeline and it works now. Many thanks for your help! Have a nice day :)

**Comment by HubbleCommand** [comment]
Yep, looks like the object tags weren't closed!

Glad I could be of assistance :)
