### ISSUE TITLE
The error in using MATSim0.10.1

### ISSUE THREAD

**Issue by Cuiyi20** [matsim-org/matsim-code-examples#4]
Dear MATSim,
When I run the project example siouxfalls-2014 in my computer using MATSim0.10.1, the system throw a problem. The message is under follow.

2018-08-29 10:02:31,352 ERROR MatsimRuntimeModifications:54 Getting uncaught Exception in Thread main
java.lang.IncompatibleClassChangeError: Found interface org.matsim.core.config.ConfigWriterHandler, but class was expected
	at org.matsim.core.config.ConfigWriter.writeStream(ConfigWriter.java:73)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:61)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2018-08-29 10:02:31,356 ERROR MatsimRuntimeModifications:60 ERROR --- This is an unexpected shutdown!
2018-08-29 10:02:31,356 ERROR MatsimRuntimeModifications:63 Shutdown possibly caused by the following Exception:
java.lang.IncompatibleClassChangeError: Found interface org.matsim.core.config.ConfigWriterHandler, but class was expected
	at org.matsim.core.config.ConfigWriter.writeStream(ConfigWriter.java:73)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:61)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2018-08-29 10:02:31,363 ERROR MatsimRuntimeModifications:78 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2018-08-29 10:02:31,372 ERROR MatsimRuntimeModifications:79 ERROR --- results should not be used for further analysis.
2018-08-29 10:02:31,378 ERROR MatsimRuntimeModifications:83 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.

Do anyone know the reason? Thank you!

**Comment by kainagel** [comment]
Dear Cuiyi20,

it is not doing it for me.  Could you please tell us how you started matsim?  And also please attach the full logfile.  Thanks.

Best wishes

Kai

**Comment by Cuiyi20** [comment]
Thank you, Professor!
I use the MATSim0.10.1 by double clicking the matsim-0.10.1.jar. And I resd the "API Documentation (Doxygen)", but the class "ConfigWriterHandler" font is black and has no link.
2018-08-29 10:02:31,238  INFO Gbl:59 JVM: 1.8.0_162; Oracle Corporation; mixed mode; 64-bit
2018-08-29 10:02:31,238  INFO Gbl:63 OS: Windows 10; 10.0; amd64
2018-08-29 10:02:31,239  INFO Gbl:66 CPU cores: 4
2018-08-29 10:02:31,239  INFO Gbl:67 max. Memory: 6667.0MB (6990856192B)
2018-08-29 10:02:31,240  INFO Gbl:105 MATSim-Build: r7663c4104e5a02ad1684b3cbab3ad6da7f0eb749 (2018-08-14 09:25:58)
2018-08-29 10:02:31,242  INFO ControlerListenerManagerImpl:107 calling notifyStartup on org.matsim.counts.CountsControlerListener
2018-08-29 10:02:31,243  INFO ControlerListenerManagerImpl:107 calling notifyStartup on org.matsim.analysis.ModeStatsControlerListener
2018-08-29 10:02:31,252  INFO TransitRouterNetwork:407 start creating transit network
2018-08-29 10:02:31,253  INFO Counter:61  node #1
2018-08-29 10:02:31,254  INFO Counter:61  node #2
2018-08-29 10:02:31,255  INFO Counter:61  link #1
2018-08-29 10:02:31,256  INFO Counter:61  link #2
2018-08-29 10:02:31,256  INFO Counter:61  node #4
2018-08-29 10:02:31,256  INFO Counter:61  link #4
2018-08-29 10:02:31,257  INFO Counter:61  node #8
2018-08-29 10:02:31,257  INFO Counter:61  link #8
2018-08-29 10:02:31,257  INFO Counter:61  node #16
2018-08-29 10:02:31,258  INFO Counter:61  link #16
2018-08-29 10:02:31,258  INFO Counter:61  node #32
2018-08-29 10:02:31,267  INFO Counter:61  link #32
2018-08-29 10:02:31,271  INFO Counter:61  node #64
2018-08-29 10:02:31,273  INFO Counter:61  link #64
2018-08-29 10:02:31,275  INFO Counter:61  node #128
2018-08-29 10:02:31,278  INFO Counter:61  link #128
2018-08-29 10:02:31,289  INFO TransitRouterNetwork:433 add transfer links
2018-08-29 10:02:31,296  INFO TransitRouterNetwork:449 182 transfer links to be added.
2018-08-29 10:02:31,302  INFO Counter:61  link #256
2018-08-29 10:02:31,304  INFO TransitRouterNetwork:455 transit router network statistics:
2018-08-29 10:02:31,304  INFO TransitRouterNetwork:456  # nodes: 141
2018-08-29 10:02:31,304  INFO TransitRouterNetwork:457  # links total:     313
2018-08-29 10:02:31,305  INFO TransitRouterNetwork:458  # transfer links:  182
2018-08-29 10:02:31,311 DEBUG NetworkRoutingProvider:75 requesting network routing module with routingMode=car;	mode=car
2018-08-29 10:02:31,312  INFO NetworkImpl:167  node # 1
2018-08-29 10:02:31,312  INFO NetworkImpl:167  node # 4
2018-08-29 10:02:31,312  INFO NetworkImpl:167  node # 16
2018-08-29 10:02:31,313  INFO NetworkImpl:167  node # 64
2018-08-29 10:02:31,313  INFO NetworkImpl:167  node # 256
2018-08-29 10:02:31,315  INFO NetworkImpl:163  link # 1
2018-08-29 10:02:31,316  INFO NetworkImpl:163  link # 4
2018-08-29 10:02:31,317  INFO NetworkImpl:163  link # 16
2018-08-29 10:02:31,318  INFO NetworkImpl:163  link # 64
2018-08-29 10:02:31,326  INFO NetworkImpl:163  link # 256
2018-08-29 10:02:31,337  INFO ControlerListenerManagerImpl:107 calling notifyStartup on org.matsim.analysis.ScoreStatsControlerListener
2018-08-29 10:02:31,338  INFO ControlerListenerManagerImpl:110 all ControlerStartupListeners called.
2018-08-29 10:02:31,338  INFO ControlerUtils:58 config dump before iterations start
2018-08-29 10:02:31,341  INFO Config:561 setting context to [file:/D:/siouxfalls-2014/]
2018-08-29 10:02:31,352 ERROR MatsimRuntimeModifications:54 Getting uncaught Exception in Thread main
java.lang.IncompatibleClassChangeError: Found interface org.matsim.core.config.ConfigWriterHandler, but class was expected
	at org.matsim.core.config.ConfigWriter.writeStream(ConfigWriter.java:73)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:61)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2018-08-29 10:02:31,355  INFO MatsimRuntimeModifications:58 S H U T D O W N   ---   start shutdown.
2018-08-29 10:02:31,356 ERROR MatsimRuntimeModifications:60 ERROR --- This is an unexpected shutdown!
2018-08-29 10:02:31,356 ERROR MatsimRuntimeModifications:63 Shutdown possibly caused by the following Exception:
java.lang.IncompatibleClassChangeError: Found interface org.matsim.core.config.ConfigWriterHandler, but class was expected
	at org.matsim.core.config.ConfigWriter.writeStream(ConfigWriter.java:73)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:61)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:82)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at org.matsim.core.controler.Controler.run(Controler.java:202)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2018-08-29 10:02:31,358  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.EventsHandlingImpl
2018-08-29 10:02:31,358  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.DumpDataAtEndImpl
2018-08-29 10:02:31,358  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ModeStatsControlerListener
2018-08-29 10:02:31,361  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ScoreStatsControlerListener
2018-08-29 10:02:31,362  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.TravelDistanceStatsControlerListener
2018-08-29 10:02:31,362  INFO ControlerListenerManagerImpl:129 all ControlerShutdownListeners called.
2018-08-29 10:02:31,363 ERROR MatsimRuntimeModifications:78 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2018-08-29 10:02:31,372 ERROR MatsimRuntimeModifications:79 ERROR --- results should not be used for further analysis.
2018-08-29 10:02:31,378  INFO MatsimRuntimeModifications:81 S H U T D O W N   ---   shutdown completed.
2018-08-29 10:02:31,378 ERROR MatsimRuntimeModifications:83 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.

**Comment by Cuiyi20** [comment]
[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/2331023/logfile.log)

**Comment by jfbischoff** [comment]
Hi Cuiyi,
there was a little problem with the release on the website in the zip package. We have fixed that very recently. Please download the fixed zipfile from:

https://matsim.org/downloads/

Bests,
Joschka

**Comment by Cuiyi20** [comment]
Thank you very much！The priblem is solved!
