### ISSUE TITLE
subtourModeChoice causing "injection" error 

### ISSUE THREAD

**Issue by fredshone** [matsim-org/matsim-code-examples#414]
Hi, 

we have a previously running multimodal (+ raptor) (matsim version 11) scenario that is throwing the following error when we try and use the `subtourModeChoice` strategy (we previously were using `ChangeSingleTripMode`):

```
1) No implementation for org.matsim.core.replanning.PlanStrategy annotated with @com.google.inject.name.Named(value=subtourModeChoice) was bound.
at org.matsim.core.replanning.StrategyManagerModule.install(StrategyManagerModule.java:87) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.replanning.StrategyManagerModule)
```

**Comment by fredshone** [comment]
We get the same looking issue running V12, log below. Is `subtourModeChoice` redundant now?

```
2020-08-19T16:00:23,961  INFO VspConfigConsistencyCheckerImpl:58 NOT running vsp config consistency check because vsp defaults checking level is set to IGNORE
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/Users/mickyfitz/workspace/columbus/target/columbus-1.0.0-SNAPSHOT-jar-with-dependencies.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:
1) No implementation for org.matsim.core.replanning.PlanStrategy annotated with @com.google.inject.name.Named(value="subtourModeChoice") was bound.
  Did you mean?
    * org.matsim.core.replanning.PlanStrategy annotated with @com.google.inject.name.Named(value="ChangeExpBeta")
    * org.matsim.core.replanning.PlanStrategy annotated with @com.google.inject.name.Named(value="ReRoute")
    * org.matsim.core.replanning.PlanStrategy annotated with @com.google.inject.name.Named(value="TimeAllocationMutator")
    15 more bindings with other annotations.
  at org.matsim.core.replanning.StrategyManagerModule.install(StrategyManagerModule.java:87) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.replanning.StrategyManagerModule)
2) No implementation for org.matsim.core.replanning.PlanStrategy annotated with @com.google.inject.name.Named(value="subtourModeChoice") was bound.
  Did you mean?
    * org.matsim.core.replanning.PlanStrategy annotated with @com.google.inject.name.Named(value="ChangeExpBeta")
    * org.matsim.core.replanning.PlanStrategy annotated with @com.google.inject.name.Named(value="ReRoute")
    * org.matsim.core.replanning.PlanStrategy annotated with @com.google.inject.name.Named(value="TimeAllocationMutator")
    15 more bindings with other annotations.
  at org.matsim.core.replanning.StrategyManagerModule.install(StrategyManagerModule.java:87) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.replanning.StrategyManagerModule)
3) No implementation for org.matsim.core.replanning.PlanStrategy annotated with @com.google.inject.name.Named(value="subtourModeChoice") was bound.
  Did you mean?
    * org.matsim.core.replanning.PlanStrategy annotated with @com.google.inject.name.Named(value="ChangeExpBeta")
    * org.matsim.core.replanning.PlanStrategy annotated with @com.google.inject.name.Named(value="ReRoute")
    * org.matsim.core.replanning.PlanStrategy annotated with @com.google.inject.name.Named(value="TimeAllocationMutator")
    15 more bindings with other annotations.
  at org.matsim.core.replanning.StrategyManagerModule.install(StrategyManagerModule.java:87) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.replanning.StrategyManagerModule)
3 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:237)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:242)
	at org.matsim.core.controler.Injector.createInjector(Injector.java:74)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at com.arup.cm.RunMultimodalMatsim.main(RunMultimodalMatsim.java:38)
```

**Comment by fredshone** [comment]
Resolved as follows:

The module is called subtourModeChoice  but the strategy name is SubtourModeChoice, eg:
```
	<module name="subtourModeChoice">
		<param name="chainBasedModes" value="car,bike" />
		<param name="modes" value="car,bus,train,walk,bike" />
	</module>

	<module name="strategy">
		<param name="maxAgentPlanMemorySize" value="5" />
		<parameterset type="strategysettings">
			<param name="strategyName" value="SubtourModeChoice"/>
			<param name="subpopulation" value="low income"/>
			<param name="weight" value="0.1"/>
		</parameterset>
        ...
        </module name="strategy">
```
