### ISSUE TITLE
one_taxi simulation error

### ISSUE THREAD

**Issue by daisychang2309** [matsim-org/matsim-code-examples#422]
Hi, I try to run one_taxi config but it turned out to be error.
I didn't revise any of code from code example but it just turned out to be error, I would really appreciate for your help.
*I uses matsim 0.10.1 ver

The following is the error file.
> 
2020-08-28 10:15:59,861 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
java.lang.RuntimeException: Unmaterialized config group: multiModeTaxi
	at org.matsim.core.config.consistency.UnmaterializedConfigGroupChecker.checkConsistency(UnmaterializedConfigGroupChecker.java:32)
	at org.matsim.core.config.Config.checkConsistency(Config.java:225)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:65)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:78)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.project.RunMatsim.main(RunMatsim.java:55)
2020-08-28 10:15:59,863 ERROR MatsimRuntimeModifications:81 ERROR --- This is an unexpected shutdown!
2020-08-28 10:15:59,863 ERROR MatsimRuntimeModifications:84 Shutdown possibly caused by the following Exception:
java.lang.RuntimeException: Unmaterialized config group: multiModeTaxi
	at org.matsim.core.config.consistency.UnmaterializedConfigGroupChecker.checkConsistency(UnmaterializedConfigGroupChecker.java:32)
	at org.matsim.core.config.Config.checkConsistency(Config.java:225)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:65)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:78)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.project.RunMatsim.main(RunMatsim.java:55)
2020-08-28 10:16:00,878 ERROR MatsimRuntimeModifications:99 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2020-08-28 10:16:00,878 ERROR MatsimRuntimeModifications:100 ERROR --- results should not be used for further analysis.
2020-08-28 10:16:00,878 ERROR MatsimRuntimeModifications:104 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.

And the following is config file.

`

<?xml version="1.0" ?>
<!DOCTYPE config SYSTEM "http://www.matsim.org/files/dtd/config_v2.dtd">
<config>
	<module name="multiModeTaxi">
		<parameterset type="taxi">
			<param name="destinationKnown" value="false"/>
			<param name="vehicleDiversion" value="false"/>
			<param name="pickupDuration" value="120"/>
			<param name="dropoffDuration" value="60"/>
			<param name="onlineVehicleTracker" value="false"/>

			<param name="taxisFile" value="one_taxi_vehicles.xml"/>

			<param name="timeProfiles" value="true"/>
			<param name="detailedStats" value="true"/>

			<parameterset type="RuleBasedTaxiOptimizer"/>
		</parameterset>
	</module>

	<module name="network">
		<param name="inputNetworkFile" value="grid_network.xml"/>
	</module>

	<module name="plans">
		<param name="inputPlansFile" value="one_taxi_population.xml"/>
	</module>

	<module name="qsim">
		<param name="simStarttimeInterpretation" value="onlyUseStarttime"/>
		<param name="insertingWaitingVehiclesBeforeDrivingVehicles" value="true"/>
		<param name="snapshotStyle" value="queue"/>
	</module>

	<module name="otfvis">
		<param name="coloringScheme" value="taxicab"/>
		<param name="drawNonMovingItems" value="true"/>
	</module>

	<module name="controler">
		<param name="outputDirectory" value="test/output/one_taxi"/>
		<param name="overwriteFiles" value="deleteDirectoryIfExists"/>
		<param name="firstIteration" value="0"/>
		<param name="lastIteration" value="0"/>
	</module>

	<module name="planCalcScore">
		<param name="activityType_0" value="dummy"/>
		<param name="activityTypicalDuration_0" value="24:00:00"/>
		<param name="traveling_taxi" value="-6"/>
	</module>

	<module name="strategy">
		
		<param name="maxAgentPlanMemorySize" value="1"/>
		<param name="ModuleProbability_1" value="1.0"/>
		<param name="Module_1" value="KeepLastSelected"/>
	</module>
</config>
`

**Comment by michalmac** [comment]
Closing it as this thread moved to: https://github.com/matsim-org/matsim-code-examples/issues/436
