### ISSUE TITLE
stuck in landmarks calculator and then get error and it stops running

### ISSUE THREAD

**Issue by elyh1992** [matsim-org/matsim-code-examples#443]
Hi,

I was running a model without any problem then I changed the monetary distance rate from 0 to 0.00017. Since then when running the model, it stuck for a long time in the landmark calculation part and then I get the following error. Do you have any suggestions about why this happen and what should I do to solve it? Is it a memory problem? If yes is there a way to solve it?
Thank you in advance for your help.
error:
2020-10-10 00:56:28,988 ERROR MatsimRuntimeModifications$1:62 Getting uncaught Exception in Thread pool-1-thread-1
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
	at java.base/java.util.PriorityQueue.grow(PriorityQueue.java:306)
	at java.base/java.util.PriorityQueue.offer(PriorityQueue.java:345)
	at java.base/java.util.PriorityQueue.add(PriorityQueue.java:327)
	at org.matsim.core.router.util.PreProcessLandmarks$Calculator.expandLandmarkFrom(PreProcessLandmarks.java:203)
	at org.matsim.core.router.util.PreProcessLandmarks$Calculator.run(PreProcessLandmarks.java:180)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-10-10 00:56:28,995 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.RuntimeException: java.lang.InterruptedException
  at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:68) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.router.TripRouterModule)
  while locating org.matsim.core.router.RoutingModule annotated with @com.google.inject.name.Named(value=car)
  while locating org.matsim.core.router.RoutingModule annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=100, type=MAPBINDER, keyType=java.lang.String)
  at org.matsim.core.router.TripRouter.<init>(TripRouter.java:102)
  while locating org.matsim.core.router.TripRouter

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at org.matsim.core.controler.PrepareForSimImpl.lambda$run$0(PrepareForSimImpl.java:168)
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils.run(ParallelPersonAlgorithmUtils.java:86)
	at org.matsim.core.controler.PrepareForSimImpl.run(PrepareForSimImpl.java:167)
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:115)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:79)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:248)
	at org.matsim.run.RunMelbourne_new.main(RunMelbourne_new.java:60)
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
	at org.matsim.core.router.util.PreProcessLandmarks.run(PreProcessLandmarks.java:143)
	at org.matsim.core.router.FastAStarLandmarksFactory.createPathCalculator(FastAStarLandmarksFactory.java:89)
	at org.matsim.core.router.NetworkRoutingProvider.get(NetworkRoutingProvider.java:120)
	at org.matsim.core.router.NetworkRoutingProvider.get(NetworkRoutingProvider.java:45)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:104)
	at com.google.inject.multibindings.MapBinder$RealMapBinder$ValueProvider.get(MapBinder.java:821)
	at org.matsim.core.router.TripRouter.<init>(TripRouter.java:106)
	at org.matsim.core.router.TripRouter$$FastClassByGuice$$40b051f1.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 11 more
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1454)
	at org.matsim.core.router.util.PreProcessLandmarks.run(PreProcessLandmarks.java:141)
	... 33 more
2020-10-10 00:56:29,003 ERROR MatsimRuntimeModifications:81 ERROR --- This is an unexpected shutdown!
2020-10-10 00:56:29,003 ERROR MatsimRuntimeModifications:84 Shutdown possibly caused by the following Exception:
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.RuntimeException: java.lang.InterruptedException
  at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:68) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.router.TripRouterModule)
  while locating org.matsim.core.router.RoutingModule annotated with @com.google.inject.name.Named(value=car)
  while locating org.matsim.core.router.RoutingModule annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=100, type=MAPBINDER, keyType=java.lang.String)
  at org.matsim.core.router.TripRouter.<init>(TripRouter.java:102)
  while locating org.matsim.core.router.TripRouter

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at org.matsim.core.controler.PrepareForSimImpl.lambda$run$0(PrepareForSimImpl.java:168)
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils.run(ParallelPersonAlgorithmUtils.java:86)
	at org.matsim.core.controler.PrepareForSimImpl.run(PrepareForSimImpl.java:167)
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:115)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:79)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:248)
	at org.matsim.run.RunMelbourne_new.main(RunMelbourne_new.java:60)
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
	at org.matsim.core.router.util.PreProcessLandmarks.run(PreProcessLandmarks.java:143)
	at org.matsim.core.router.FastAStarLandmarksFactory.createPathCalculator(FastAStarLandmarksFactory.java:89)
	at org.matsim.core.router.NetworkRoutingProvider.get(NetworkRoutingProvider.java:120)
	at org.matsim.core.router.NetworkRoutingProvider.get(NetworkRoutingProvider.java:45)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
2020-10-10 00:56:29,003  INFO MatsimRuntimeModifications:79 S H U T D O W N   ---   start shutdown.
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:104)
	at com.google.inject.multibindings.MapBinder$RealMapBinder$ValueProvider.get(MapBinder.java:821)
	at org.matsim.core.router.TripRouter.<init>(TripRouter.java:106)
	at org.matsim.core.router.TripRouter$$FastClassByGuice$$40b051f1.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 11 more
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1454)
	at org.matsim.core.router.util.PreProcessLandmarks.run(PreProcessLandmarks.java:141)
	... 33 more
2020-10-10 00:56:29,013  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.EventsHandlingImpl
2020-10-10 00:56:29,013  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.DumpDataAtEndImpl
2020-10-10 00:56:29,021  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ModeStatsControlerListener
2020-10-10 00:56:29,021  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ScoreStatsControlerListener
2020-10-10 00:56:29,021  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.TravelDistanceStatsControlerListener
2020-10-10 00:56:30,537  INFO ControlerListenerManagerImpl:129 all ControlerShutdownListeners called.
2020-10-10 00:56:30,537  INFO MatsimRuntimeModifications:102 S H U T D O W N   ---   shutdown completed.
2020-10-10 00:56:30,537 ERROR MatsimRuntimeModifications:99 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2020-10-10 00:56:30,537 ERROR MatsimRuntimeModifications:100 ERROR --- results should not be used for further analysis.
2020-10-10 00:56:30,537 ERROR MatsimRuntimeModifications:104 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.RuntimeException: java.lang.InterruptedException
  at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:68) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$2 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.router.TripRouterModule)
  while locating org.matsim.core.router.RoutingModule annotated with @com.google.inject.name.Named(value=car)
  while locating org.matsim.core.router.RoutingModule annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=100, type=MAPBINDER, keyType=java.lang.String)
  at org.matsim.core.router.TripRouter.<init>(TripRouter.java:102)
  while locating org.matsim.core.router.TripRouter

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at org.matsim.core.controler.PrepareForSimImpl.lambda$run$0(PrepareForSimImpl.java:168)
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils.run(ParallelPersonAlgorithmUtils.java:86)
	at org.matsim.core.controler.PrepareForSimImpl.run(PrepareForSimImpl.java:167)
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:115)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:79)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:248)
	at org.matsim.run.RunMelbourne_new.main(RunMelbourne_new.java:60)
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
	at org.matsim.core.router.util.PreProcessLandmarks.run(PreProcessLandmarks.java:143)
	at org.matsim.core.router.FastAStarLandmarksFactory.createPathCalculator(FastAStarLandmarksFactory.java:89)
	at org.matsim.core.router.NetworkRoutingProvider.get(NetworkRoutingProvider.java:120)
	at org.matsim.core.router.NetworkRoutingProvider.get(NetworkRoutingProvider.java:45)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.spi.ProviderLookup$1.get(ProviderLookup.java:104)
	at com.google.inject.multibindings.MapBinder$RealMapBinder$ValueProvider.get(MapBinder.java:821)
	at org.matsim.core.router.TripRouter.<init>(TripRouter.java:106)
	at org.matsim.core.router.TripRouter$$FastClassByGuice$$40b051f1.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 11 more
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133)
	at java.base/java.util.concurrent.ThreadPoolExecutor.awaitTermination(ThreadPoolExecutor.java:1454)
	at org.matsim.core.router.util.PreProcessLandmarks.run(PreProcessLandmarks.java:141)
	... 33 more
2020-10-10 00:56:48,019  INFO MemoryObserver:41 used RAM: 1860 MB  free: 2203 MB  total: 4064 MB
2020-10-10 00:57:48,022  INFO MemoryObserver:41 used RAM: 2790 MB  free: 1273 MB  total: 4064 MB

**Comment by mrieser** [comment]
> I changed the monetary distance rate from 0 to 0.00017

change it to `-0.00017`, i.e. a negative value. A positive value means the agent gains money when driving, so by driving circles they can gain more and more and more money, which is why the routing does not end until the memory runs out.

**Comment by elyh1992** [comment]
Thank you. This solves the problem.
