### ISSUE TITLE
Exception while running MATSim

### ISSUE THREAD

**Issue by nkuehnel** [matsim-org/matsim-code-examples#45]
Hi everyone,

can anyone help me with this exception? Log file is attached as well

Thanks in advance
Nico

[mito_assignment.logfile.log](https://github.com/matsim-org/matsim-code-examples/files/2663857/mito_assignment.logfile.log)

2018-12-10 16:46:34,587 ERROR SimStepParallelEventsManagerImpl$ExceptionHandler:420 Thread class org.matsim.core.events.SimStepParallelEventsManagerImpl$ProcessEventsRunnable4 died with exception while handling events.
java.lang.RuntimeException: problem invoking EventHandler org.matsim.core.events.algorithms.Vehicle2DriverEventHandler for event-class org.matsim.api.core.v01.events.VehicleLeavesTrafficEvent
	at org.matsim.core.events.EventsManagerImpl.computeEvent(EventsManagerImpl.java:230)
	at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:136)
	at org.matsim.core.events.SimStepParallelEventsManagerImpl$ProcessEventsRunnable.run(SimStepParallelEventsManagerImpl.java:330)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
	at java.util.HashMap$TreeNode.removeTreeNode(HashMap.java:2029)
	at java.util.HashMap.removeNode(HashMap.java:839)
	at java.util.HashMap.remove(HashMap.java:798)
	at org.matsim.core.events.algorithms.Vehicle2DriverEventHandler.handleEvent(Vehicle2DriverEventHandler.java:57)
	at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.matsim.core.events.EventsManagerImpl.computeEvent(EventsManagerImpl.java:226)
	... 3 more

**Comment by kainagel** [comment]
The real error is normally further up in the logfile.

**Comment by nkuehnel** [comment]
That's what I thought but it is indeed the first occuring exception (see attached logfile)

**Comment by jfbischoff** [comment]
This is a very strange exception, which does not seem to be re-producable. Most likely, if you re-run, the problem will disappear.
That said, it seems to happen from time to time.
@kainagel had some comments the last time someone reported:
https://github.com/matsim-org/matsim-code-examples/wiki/faq-305135621

**Comment by kainagel** [comment]
Ah thanks.  Yes this may indeed be a concurrency issue.  :-(. I changed the offending data structure to `ConcurrentHashmap`, but as usual it will take time until it has moved through the pull request.

Sorry ...

**Comment by nkuehnel** [comment]
I see. Thank you, I'll just run  it again and hope it goes well :)
