### ISSUE TITLE
error while using GTFS2MATSim 

### ISSUE THREAD

**Issue by elyh1992** [matsim-org/matsim-code-examples#488]
Hi,

I am running RunGTFS2MATSimExample to convert GTFS data to transit schedule and network but I get this error:

Exception in thread "main" java.lang.IllegalArgumentException: There is already a departure with id copied-24h_1695.T0.3-1-mjp-1.2.H in transit route 1---3-1-mjp-1_22
	at org.matsim.pt.transitSchedule.TransitRouteImpl.addDeparture(TransitRouteImpl.java:96)
	at org.matsim.contrib.gtfs.TransitSchedulePostProcessTools.copyLateDeparturesToStartOfDay(TransitSchedulePostProcessTools.java:77)
	at org.matsim.contrib.gtfs.RunGTFS2MATSimExample.main(RunGTFS2MATSimExample.java:70)

I want to know what does this error means and what is causing it? Do you have any suggestions on how should I solve it? 

Thank you for your help.

**Comment by vsp-gleich** [comment]
Hi,
it seems someone copied some post-processing steps from RunGTFS2MATSimExample to RunGTFS2MATSim, so they were run twice leading to the same id used twice which caused the error message. I deleted these post-processing steps in RunGTFS2MATSimExample.

**Comment by elyh1992** [comment]
Thank you. It is working now.
