### ISSUE TITLE
Matsim as a plugin to my Spring application

### ISSUE THREAD

**Issue by miilljana** [matsim-org/matsim-code-examples#509]
Hi everyone
I'm using matsim as a plugin to my Spring application, and getting this error from the Logger class:

```
Exception in thread "main" java.lang.ClassCastException: class org.apache.logging.slf4j.SLF4JLoggerContext cannot be cast to class org.apache.logging.log4j.core.LoggerContext (org.apache.logging.slf4j.SLF4JLoggerContext and org.apache.logging.log4j.core.LoggerContext are in unnamed module of loader 'app')
	at org.matsim.core.controler.OutputDirectoryLogging.initLogging(OutputDirectoryLogging.java:128)
	at org.matsim.core.controler.OutputDirectoryLogging.initLogging(OutputDirectoryLogging.java:96)
	at org.matsim.core.controler.AbstractController.setupOutputDirectory(AbstractController.java:68)
	at org.matsim.core.controler.NewControler.run(NewControler.java:81)
	at org.matsim.core.controler.Controler.run(Controler.java:249)
	at com.example.demoMatsim.RunMatSIm.main(RunMatSIm.java:21)
```
Do you have ay ideas? Thank you!

**Comment by dirkbolte** [comment]
I stumbled across this issue while looking for the same error message in a different context (without this plugin) but my fix might help for you as well.

The issue (in my case) is that Spring finds both Log4J as well as SLF4J on the class path and thus cannot decide which one to load. In my case, I want to use SLF4J, so I have to exclude the other one from the class path by excluding it from every dependency. In gradle (Kotlin), you can do it like this:

```kotlin
configurations {
    all {
        exclude(group = "org.apache.logging.log4j", module = "log4j-core")
    }
}
```

From what I see, you should only exclude the core package as `log4j-to-slf4j` is in the same group and that one is needed for libraries which use Log4J to work with SLF4J.

**Comment by RydAlex** [comment]
If you run it in with spring boot you can always exclude logging directly from the spring boot module:

```
implementation('org.springframework.boot:spring-boot-starter-web'){
        exclude module: "spring-boot-starter-logging"
}
```
