### ISSUE TITLE
Problem when trying the dvrp example. 

### ISSUE THREAD

**Issue by HawkTom** [matsim-org/matsim-code-examples#511]
Hello.

I am a brand new user and trying the dvrp example in the latest version of MATSim (12.0). I run the MATSim in the IDE (IntellJ). 

When I load the config file `generic_dvrp_one_taxi_config.xml` and start the MATSim, it raised up the error:
```
2021-01-13 16:47:39,812  INFO ControlerUtils:63 Complete config dump done.
2021-01-13 16:47:39,812  INFO ControlerUtils:64 Checking consistency of config...
2021-01-13 16:47:39,812  INFO PlanCalcScoreConfigGroup$ScoringParameterSet:1485 NO OPENING OR CLOSING TIMES DEFINED!

There is no activity type that has an opening *and* closing time (or opening time and late penalty) defined.
This usually means that the activity chains can be shifted by an arbitrary
number of hours without having an effect on the score of the plans, and thus
resulting in wrong results / traffic patterns.
If you are using MATSim without time adaptation, you can ignore this warning.


2021-01-13 16:47:39,812  INFO VspConfigConsistencyCheckerImpl:58 NOT running vsp config consistency check because vsp defaults checking level is set to IGNORE
2021-01-13 16:47:39,816  INFO MatsimRuntimeModifications:79 S H U T D O W N   ---   start shutdown.
2021-01-13 16:47:39,816  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.EventsHandlingImpl
2021-01-13 16:47:39,816  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.DumpDataAtEndImpl
2021-01-13 16:47:39,817  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ModeStatsControlerListener
2021-01-13 16:47:39,817  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ScoreStatsControlerListener
2021-01-13 16:47:39,817  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.TravelDistanceStatsControlerListener
2021-01-13 16:47:40,387  INFO ControlerListenerManagerImpl:129 all ControlerShutdownListeners called.2021-01-13 16:47:40,387 ERROR MatsimRuntimeModifications:99 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2021-01-13 16:47:40,387  INFO MatsimRuntimeModifications:102 S H U T D O W N   ---   shutdown completed.

2021-01-13 16:47:40,387 ERROR MatsimRuntimeModifications:100 ERROR --- results should not be used for further analysis.
2021-01-13 16:47:40,387 ERROR MatsimRuntimeModifications:104 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
Exception in thread "main" java.lang.RuntimeException: Unmaterialized config group: otfvis
	at org.matsim.core.config.consistency.UnmaterializedConfigGroupChecker.checkConsistency(UnmaterializedConfigGroupChecker.java:32)
	at org.matsim.core.config.Config.checkConsistency(Config.java:225)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:65)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:78)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.project.RunMatsim.main(RunMatsim.java:63)

The simulation did not run properly. Error/Exit code: 1
```
I think it might be the problem of the visualization by OTFVI, so I comment the lines in the `config.xml`:
```
<module name="otfvis">
		<param name="coloringScheme" value="taxicab"/>
		<param name="drawNonMovingItems" value="true"/>
	</module>
```
but it still doesn't work. The errorlog is:
```
2021-01-13 16:50:52,105  INFO ControlerUtils:63 Complete config dump done.
2021-01-13 16:50:52,105  INFO ControlerUtils:64 Checking consistency of config...
2021-01-13 16:50:52,105  INFO PlanCalcScoreConfigGroup$ScoringParameterSet:1485 NO OPENING OR CLOSING TIMES DEFINED!

There is no activity type that has an opening *and* closing time (or opening time and late penalty) defined.
This usually means that the activity chains can be shifted by an arbitrary
number of hours without having an effect on the score of the plans, and thus
resulting in wrong results / traffic patterns.
If you are using MATSim without time adaptation, you can ignore this warning.


2021-01-13 16:50:52,106  INFO VspConfigConsistencyCheckerImpl:58 NOT running vsp config consistency check because vsp defaults checking level is set to IGNORE
2021-01-13 16:50:52,109  INFO ControlerUtils:66 Checking consistency of config done.
2021-01-13 16:50:52,110  INFO Counter:69 [VehiclesImpl] added vehicle # 1
2021-01-13 16:50:52,110  INFO Counter:69 [VehiclesImpl] added vehicle # 2
2021-01-13 16:50:52,110  INFO Counter:69 [VehiclesImpl] added vehicle # 4
2021-01-13 16:50:52,110  INFO Counter:69 [VehiclesImpl] added vehicle # 8
2021-01-13 16:50:52,117  INFO Counter:74 [PersonPrepareForSim] handled person # 0
2021-01-13 16:50:52,117  INFO MatsimRuntimeModifications:79 S H U T D O W N   ---   start shutdown.
2021-01-13 16:50:52,118  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.EventsHandlingImpl
2021-01-13 16:50:52,118  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.DumpDataAtEndImpl
2021-01-13 16:50:52,118  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ModeStatsControlerListener
2021-01-13 16:50:52,118  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ScoreStatsControlerListener
2021-01-13 16:50:52,118  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.TravelDistanceStatsControlerListener

	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:216)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:90)
	at org.matsim.core.population.algorithms.PersonPrepareForSim.run(PersonPrepareForSim.java:177)
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils$PersonAlgoThread.run(ParallelPersonAlgorithmUtils.java:145)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-13 16:50:52,116 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.1 died with exception while handling events.
org.matsim.core.router.TripRouter$UnknownModeException: unregistered main mode |taxi|: does not pertain to [pt, car, non_network_walk, ride, walk, bike]
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:216)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:90)
	at org.matsim.core.population.algorithms.PersonPrepareForSim.run(PersonPrepareForSim.java:177)
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils$PersonAlgoThread.run(ParallelPersonAlgorithmUtils.java:145)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-13 16:50:52,117 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
java.lang.RuntimeException: Exception while processing persons. Cannot guarantee that all persons have been fully processed.
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils.run(ParallelPersonAlgorithmUtils.java:120)
	at org.matsim.core.controler.PrepareForSimImpl.run(PrepareForSimImpl.java:153)
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:115)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:79)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.project.RunMatsim.main(RunMatsim.java:63)
2021-01-13 16:50:52,117 ERROR MatsimRuntimeModifications:81 ERROR --- This is an unexpected shutdown!
2021-01-13 16:50:52,117 ERROR MatsimRuntimeModifications:84 Shutdown possibly caused by the following Exception:
java.lang.RuntimeException: Exception while processing persons. Cannot guarantee that all persons have been fully processed.
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils.run(ParallelPersonAlgorithmUtils.java:120)
	at org.matsim.core.controler.PrepareForSimImpl.run(PrepareForSimImpl.java:153)
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:115)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:79)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.project.RunMatsim.main(RunMatsim.java:63)
2021-01-13 16:50:52,689 ERROR MatsimRuntimeModifications:99 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.2021-01-13 16:50:52,689  INFO ControlerListenerManagerImpl:129 all ControlerShutdownListeners called.
2021-01-13 16:50:52,689  INFO MatsimRuntimeModifications:102 S H U T D O W N   ---   shutdown completed.

2021-01-13 16:50:52,689 ERROR MatsimRuntimeModifications:100 ERROR --- results should not be used for further analysis.
2021-01-13 16:50:52,689 ERROR MatsimRuntimeModifications:104 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
Exception in thread "main" java.lang.RuntimeException: Exception while processing persons. Cannot guarantee that all persons have been fully processed.
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils.run(ParallelPersonAlgorithmUtils.java:120)
	at org.matsim.core.controler.PrepareForSimImpl.run(PrepareForSimImpl.java:153)
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:115)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:79)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.project.RunMatsim.main(RunMatsim.java:63)

The simulation did not run properly. Error/Exit code: 1
```

May I ask what's the problem of the MATSim or the the config file?  Thanks,

Best,
Hao

**Comment by michalmac** [comment]
https://github.com/matsim-org/matsim-maas contains examples that you can run. Maybe try start from there and later adapt to your needs?

**Comment by HawkTom** [comment]
> https://github.com/matsim-org/matsim-maas contains examples that you can run. Maybe try start from there and later adapt to your needs?

Hello michalmac,

Thanks for your reply.  

Actually, the above error was raised when I try the example in https://github.com/matsim-org/matsim-maas. 

Best, 
Hao

**Comment by michalmac** [comment]
From the stack trace I see you are not running it from matsim-maas. Moreover, matsim-maas uses MATSim snapshot version (not 12.0). Can you double check?
