### ISSUE TITLE
HAFAS data is not interpretable by hafas2transitschedule

### ISSUE THREAD

**Issue by Alnik89** [matsim-org/matsim-code-examples#513]
Hi everyone,
in my current thesis, i am trying to implement a matsim model of a model region in schleswig holstein.
Since i want to include the only bus line of the model region into the matsim model i asked the transport operator for the corresponding hafas data.
Although the data correspond to the required format at first glance, they do not seem to be interpretable by hafas2transitschedule.
Pls find received data attached below.
Is there a possibility to adjust the data?
or
What do i have to consider with my inquiry in order to receive interpretable data?

In advance,
Many thanks for any help! 
Kind regards
Alexander

[HAFAS.zip](https://github.com/matsim-org/matsim-code-examples/files/5835618/HAFAS.zip)

**Comment by mrieser** [comment]
Did you get an error message or exception? What does it state?

**Comment by Alnik89** [comment]
attached the error message.
Unfortunately a bit deep for my minimal understanding of the functioning.

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.matsim.pt2matsim.hafas.lib.OperatorReader.readOperators(OperatorReader.java:43)
	at org.matsim.pt2matsim.hafas.HafasConverter.run(HafasConverter.java:102)
	at org.matsim.pt2matsim.hafas.HafasConverter.run(HafasConverter.java:57)
	at org.matsim.pt2matsim.run.HafasTransitSchedule.main(HafasTransitSchedule.java:47)

**Comment by Alnik89** [comment]
It dies with the Read operators
2021-01-19 13:29:25,880  INFO StopReader:89   Read transit stops... done.
2021-01-19 13:29:25,880  INFO HafasConverter:93   Read transit stops... done.
2021-01-19 13:29:25,880  INFO HafasConverter:96   Read minimal transfer times...
2021-01-19 13:29:25,881  INFO MinimalTransferTimesReader:43    UMSTEIGB does not exist!
2021-01-19 13:29:25,882  INFO MinimalTransferTimesReader:71    METABHF does not exist!
2021-01-19 13:29:25,882  INFO HafasConverter:98   Read minimal transfer times... done.
2021-01-19 13:29:25,882  INFO HafasConverter:101   Read operators...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException:

**Comment by mrieser** [comment]
I tried running it with the provided data, for me it already fails before with:

> ERROR ECKDATENReader:40     ECKDATEN does not exist!

Looking at the code and your exception, there seems to be a problem with reading the operators data (file `BETRIEB_DE`), most likely with the last line, as it does not contain any `"` character that the code expects. Not sure how to proceed. Maybe it works if you just delete that line, maybe you have to modify that line somehow that it looks more like the lines before, and ultimately try to fix the code of pt2matsim...

**Comment by Alnik89** [comment]
After manually adjusting the hafas data, I have now managed to process them with hafas2transitschedule.
**The crucial adjustments are:**

**The Z-rows in file FPLAN should look like:**
_*Z 26141 000072   001                                     % -- 26141 --_
while:
- The *Z row contains data from a new trip [**fix Char**]. Every trip starts with the *Z row.
- 26141 is the number of the transit route [**adapt to your own data**]
- 000072 descripes a handle(to file FPLAN) [**fix Char**]
- 001 counter for vehicle Ref. ID [**fix Char**]

**Based on the handle the file BETRIEB_DE should look like:**
_00343 K "DRN" L "DRN" V "DB Regio Bus Nord GmbH"
00343 : 000072_
while:
- "DRN" and "DB Regio Bus Nord GmbH" references the transit operator [**adapt to your own data**]
- 00343 and 000072 are handles [**fix Char**]
