### ISSUE TITLE
Error while iteration tries to use TransitQSimEngine.handleDeparture(TransitQSimEngine)

### ISSUE THREAD

**Issue by vsgo222** [matsim-org/matsim-code-examples#515]
[output_HighPTRdrshp_BusLane.zip](https://github.com/matsim-org/matsim-code-examples/files/5863974/output_HighPTRdrshp_BusLane.zip)
Hello all,
I am trying to introduce bus lanes + increased number of services on identified PT routes. For this I update the transitSchedule, transitVehicle and Roadnetwork files with original plans file used for this re-run. 
When I try to rerun MATSim using this updated files, it keeps shutting down and gives following error message

```
 java.lang.NullPointerException: null
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.handleAgentPTDeparture(TransitQSimEngine.java:179) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.handleDeparture(TransitQSimEngine.java:193) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.arrangeAgentDeparture(QSim.java:493) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.arrangeNextAgentAction(QSim.java:455) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim$1.arrangeNextAgentState(QSim.java:162) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.ActivityEngineDefaultImpl.handleActivity(ActivityEngineDefaultImpl.java:154) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.arrangeAgentActivity(QSim.java:474) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.arrangeNextAgentAction(QSim.java:452) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim$1.arrangeNextAgentState(QSim.java:162) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.DefaultTeleportationEngine.handleTeleportationArrivals(DefaultTeleportationEngine.java:146) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.DefaultTeleportationEngine.doSimStep(DefaultTeleportationEngine.java:131) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.doSimStep(QSim.java:408) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:267) ~[classes/:?]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124) ~[classes/:?]
	at org.matsim.core.controler.AbstractController$9.run(AbstractController.java:211) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:243) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:207) [classes/:?]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154) [classes/:?]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121) [classes/:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:81) [classes/:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [classes/:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [classes/:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89) [classes/:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [classes/:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [classes/:?]
	at org.matsim.run.Controler.run(Controler.java:59) [classes/:?]
	at org.matsim.run.Controler.main(Controler.java:63) [classes/:?]
2021-01-24T21:55:22,758  INFO AbstractController$6:234 ### ITERATION 0 fires after mobsim event
2021-01-24T21:55:22,758  INFO ControlerListenerManagerImpl:248 calling notifyAfterMobsim on org.matsim.analysis.LegTimesControlerListener
2021-01-24T21:55:22,759  INFO LegTimesControlerListener:50 [0] average trip (probably: leg) duration is: 554 seconds = 00:09:14
2021-01-24T21:55:22,759  INFO ControlerListenerManagerImpl:248 calling notifyAfterMobsim on org.matsim.core.events.MobsimScopeEventHandling
2021-01-24T21:55:22,761  INFO ControlerListenerManagerImpl:248 calling notifyAfterMobsim on org.matsim.core.scoring.EventsToActivities$1
2021-01-24T21:55:22,763  WARN CharyparNagelActivityScoring:246 The first and the last activity do not have the same type. 
2021-01-24T21:55:22,763  WARN CharyparNagelActivityScoring:247 Will score the first activity from midnight to its end, and the last activity from its start to midnight.
[output_HighPTRdrshp_BusLane.zip](https://github.com/matsim-org/matsim-code-examples/files/5863953/output_HighPTRdrshp_BusLane.zip)


2021-01-24T21:55:22,763  WARN CharyparNagelActivityScoring:248 Because of the nonlinear function, this is not the same as scoring from start to end.
2021-01-24T21:55:22,764  WARN CharyparNagelActivityScoring:249 first activity: act [type=Home][coord=null][linkId=104633097_F][startTime=undefined][endTime=03:36:45][duration=undefined][facilityId=13013180104_2015000417896_1842]
2021-01-24T21:55:22,764  WARN CharyparNagelActivityScoring:250 last activity: act [type=Work][coord=[x=728862.8747953124 | y=462124.76513543003]][linkId=104619764_F][startTime=04:00:56][endTime=undefined][duration=undefined][facilityId=F131390016032001]
2021-01-24T21:55:22,764  WARN CharyparNagelActivityScoring:251 This may also happen when plans are not completed when the simulation ends.
2021-01-24T21:55:22,764  WARN CharyparNagelActivityScoring:253 Additional warnings of this type are suppressed.
2021-01-24T21:55:22,789  INFO ControlerListenerManagerImpl:251 [it.0] all ControlerAfterMobsimListeners called.
2021-01-24T21:55:22,789 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
java.lang.NullPointerException: null
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.handleAgentPTDeparture(TransitQSimEngine.java:179) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.handleDeparture(TransitQSimEngine.java:193) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.arrangeAgentDeparture(QSim.java:493) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.arrangeNextAgentAction(QSim.java:455) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim$1.arrangeNextAgentState(QSim.java:162) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.ActivityEngineDefaultImpl.handleActivity(ActivityEngineDefaultImpl.java:154) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.arrangeAgentActivity(QSim.java:474) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.arrangeNextAgentAction(QSim.java:452) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim$1.arrangeNextAgentState(QSim.java:162) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.DefaultTeleportationEngine.handleTeleportationArrivals(DefaultTeleportationEngine.java:146) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.DefaultTeleportationEngine.doSimStep(DefaultTeleportationEngine.java:131) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.doSimStep(QSim.java:408) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:267) ~[classes/:?]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124) ~[classes/:?]
	at org.matsim.core.controler.AbstractController$9.run(AbstractController.java:211) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:243) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:207) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121) ~[classes/:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:81) ~[classes/:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [classes/:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [classes/:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89) [classes/:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [classes/:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [classes/:?]
	at org.matsim.run.Controler.run(Controler.java:59) [classes/:?]
	at org.matsim.run.Controler.main(Controler.java:63) [classes/:?]
2021-01-24T21:55:22,790  INFO MatsimRuntimeModifications:79 S H U T D O W N   ---   start shutdown.
2021-01-24T21:55:22,790 ERROR MatsimRuntimeModifications:81 ERROR --- This is an unexpected shutdown!
2021-01-24T21:55:22,790 ERROR MatsimRuntimeModifications:84 Shutdown possibly caused by the following Exception:
java.lang.NullPointerException: null
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.handleAgentPTDeparture(TransitQSimEngine.java:179) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.handleDeparture(TransitQSimEngine.java:193) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.arrangeAgentDeparture(QSim.java:493) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.arrangeNextAgentAction(QSim.java:455) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim$1.arrangeNextAgentState(QSim.java:162) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.ActivityEngineDefaultImpl.handleActivity(ActivityEngineDefaultImpl.java:154) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.arrangeAgentActivity(QSim.java:474) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.arrangeNextAgentAction(QSim.java:452) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim$1.arrangeNextAgentState(QSim.java:162) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.DefaultTeleportationEngine.handleTeleportationArrivals(DefaultTeleportationEngine.java:146) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.DefaultTeleportationEngine.doSimStep(DefaultTeleportationEngine.java:131) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.doSimStep(QSim.java:408) ~[classes/:?]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:267) ~[classes/:?]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124) ~[classes/:?]
	at org.matsim.core.controler.AbstractController$9.run(AbstractController.java:211) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:243) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:207) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154) ~[classes/:?]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121) ~[classes/:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:81) ~[classes/:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [classes/:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [classes/:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89) [classes/:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [classes/:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [classes/:?]
	at org.matsim.run.Controler.run(Controler.java:59) [classes/:?]
	at org.matsim.run.Controler.main(Controler.java:63) [classes/:?]
2021-01-24T21:55:22,791  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.EventsHandlingImpl
2021-01-24T21:55:22,793  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.DumpDataAtEndImpl
2021-01-24T21:55:22,793  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ScoreStatsControlerListener
2021-01-24T21:55:22,794  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.IterationTravelStatsControlerListener
2021-01-24T21:55:22,795  INFO IterationTravelStatsControlerListener:104 Writing all Person and Attributes to personscsv
2021-01-24T21:55:31,821  INFO IterationTravelStatsControlerListener:148 ...done
2021-01-24T21:55:31,821  INFO ControlerListenerManagerImpl:129 all ControlerShutdownListeners called.
2021-01-24T21:55:31,821 ERROR MatsimRuntimeModifications:99 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2021-01-24T21:55:31,821 ERROR MatsimRuntimeModifications:100 ERROR --- results should not be used for further analysis.
2021-01-24T21:55:31,821  INFO MatsimRuntimeModifications:102 S H U T D O W N   ---   shutdown completed.
2021-01-24T21:55:31,821 ERROR MatsimRuntimeModifications:104 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
```
Initially I thought error is on my way of configuring these dependent files but it seems running fine when I iterate using small number of agents (I tested 10,000 agents). Also the base case with same plan file successfully completes 50 iterations as desired keeping other setting parameters constant. 
I also attach the error-log file for you ready reference. I would be grateful, if someone guides me or pinpoints what might be the case here. 

Thank you
Vedant, @gregerhardt

**Comment by vsp-gleich** [comment]
Some idea: I think you might have an issue with link ids. Probably you implemented the bus lane by adding a new link and moved the bus route and the TransitStopFacility to the new (bus lane) link. However, if you use the original plans file with routes on the old network and on the old transit schedule, agents will walk to the link where the bus operated before and not to the bus lane link. This obviously does not work. Maybe it worked with 10 000 agents, because for some reason only those agents were selected who did not use the bus on the new bus lane.

**Comment by mrieser** [comment]
Not sure what MATSim version you use. In the current code, `TransitQSimEngine` line 179 refers to this line:

    if (stop.getLinkId() == null || stop.getLinkId().equals(linkId)) {

~~A null pointer could happen here when a transit stop has no link assigned.~~
~~Assuming this is also the correct line in your code that you use, I would check your schedule if every stop has a valid link id. Not sure, but likely the `TransitScheduleValidator` checks this as well, so that's worth a try as well.~~

---

Edit: hmm, no, if the linkId is null, then the if-statement should actually not go to the second part... So please check with your code.

Okay, so probably `stop` is null if it's the correct line. `stop` comes from the line above:

    TransitStopFacility stop = this.schedule.getFacilities().get(accessStopId);

So, probably an agent tries to go to a transit stop that no longer exists?

Also, newer Java versions (Java 14 and up) provide additional details when a NullPointerException occurs, pinpointing the exact variable accesses that was null. This might help you further as well to figure out where the problem is.

**Comment by vsgo222** [comment]
> 
> 
> Some idea: I think you might have an issue with link ids. Probably you implemented the bus lane by adding a new link and moved the bus route and the TransitStopFacility to the new (bus lane) link. However, if you use the original plans file with routes on the old network and on the old transit schedule, agents will walk to the link where the bus operated before and not to the bus lane link. This obviously does not work. Maybe it worked with 10 000 agents because for some reason only those agents were selected who did not use the bus on the new bus lane.

@vsp-gleich: Yep, indeed it was that way. I had overlapped the link where the bus lane is introduced with a new cloned link. Removed "bus" entry in the "mode" attrib of the original link and introduced the same in the new cloned link. 

This created a scenario, where the agent start or end their journey on link: x_busway instead of original: x after I tracked  
```
public boolean handleDeparture 
private void handleAgentPTDeparture 
```
and were also highlighted by @mrieser. 

Keeping "bus" both in original and cloned link along with updating the minimal transfer section of the transitSchedule.xml seems to have resolved the error. The agent still starts/ends the journey at x_busway but I think MATSim internally resolves to let the journey terminate. 


Thank you
Vedant
