### ISSUE TITLE
Using matsim ruhrgebiet with the UAM Extension

### ISSUE THREAD

**Issue by tnt456** [matsim-org/matsim-code-examples#516]
Hello, I am trying to simulate the MATSim Ruhrgebiet Scenario and on itself that works, but when I try to use the UAM Extension in the Ruhrgebiet Scenario it does not work, the Problem i got, is that the UAM Extension is written with the MATSim v11 Core whilst the Ruhrgebiet Scenario is written with MATSim v12. I got the impression, that in the dvrp package there have been some changes between v11 and v12. I tried to update a Version of the UAM Extension so that it would use MATSim v12 but i couldn't get it to work. The Code in which i tried it is here: https://github.com/tnt456/MATSimUAMver12 and the inclusion in the Ruhrgebiet Scenario is here: https://github.com/tnt456/MATSimRWTH. 

During this approach the error occurs while computing the next actions of UAM vehicles. The Stack Trace is :

```
2020-12-17T16:30:42,977  INFO VehicleUtils:328 adding scenario element for allvehicles container
2020-12-17T16:30:42,977  INFO Counter:69 [VehiclesImpl] added vehicle # 1
2020-12-17T16:30:42,977  INFO Counter:69 [VehiclesImpl] added vehicle # 2
2020-12-17T16:30:42,977  INFO Counter:69 [VehiclesImpl] added vehicle # 4
2020-12-17T16:30:42,977  INFO Counter:69 [VehiclesImpl] added vehicle # 8
2020-12-17T16:30:42,978  INFO Counter:69 [VehiclesImpl] added vehicle # 16
2020-12-17T16:30:42,978  INFO Counter:69 [VehiclesImpl] added vehicle # 32
2020-12-17T16:30:42,979  INFO Counter:69 [VehiclesImpl] added vehicle # 64
2020-12-17T16:30:42,979  INFO Counter:69 [VehiclesImpl] added vehicle # 128
2020-12-17T16:30:42,981  INFO Counter:69 [VehiclesImpl] added vehicle # 256
2020-12-17T16:30:42,984  INFO Counter:69 [VehiclesImpl] added vehicle # 512
2020-12-17T16:30:42,990  INFO Counter:69 [VehiclesImpl] added vehicle # 1024
2020-12-17T16:30:43,002  INFO Counter:69 [VehiclesImpl] added vehicle # 2048
2020-12-17T16:30:43,030  INFO Counter:69 [VehiclesImpl] added vehicle # 4096
2020-12-17T16:30:43,084  INFO Counter:69 [VehiclesImpl] added vehicle # 8192
2020-12-17T16:30:43,201  INFO Counter:69 [VehiclesImpl] added vehicle # 16384
2020-12-17T16:30:43,303  INFO ReconstructingUmlaufBuilder:132 Generating UmlaufStuecke ...
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
.........................2020-12-17T16:30:43,326  INFO ReconstructingUmlaufBuilder:145 ... done generating UmlaufStuecke
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
....................................................................................................
.........................2020-12-17T16:30:43,823  INFO Counter:69 [VehiclesImpl] added vehicle # 32768
2020-12-17T16:30:43,969  INFO Counter:69 [VehiclesImpl] added vehicle # 65536
2020-12-17T16:30:44,490  INFO AbstractQNetsimEngine:427 Assigned 302406 nodes and 625553 links to QSimEngineRunner #0
2020-12-17T16:30:44,624  INFO EventsManagerImpl:135  event # 1
2020-12-17T16:30:44,626  INFO EventsManagerImpl:135  event # 4
2020-12-17T16:30:44,626  INFO EventsManagerImpl:158 adding Event-Handler: net.bhl.matsim.uam.events.UAMPrebookVehicle
2020-12-17T16:30:44,626  INFO EventsManagerImpl:162   org.matsim.api.core.v01.events.handler.PersonDepartureEventHandler
2020-12-17T16:30:44,626  INFO EventsManagerImpl:221     > org.matsim.api.core.v01.events.PersonDepartureEvent
2020-12-17T16:30:44,626  INFO EventsManagerImpl:170 
2020-12-17T16:30:44,626  INFO EventsManagerImpl:135  event # 16
2020-12-17T16:30:44,626  INFO EventsManagerImpl:158 adding Event-Handler: net.bhl.matsim.uam.events.UAMPrebookVehicle
2020-12-17T16:30:44,626  INFO EventsManagerImpl:162   org.matsim.api.core.v01.events.handler.PersonDepartureEventHandler
2020-12-17T16:30:44,626  INFO EventsManagerImpl:221     > org.matsim.api.core.v01.events.PersonDepartureEvent
2020-12-17T16:30:44,626  INFO EventsManagerImpl:170 
2020-12-17T16:30:44,628  INFO EventsManagerImpl:135  event # 64
2020-12-17T16:30:44,665  INFO AbstractQNetsimEngine:365 SIMULATION (QNetsimEngine) AT 00:00:00 : #links=11 #nodes=11
2020-12-17T16:30:44,669  INFO QSim:549 SIMULATION (NEW QSim) AT 00:00:00 : #Veh=112975 lost=0 simT=0.0s realT=3s; (s/r): 0.0
2020-12-17T16:30:44,730  INFO EventsManagerImpl:135  event # 256
2020-12-17T16:30:44,735  INFO EventsManagerImpl:135  event # 1024
2020-12-17T16:30:44,749  INFO EventsManagerImpl:135  event # 4096
2020-12-17T16:30:44,796  INFO EventsManagerImpl:135  event # 16384
2020-12-17T16:30:44,958  INFO EventsManagerImpl:135  event # 65536
2020-12-17T16:30:45,288  INFO Gbl:191 Thread performance: Thread=class org.matsim.core.events.SimStepParallelEventsManagerImpl$ProcessEventsRunnable0  cpu-time=0.319844649sec
2020-12-17T16:30:45,287 ERROR AbstractController:209 Mobsim did not complete normally! afterMobsimListeners will be called anyway.
java.lang.IllegalStateException: A UAM schedule should never end!
	at net.bhl.matsim.uam.schedule.UAMOptimizer.nextTask(UAMOptimizer.java:68) ~[matsim-uam-2.1.jar:?]
	at org.matsim.contrib.dvrp.vrpagent.VrpAgentLogic.computeNextAction(VrpAgentLogic.java:74) ~[dvrp-12.0.jar:?]
	at org.matsim.contrib.dynagent.DynAgent.computeNextAction(DynAgent.java:83) ~[dvrp-12.0.jar:?]
	at org.matsim.contrib.dynagent.DynAgent.endActivityAndComputeNextState(DynAgent.java:98) ~[dvrp-12.0.jar:?]
	at org.matsim.core.mobsim.qsim.ActivityEngineDefaultImpl.doSimStep(ActivityEngineDefaultImpl.java:107) ~[matsim-12.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.doSimStep(QSim.java:408) ~[matsim-12.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:267) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:198) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:230) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:194) [matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:145) [matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:113) [matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80) [matsim-12.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-12.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88) [matsim-12.0.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-12.0.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-12.0.jar:?]
	at org.matsim.ruhrgebiet.run.RunRuhrgebietScenario.main(RunRuhrgebietScenario.java:84) [matsim-ruhrgebiet-1.1.x-SNAPSHOT.jar:?]
2020-12-17T16:30:45,292  INFO AbstractController$9:221 ### ITERATION 0 fires after mobsim event
2020-12-17T16:30:45,292  INFO ControlerListenerManagerImpl:248 calling notifyAfterMobsim on org.matsim.analysis.LegTimesControlerListener
2020-12-17T16:30:45,303  INFO LegTimesControlerListener:50 [0] average trip (probably: leg) duration is: 0 seconds = 00:00:00
2020-12-17T16:30:45,303  INFO ControlerListenerManagerImpl:248 calling notifyAfterMobsim on org.matsim.core.scoring.EventsToActivities$1
2020-12-17T16:30:45,305  INFO ControlerListenerManagerImpl:251 [it.0] all ControlerAfterMobsimListeners called.
2020-12-17T16:30:45,305 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
java.lang.IllegalStateException: A UAM schedule should never end!
	at net.bhl.matsim.uam.schedule.UAMOptimizer.nextTask(UAMOptimizer.java:68) ~[matsim-uam-2.1.jar:?]
	at org.matsim.contrib.dvrp.vrpagent.VrpAgentLogic.computeNextAction(VrpAgentLogic.java:74) ~[dvrp-12.0.jar:?]
	at org.matsim.contrib.dynagent.DynAgent.computeNextAction(DynAgent.java:83) ~[dvrp-12.0.jar:?]
	at org.matsim.contrib.dynagent.DynAgent.endActivityAndComputeNextState(DynAgent.java:98) ~[dvrp-12.0.jar:?]
	at org.matsim.core.mobsim.qsim.ActivityEngineDefaultImpl.doSimStep(ActivityEngineDefaultImpl.java:107) ~[matsim-12.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.doSimStep(QSim.java:408) ~[matsim-12.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:267) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:198) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:230) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:194) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:145) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:113) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-12.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88) [matsim-12.0.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-12.0.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-12.0.jar:?]
	at org.matsim.ruhrgebiet.run.RunRuhrgebietScenario.main(RunRuhrgebietScenario.java:84) [matsim-ruhrgebiet-1.1.x-SNAPSHOT.jar:?]
2020-12-17T16:30:45,306  INFO MatsimRuntimeModifications:79 S H U T D O W N   ---   start shutdown.
2020-12-17T16:30:45,306 ERROR MatsimRuntimeModifications:81 ERROR --- This is an unexpected shutdown!
2020-12-17T16:30:45,306 ERROR MatsimRuntimeModifications:84 Shutdown possibly caused by the following Exception:
java.lang.IllegalStateException: A UAM schedule should never end!
	at net.bhl.matsim.uam.schedule.UAMOptimizer.nextTask(UAMOptimizer.java:68) ~[matsim-uam-2.1.jar:?]
	at org.matsim.contrib.dvrp.vrpagent.VrpAgentLogic.computeNextAction(VrpAgentLogic.java:74) ~[dvrp-12.0.jar:?]
	at org.matsim.contrib.dynagent.DynAgent.computeNextAction(DynAgent.java:83) ~[dvrp-12.0.jar:?]
	at org.matsim.contrib.dynagent.DynAgent.endActivityAndComputeNextState(DynAgent.java:98) ~[dvrp-12.0.jar:?]
	at org.matsim.core.mobsim.qsim.ActivityEngineDefaultImpl.doSimStep(ActivityEngineDefaultImpl.java:107) ~[matsim-12.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.doSimStep(QSim.java:408) ~[matsim-12.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:267) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:198) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:230) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:194) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:145) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:113) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80) ~[matsim-12.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-12.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-12.0.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88) [matsim-12.0.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-12.0.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-12.0.jar:?]
	at org.matsim.ruhrgebiet.run.RunRuhrgebietScenario.main(RunRuhrgebietScenario.java:84) [matsim-ruhrgebiet-1.1.x-SNAPSHOT.jar:?]
2020-12-17T16:30:45,306  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.EventsHandlingImpl
2020-12-17T16:30:45,307  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.DumpDataAtEndImpl
2020-12-17T16:30:45,307  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ModeStatsControlerListener
2020-12-17T16:30:45,308  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ScoreStatsControlerListener
2020-12-17T16:30:45,309  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.IterationTravelStatsControlerListener
2020-12-17T16:30:48,466  INFO IterationTravelStatsControlerListener:100 Writing all Person and Attributes to personscsv
2020-12-17T16:30:49,011  INFO IterationTravelStatsControlerListener:134 ...done
2020-12-17T16:30:49,012  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on net.bhl.matsim.uam.listeners.ParallelLeastCostPathCalculatorShutdownListener
2020-12-17T16:30:49,012  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on net.bhl.matsim.uam.listeners.UAMShutdownListener
java.net.MalformedURLException: no protocol: /rwthfs/rz/cluster/hpcwork/rwth0552/uam_vehicles.xml
	at java.base/java.net.URL.<init>(URL.java:645)
	at java.base/java.net.URL.<init>(URL.java:541)
	at java.base/java.net.URL.<init>(URL.java:488)
	at net.bhl.matsim.uam.listeners.UAMShutdownListener.writeUAMVehiclesFile(UAMShutdownListener.java:45)
	at net.bhl.matsim.uam.listeners.UAMShutdownListener.notifyShutdown(UAMShutdownListener.java:32)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerShutdownEvent(ControlerListenerManagerImpl.java:127)
	at org.matsim.core.controler.AbstractController$1.shutdown(AbstractController.java:85)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:87)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:82)
	at org.matsim.core.controler.Controler.run(Controler.java:249)
	at org.matsim.ruhrgebiet.run.RunRuhrgebietScenario.main(RunRuhrgebietScenario.java:84)
2020-12-17T16:30:49,013  INFO ControlerListenerManagerImpl:129 all ControlerShutdownListeners called.
2020-12-17T16:30:49,013 ERROR MatsimRuntimeModifications:99 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2020-12-17T16:30:49,013 ERROR MatsimRuntimeModifications:100 ERROR --- results should not be used for further analysis.
2020-12-17T16:30:49,013  INFO MatsimRuntimeModifications:102 S H U T D O W N   ---   shutdown completed.
2020-12-17T16:30:49,013 ERROR MatsimRuntimeModifications:104 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
Exception in thread "main" java.lang.IllegalStateException: A UAM schedule should never end!
	at net.bhl.matsim.uam.schedule.UAMOptimizer.nextTask(UAMOptimizer.java:68)
	at org.matsim.contrib.dvrp.vrpagent.VrpAgentLogic.computeNextAction(VrpAgentLogic.java:74)
	at org.matsim.contrib.dynagent.DynAgent.computeNextAction(DynAgent.java:83)
	at org.matsim.contrib.dynagent.DynAgent.endActivityAndComputeNextState(DynAgent.java:98)
	at org.matsim.core.mobsim.qsim.ActivityEngineDefaultImpl.doSimStep(ActivityEngineDefaultImpl.java:107)
	at org.matsim.core.mobsim.qsim.QSim.doSimStep(QSim.java:408)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:267)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124)
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:198)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:230)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:194)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:145)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:113)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:82)
	at org.matsim.core.controler.Controler.run(Controler.java:249)
	at org.matsim.ruhrgebiet.run.RunRuhrgebietScenario.main(RunRuhrgebietScenario.java:84)
```

This error occurs even though the only task in the vehicles schedule is an UAM stay task with endtime Infinity. That is why I suspect, that there has been a change in the dvrp or the dynagent package from Version 11 to 12.

Right now I am trying a different approach in which I try to take the Ruhrgebiet Scenario and run it with MATSim 11 so that i can easily get the UAM Extension in to it. Does that seem like a good idea? 

I would be happy about any help or suggestions!!

**Comment by tnt456** [comment]
With the second approach i mentioned above, I now have the Problem, that there are no vehicles in the implementation. 
I used the UAM class RunCreateUAMBeelineScenario to create a scenario with the inputs from the ruhrgebiet scenario but if I try to run it, the scenario gets the vehicle types but no implementation of Vehicles.
Where should it get those from, can anyone help me?

**Comment by balacmi** [comment]
Hi Tobias,

Is this still a valid question and problem? If yes, maybe it would make more sense to post the question on the UAM repo. There is also a number of improvements to the UAM module since you posted this issue, it was also updated to MATSim v12. Maybe this got resolved?
