### ISSUE TITLE
UrbanEV (berlin scenario) ERROR

### ISSUE THREAD

**Issue by applibres** [matsim-org/matsim-code-examples#521]
Hi! I have prepared the configuration for UrbanEV from berlin scenario, but  when I try to run UrbanEVExample, I got this error: 
`
2021-02-03T15:38:30,894  INFO ControlerUtils:84 Complete config dump done.
2021-02-03T15:38:30,894  INFO ControlerUtils:85 Checking consistency of config...
2021-02-03T15:38:30,894  INFO PlanCalcScoreConfigGroup$ScoringParameterSet:1547 NO OPENING OR CLOSING TIMES DEFINED!

There is no activity type that has an opening *and* closing time (or opening time and late penalty) defined.
This usually means that the activity chains can be shifted by an arbitrary
number of hours without having an effect on the score of the plans, and thus
resulting in wrong results / traffic patterns.
If you are using MATSim without time adaptation, you can ignore this warning.

2021-02-03T15:38:30,895  INFO VspConfigConsistencyCheckerImpl:73 running checkConsistency ...
2021-02-03T15:38:30,895  WARN VspConfigConsistencyCheckerImpl:100 you are not using FastAStarLandmarks as routing algorithm.  vsp default is to use FastAStarLandmarks.
2021-02-03T15:38:30,895  WARN VspConfigConsistencyCheckerImpl:247 found `PlansCalcRouteConfigGroup.AccessEgressType.none'; vsp should use `accessEgressModeToLink' or some other value or talk to Kai.
2021-02-03T15:38:30,895  WARN VspConfigConsistencyCheckerImpl:254 found qsim.usePersonIdForMissingVehicleId==true; this is only for backwards compatibility and should rather be set to false
2021-02-03T15:38:30,895  WARN VspConfigConsistencyCheckerImpl:259 found `qsim.usingTravelTimeCheckInTeleporation==false'; vsp should try out `true' and report.
2021-02-03T15:38:30,900  INFO ControlerUtils:87 Checking consistency of config done.
2021-02-03T15:38:30,901 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
java.lang.RuntimeException: Object is null; follow stack trace
	at org.matsim.core.gbl.Gbl.assertNotNull(Gbl.java:209) ~[matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.PrepareForSimImpl.getVehicleTypesForAllNetworkAndMainModes(PrepareForSimImpl.java:258) ~[matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.PrepareForSimImpl.createAndAddVehiclesForEveryNetworkMode(PrepareForSimImpl.java:202) ~[matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.PrepareForSimImpl.run(PrepareForSimImpl.java:164) ~[matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:113) ~[matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80) ~[matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89) [matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.run.ev.RunUrbanEVExample.main(RunUrbanEVExample.java:53) [classes/:?]
2021-02-03T15:38:30,911  INFO MatsimRuntimeModifications:79 S H U T D O W N   ---   start shutdown.
2021-02-03T15:38:30,911 ERROR MatsimRuntimeModifications:81 ERROR --- This is an unexpected shutdown!
2021-02-03T15:38:30,911 ERROR MatsimRuntimeModifications:84 Shutdown possibly caused by the following Exception:
java.lang.RuntimeException: Object is null; follow stack trace
	at org.matsim.core.gbl.Gbl.assertNotNull(Gbl.java:209) ~[matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.PrepareForSimImpl.getVehicleTypesForAllNetworkAndMainModes(PrepareForSimImpl.java:258) ~[matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.PrepareForSimImpl.createAndAddVehiclesForEveryNetworkMode(PrepareForSimImpl.java:202) ~[matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.PrepareForSimImpl.run(PrepareForSimImpl.java:164) ~[matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:113) ~[matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80) ~[matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89) [matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-13.0-SNAPSHOT.jar:?]
	at org.matsim.run.ev.RunUrbanEVExample.main(RunUrbanEVExample.java:53) [classes/:?]
2021-02-03T15:38:30,912  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.EventsHandlingImpl
2021-02-03T15:38:30,912  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.DumpDataAtEndImpl
2021-02-03T15:38:30,912  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ScoreStatsControlerListener
2021-02-03T15:38:30,912  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.IterationTravelStatsControlerListener
2021-02-03T15:38:30,913  INFO IterationTravelStatsControlerListener:104 Writing all Person and Attributes to personscsv
2021-02-03T15:38:30,926  INFO IterationTravelStatsControlerListener:148 ...done
2021-02-03T15:38:30,926  INFO ControlerListenerManagerImpl:129 all ControlerShutdownListeners called.
2021-02-03T15:38:30,926 ERROR MatsimRuntimeModifications:99 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2021-02-03T15:38:30,926 ERROR MatsimRuntimeModifications:100 ERROR --- results should not be used for further analysis.
2021-02-03T15:38:30,926  INFO MatsimRuntimeModifications:102 S H U T D O W N   ---   shutdown completed.
2021-02-03T15:38:30,926 ERROR MatsimRuntimeModifications:104 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
Exception in thread "main" java.lang.RuntimeException: Object is null; follow stack trace
	at org.matsim.core.gbl.Gbl.assertNotNull(Gbl.java:209)
	at org.matsim.core.controler.PrepareForSimImpl.getVehicleTypesForAllNetworkAndMainModes(PrepareForSimImpl.java:258)
	at org.matsim.core.controler.PrepareForSimImpl.createAndAddVehiclesForEveryNetworkMode(PrepareForSimImpl.java:202)
	at org.matsim.core.controler.PrepareForSimImpl.run(PrepareForSimImpl.java:164)
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:113)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89)
	at org.matsim.core.controler.NewControler.run(NewControler.java:82)
	at org.matsim.core.controler.Controler.run(Controler.java:249)
	at org.matsim.run.ev.RunUrbanEVExample.main(RunUrbanEVExample.java:53)
`
Please, could you help us with this issue? 
Thanks.

**Comment by ikaddoura** [comment]
see this thread: https://github.com/matsim-scenarios/matsim-berlin/issues/63
