### ISSUE TITLE
null pointer exception at org.matsim.contrib.minibus.replanning.CreateNewPlan.run

### ISSUE THREAD

**Issue by gammapopolam** [matsim-org/matsim-code-examples#541]
Hi!

I tried to run minibus contribution. 
transitSchedule and transitVehicle file have generated by pt2matsim, it contains only one line with two stops (tried to use a "dummy" schedule because we are not able to generate real public transit data)

I have no idea why this error appears. Can you help with solving it?

[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/6216069/1.logfile.log)

[config.xml.gz](https://github.com/matsim-org/matsim-code-examples/files/6216071/config.xml.gz)

```
2021-03-28T00:18:30,622  INFO CreateOperatorFromTransitSchedule:96 Returning 0 operators created from transit schedule file null
2021-03-28T00:18:30,637  INFO TimeProvider:120 Total weight is zero. Probably first iteration. Will pick time slots randomly.
2021-03-28T00:18:30,638  INFO TimeProvider:120 Total weight is zero. Probably first iteration. Will pick time slots randomly.
2021-03-28T00:18:30,840  INFO RandomStopProvider:124 Initialized with 0 of 0 stops covering 0.0 percent of activities
2021-03-28T00:18:30,854  INFO RandomStopProvider:135 No weights found. Probably no population given. Falling back to old behavior.
2021-03-28T00:18:30,855 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
java.lang.NullPointerException: null
	at org.matsim.contrib.minibus.replanning.CreateNewPlan.run(CreateNewPlan.java:96) ~[minibus-12.0-SNAPSHOT.jar:?]
	at org.matsim.contrib.minibus.operator.AbstractOperator.init(AbstractOperator.java:99) ~[minibus-12.0-SNAPSHOT.jar:?]
	at org.matsim.contrib.minibus.operator.CarefulMultiPlanOperator.init(CarefulMultiPlanOperator.java:55) ~[minibus-12.0-SNAPSHOT.jar:?]
	at org.matsim.contrib.minibus.operator.OperatorInitializer.createAdditionalOperators(OperatorInitializer.java:97) ~[minibus-12.0-SNAPSHOT.jar:?]
	at org.matsim.contrib.minibus.hook.PBox.notifyStartup(PBox.java:141) ~[minibus-12.0-SNAPSHOT.jar:?]
	at org.matsim.contrib.minibus.hook.PControlerListener.notifyStartup(PControlerListener.java:79) ~[minibus-12.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerStartupEvent(ControlerListenerManagerImpl.java:108) ~[matsim-12.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:77) ~[matsim-12.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-12.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-12.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88) [matsim-12.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-12.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-12.0-SNAPSHOT.jar:?]
	at org.matsim.contrib.minibus.RunMinibus.run(RunMinibus.java:58) [minibus-12.0-SNAPSHOT.jar:?]
	at org.matsim.contrib.minibus.RunMinibus.main(RunMinibus.java:66) [minibus-12.0-SNAPSHOT.jar:?]
	at org.matsim.contrib.minibus.PMain.main(PMain.java:31) [minibus-12.0-SNAPSHOT.jar:?]
2021-03-28T00:18:30,869  INFO MatsimRuntimeModifications:79 S H U T D O W N   ---   start shutdown.
2021-03-28T00:18:30,878 ERROR MatsimRuntimeModifications:81 ERROR --- This is an unexpected shutdown!
2021-03-28T00:18:30,878 ERROR MatsimRuntimeModifications:84 Shutdown possibly caused by the following Exception:
java.lang.NullPointerException: null
	at org.matsim.contrib.minibus.replanning.CreateNewPlan.run(CreateNewPlan.java:96) ~[minibus-12.0-SNAPSHOT.jar:?]
	at org.matsim.contrib.minibus.operator.AbstractOperator.init(AbstractOperator.java:99) ~[minibus-12.0-SNAPSHOT.jar:?]
	at org.matsim.contrib.minibus.operator.CarefulMultiPlanOperator.init(CarefulMultiPlanOperator.java:55) ~[minibus-12.0-SNAPSHOT.jar:?]
	at org.matsim.contrib.minibus.operator.OperatorInitializer.createAdditionalOperators(OperatorInitializer.java:97) ~[minibus-12.0-SNAPSHOT.jar:?]
	at org.matsim.contrib.minibus.hook.PBox.notifyStartup(PBox.java:141) ~[minibus-12.0-SNAPSHOT.jar:?]
	at org.matsim.contrib.minibus.hook.PControlerListener.notifyStartup(PControlerListener.java:79) ~[minibus-12.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerStartupEvent(ControlerListenerManagerImpl.java:108) ~[matsim-12.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:77) ~[matsim-12.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-12.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-12.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88) [matsim-12.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-12.0-SNAPSHOT.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-12.0-SNAPSHOT.jar:?]
	at org.matsim.contrib.minibus.RunMinibus.run(RunMinibus.java:58) [minibus-12.0-SNAPSHOT.jar:?]
	at org.matsim.contrib.minibus.RunMinibus.main(RunMinibus.java:66) [minibus-12.0-SNAPSHOT.jar:?]
	at org.matsim.contrib.minibus.PMain.main(PMain.java:31) [minibus-12.0-SNAPSHOT.jar:?]
2021-03-28T00:18:30,883  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.EventsHandlingImpl
2021-03-28T00:18:30,885  INFO ControlerListenerManagerImpl:121 calling notifyShutdown on org.matsim.core.controler.corelisteners.DumpDataAtEndImpl
2021-03-28T00:18:30,885  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ModeStatsControlerListener
2021-03-28T00:18:30,886  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.ScoreStatsControlerListener
2021-03-28T00:18:30,888  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.analysis.IterationTravelStatsControlerListener
2021-03-28T00:18:31,534  INFO IterationTravelStatsControlerListener:100 Writing all Person and Attributes to personscsv
2021-03-28T00:18:32,145  INFO IterationTravelStatsControlerListener:134 ...done
2021-03-28T00:18:32,146  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.contrib.minibus.stats.Line2GexfPStat
2021-03-28T00:18:32,147  INFO Line2GexfPStat:124 terminated the last 0 gexf handlers...
2021-03-28T00:18:32,148  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.contrib.minibus.stats.GexfPStatLight
2021-03-28T00:18:32,568  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.contrib.minibus.stats.GexfPStat
2021-03-28T00:18:32,683  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.contrib.minibus.stats.operatorLogger.POperatorLogger
2021-03-28T00:18:32,684  INFO ControlerListenerManagerImpl:126 calling notifyShutdown on org.matsim.contrib.minibus.stats.PStatsOverview
2021-03-28T00:18:32,685  INFO ControlerListenerManagerImpl:129 all ControlerShutdownListeners called.
2021-03-28T00:18:32,685 ERROR MatsimRuntimeModifications:99 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2021-03-28T00:18:32,685 ERROR MatsimRuntimeModifications:100 ERROR --- results should not be used for further analysis.
2021-03-28T00:18:32,686  INFO MatsimRuntimeModifications:102 S H U T D O W N   ---   shutdown completed.
2021-03-28T00:18:32,686 ERROR MatsimRuntimeModifications:104 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
```

**Comment by gammapopolam** [comment]
I am sorry for my inattention. It was a typo in config. 
I just forgot to add character 0 in the end of the coordinates in minY & maxY params
