### ISSUE TITLE
Question about nodes in MATSim simulation

### ISSUE THREAD

**Issue by ChevyLin** [matsim-org/matsim-code-examples#555]
Dear all:
I'm a beginner to MATSim, When I start my own simulation in MATSim GUI, It tell me :
`2) Error in custom provider, java.lang.IllegalArgumentException: There exists already a node with id = -101752.
Existing node: [id=-101752][coord=[x=1.2687049277399903E7][y=2607560.323263359]][type=null][nof_inlinks=1][nof_outlinks=1]
Node to be added: [id=-101752][coord=[x=1.2687049277399903E7][y=2607560.323263359]][type=null][nof_inlinks=0][nof_outlinks=0].
Node is not added to the network.
  at org.matsim.core.scenario.ScenarioByConfigModule.createScenario(ScenarioByConfigModule.java:9) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.scenario.ScenarioByConfigModule)
  at org.matsim.core.scenario.ScenarioByConfigModule.createScenario(ScenarioByConfigModule.java:9) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.scenario.ScenarioByConfigModule)
  while locating org.matsim.api.core.v01.Scenario
    for the 1st parameter of org.matsim.core.scenario.ScenarioByInstanceModule.providePopulation(ScenarioByInstanceModule.java:43)
  while locating org.matsim.api.core.v01.population.Population
    for the 1st parameter of org.matsim.core.scenario.ScenarioByInstanceModule.providePopulationFactory(ScenarioByInstanceModule.java:47)
  while locating org.matsim.api.core.v01.population.PopulationFactory
    for field at org.matsim.core.router.FreespeedFactorRouting.populationFactory(FreespeedFactorRouting.java:18)
  at org.matsim.core.router.TripRouterModule.install(TripRouterModule.java:55) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.Controler$1 -> org.matsim.core.controler.ControlerDefaultsModule -> org.matsim.core.router.TripRouterModule)
Caused by: java.lang.IllegalArgumentException: There exists already a node with id = -101752.
`
I search for the network.xml, but there is only one node which id=-101752, and this node is one link's start and another link's end. I would like to know what's wrong with my network or something else, hope you can fix my puzzle, thanks.

**Comment by Janekdererste** [comment]
This means you have the same node in your network twice. Matsim complains about that when it tries to load the network from file into memory. In case you have edited your network file manually, this could be a copy paste error. 

If you actually want two nodes at the very same coordinate. You have to assign different ids.

**Comment by ChevyLin** [comment]
> This means you have the same node in your network twice. Matsim complains about that when it tries to load the network from file into memory. In case you have edited your network file manually, this could be a copy paste error.
> 
> If you actually want two nodes at the very same coordinate. You have to assign different ids.

Thanks for your reply. As I said above, my network have only one node which id = -101752, so I'm puzzle about this, I can assure that there are no same nodes in my network. Thanks for your advice and could there be other circumstances cause this problem?Sincerely thanks,

**Comment by Janekdererste** [comment]
Sorry for the late reply. This is strange then. Could you make your scenario files and your repository with which you are starting matsim available as a link?

**Comment by ChevyLin** [comment]
I think I have found where the problem is. My PC has run out of memory. It is a embarrassing problem. Thanks for your kindly reply.
