### ISSUE TITLE
PersonPrepareForSim get stuck when trying to simulate Santiago Scenario

### ISSUE THREAD

**Issue by leocamus** [matsim-org/matsim-code-examples#584]
Hi all!

After one or two years, I am trying to re-run the MATSim Santiago Scenario, but I'm having issues in the PersonPrepareForSim step. 

I am using MATSim 13.0 and the somehow outdated versions of the Config and the Plans File. When trying to run MATSim without any modification in Config, I got a message that says there were trips without routingMode. I fix this adding the line config.plans().setHandlingOfPlansWithoutRoutingMode(HandlingOfPlansWithoutRoutingMode.useMainModeIdentifier) (don't know if this is the correct way to proceed in these cases). After this, PersonPrepareForSim got stuck. I don't know where to start to fix this problem... should I "update" the plans file to add the routingMode attribute to every leg? I'm not really sure if the useMainModeIdentifier is the problem or not.

I attach the console output and the config file I am using to run the simulation. 

[v2a_consoleOutput_stuck.txt](https://github.com/matsim-org/matsim-code-examples/files/6730057/v2a_consoleOutput_stuck.txt)
[config_baseCase1pct.txt](https://github.com/matsim-org/matsim-code-examples/files/6730084/config_baseCase1pct.txt)

**Comment by vsp-gleich** [comment]
Hi, 2 years ago we introduced the routing mode attribute at legs. This attribute tells the replanning logic which router to use for re-routing. It can be different from the leg mode itself, e.g. if an agent walks to the street to take the car from there, that is an walk leg with routing mode car.
When we introduced this most people converted their plans files by running in matsim, which does auto-detection of the routing mode using the MainModeIdentifier if that setting you mentioned (config.plans().setHandlingOfPlansWithoutRoutingMode(HandlingOfPlansWithoutRoutingMode.useMainModeIdentifier) is switched on (this is its intended use case). I cannot tell you why it's stuck for your plans file. Check your MainModeIdentifier gives the correct routing modes for your plans ( e.g. a walk-car-walk trip should be routing mode car and so on ). If that does not give a hint you might try to set a break point or write out which agent is being processed in PrepareForSimImpl.adaptOutdatedPlansForRoutingMode() and try to understand why other agents were processed and what is different about the agent that makes it stuck. It might help to set number of threads to 1 in global config to have only 1 agent processed at a time.

**Comment by leocamus** [comment]
Hi, thank you for all your help.

After some tests/debugging, I found the problematic agents that made the simulation to get stuck... The agents look like this

	<person id="16517105_40">
		<plan selected="yes">
			<activity type="home13.0H" x="343216.6166185329" y="6290460.766894415" end_time="08:58:50" >
			</activity>
			<leg mode="other">
			</leg>
			<activity type="educ6.0H" x="342317.16934315074" y="6288283.392608281" start_time="09:28:50" end_time="15:28:50" >
			</activity>
			<leg mode="other">
			</leg>
			<activity type="home1.0H" x="343216.6166185329" y="6290460.766894415" start_time="16:23:50" end_time="17:58:50" >
			</activity>
			<leg mode="walk">
			</leg>
			<activity type="leis0.5H" x="343087.4645670147" y="6290340.292128808" start_time="18:08:50" end_time="18:58:50" >
			</activity>
			<leg mode="walk">
			</leg>
			<activity type="home13.0H" x="343216.6166185329" y="6290460.766894415" start_time="19:08:50" >
			</activity>
		</plan>

	</person>

I am using a runner that makes some modification to the controller, adding other network modes than car (ride, taxi, colectivo, *other*) so I don't know if this is causing the problem when interacting with the PrepareForSimImpl.adaptOutdatedPlansForRoutingMode(). The runner that I am using is available here
https://github.com/leocamus/SantiagoEVProject/blob/master/src/main/java/runSantiagoTests/RunMatsimFromScratch.java

Any suggestions for fixing this problem will be helpful

**Comment by kainagel** [comment]
It is odd that it runs into an infinite loop rather than aborting with an error.  Some things to do:

* Find out the PID (process ID) of the non-terminating java job, and run "jstack PID" a couple of times on the job.  Post the result here.  This should give an idea of where it hangs.

Can you run the code with a plans file that has _only_ the plan above?  If so, then:

* change all "walk" modes into "other" and re-run.
* change all "other" modes into "walk" and re-run.

Other things:

* Is your network attributed correctly?  Most if not all links should have something like `modes="colectivo,other,car,taxi,ride"`.  (I think.  Depends a bit on the details of the setup.)

**Comment by leocamus** [comment]
Dear Professor Kai, 

Thanks for your response. 

1. I found the PID and run de jstack PID two times (the number of threads is set up to 1 in config)

**First log**

2021-07-29 17:48:01
Full thread dump Java HotSpot(TM) 64-Bit Server VM (11.0.12+8-LTS-237 mixed mode):

Threads class SMR info:
_java_thread_list=0x00007fbdd8c1c9c0, length=13, elements={
0x00007fbdd6017800, 0x00007fbdd5876800, 0x00007fbdd5879800, 0x00007fbdd6028800,
0x00007fbdd602b800, 0x00007fbdd602c000, 0x00007fbdd587f800, 0x00007fbdd602d000,
0x00007fbdd604a000, 0x00007fbdd6a75800, 0x00007fbddd065000, 0x00007fbddf176000,
0x00007fbddab59000
}

"main" #1 prio=5 os_prio=31 cpu=6762.59ms elapsed=211.04s allocated=966M defined_classes=6220 tid=0x00007fbdd6017800 nid=0x2003 in Object.wait()  [0x0000700001caa000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.12/Native Method)
	- waiting on <0x0000000712500000> (a java.lang.Thread)
	at java.lang.Thread.join(java.base@11.0.12/Thread.java:1305)
	- waiting to re-lock in wait() <0x0000000712500000> (a java.lang.Thread)
	at java.lang.Thread.join(java.base@11.0.12/Thread.java:1379)
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils.run(ParallelPersonAlgorithmUtils.java:113)
	at runSantiagoTests.SantiagoPrepareForSim.run(SantiagoPrepareForSim.java:151)
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:113)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89)
	at org.matsim.core.controler.NewControler.run(NewControler.java:82)
	at org.matsim.core.controler.Controler.run(Controler.java:249)
	at runSantiagoTests.RunMatsimFromScratch.main(RunMatsimFromScratch.java:126)

   Locked ownable synchronizers:
	- None

"Reference Handler" #2 daemon prio=10 os_prio=31 cpu=1.51ms elapsed=211.02s allocated=0B defined_classes=0 tid=0x00007fbdd5876800 nid=0x4a03 waiting on condition  [0x00007000023bf000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.12/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@11.0.12/Reference.java:241)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.12/Reference.java:213)

   Locked ownable synchronizers:
	- None

"Finalizer" #3 daemon prio=8 os_prio=31 cpu=0.61ms elapsed=211.02s allocated=280B defined_classes=1 tid=0x00007fbdd5879800 nid=0x4803 in Object.wait()  [0x00007000024c2000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.12/Native Method)
	- waiting on <0x0000000700161890> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.12/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x0000000700161890> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.12/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.12/Finalizer.java:170)

   Locked ownable synchronizers:
	- None

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 cpu=0.38ms elapsed=211.00s allocated=488B defined_classes=0 tid=0x00007fbdd6028800 nid=0x5603 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Service Thread" #5 daemon prio=9 os_prio=31 cpu=0.07ms elapsed=211.00s allocated=0B defined_classes=0 tid=0x00007fbdd602b800 nid=0xa803 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread0" #6 daemon prio=9 os_prio=31 cpu=5976.55ms elapsed=211.00s allocated=0B defined_classes=0 tid=0x00007fbdd602c000 nid=0xa603 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
	- None

"C1 CompilerThread0" #9 daemon prio=9 os_prio=31 cpu=1971.81ms elapsed=211.00s allocated=25960B defined_classes=0 tid=0x00007fbdd587f800 nid=0xa403 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
	- None

"Sweeper thread" #10 daemon prio=9 os_prio=31 cpu=4.75ms elapsed=211.00s allocated=0B defined_classes=0 tid=0x00007fbdd602d000 nid=0xa203 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Common-Cleaner" #11 daemon prio=8 os_prio=31 cpu=2.15ms elapsed=210.97s allocated=0B defined_classes=0 tid=0x00007fbdd604a000 nid=0x5c03 in Object.wait()  [0x0000700002cdd000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.12/Native Method)
	- waiting on <0x0000000700162510> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.12/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x0000000700162510> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@11.0.12/CleanerImpl.java:148)
	at java.lang.Thread.run(java.base@11.0.12/Thread.java:834)
	at jdk.internal.misc.InnocuousThread.run(java.base@11.0.12/InnocuousThread.java:134)

   Locked ownable synchronizers:
	- None

"Log4j2-TF-1-Scheduled-1" #13 daemon prio=5 os_prio=31 cpu=2.76ms elapsed=210.40s allocated=27616B defined_classes=5 tid=0x00007fbdd6a75800 nid=0x9403 waiting on condition  [0x00007000034f5000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.12/Native Method)
	- parking to wait for  <0x0000000700a7e8c8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.12/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.12/AbstractQueuedSynchronizer.java:2123)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.12/ScheduledThreadPoolExecutor.java:1182)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.12/ScheduledThreadPoolExecutor.java:899)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.12/ThreadPoolExecutor.java:1054)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.12/ThreadPoolExecutor.java:1114)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.12/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.12/Thread.java:834)

   Locked ownable synchronizers:
	- None

"MemoryPrinter" #15 daemon prio=5 os_prio=31 cpu=10.28ms elapsed=200.71s allocated=633K defined_classes=35 tid=0x00007fbddd065000 nid=0x6517 waiting on condition  [0x00007000033f2000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(java.base@11.0.12/Native Method)
	at org.matsim.utils.MemoryObserver$MemoryPrinter.run(MemoryObserver.java:58)
	at java.lang.Thread.run(java.base@11.0.12/Thread.java:834)

   Locked ownable synchronizers:
	- None

"PersonPrepareForSim.0" #16 prio=5 os_prio=31 cpu=197253.53ms elapsed=198.33s allocated=33145K defined_classes=24 tid=0x00007fbddf176000 nid=0x8b03 runnable  [0x0000700003f12000]
   java.lang.Thread.State: RUNNABLE
	at org.matsim.core.router.Dijkstra.constructPath(Dijkstra.java:341)
	at org.matsim.core.router.Dijkstra.calcLeastCostPath(Dijkstra.java:242)
	at org.matsim.core.router.NetworkRoutingModule.calcRoute(NetworkRoutingModule.java:95)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:174)
	- locked <0x0000000709224be8> (a org.matsim.core.router.TripRouter)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:94)
	at org.matsim.core.population.algorithms.PersonPrepareForSim.run(PersonPrepareForSim.java:220)
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils$PersonAlgoThread.run(ParallelPersonAlgorithmUtils.java:145)
	at java.lang.Thread.run(java.base@11.0.12/Thread.java:834)

   Locked ownable synchronizers:
	- None

"Attach Listener" #17 daemon prio=9 os_prio=31 cpu=0.81ms elapsed=0.17s allocated=0B defined_classes=0 tid=0x00007fbddab59000 nid=0x6e07 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"VM Thread" os_prio=31 cpu=163.86ms elapsed=211.02s tid=0x00007fbdd5871000 nid=0x3803 runnable  

"GC Thread#0" os_prio=31 cpu=167.67ms elapsed=211.04s tid=0x00007fbdd5810000 nid=0x5203 runnable  

"GC Thread#1" os_prio=31 cpu=173.94ms elapsed=210.70s tid=0x00007fbdd7017000 nid=0x5f03 runnable  

"GC Thread#2" os_prio=31 cpu=169.45ms elapsed=210.70s tid=0x00007fbdd7015000 nid=0x6103 runnable  

"GC Thread#3" os_prio=31 cpu=167.46ms elapsed=210.70s tid=0x00007fbdd7015800 nid=0x6203 runnable  

"GC Thread#4" os_prio=31 cpu=172.25ms elapsed=210.70s tid=0x00007fbdd709b000 nid=0x6303 runnable  

"GC Thread#5" os_prio=31 cpu=169.77ms elapsed=210.70s tid=0x00007fbdd709b800 nid=0x9803 runnable  

"GC Thread#6" os_prio=31 cpu=134.45ms elapsed=205.27s tid=0x00007fbddd9b2800 nid=0x3b07 runnable  

"GC Thread#7" os_prio=31 cpu=70.12ms elapsed=200.08s tid=0x00007fbddd216800 nid=0x8d03 runnable  

"G1 Main Marker" os_prio=31 cpu=1.21ms elapsed=211.04s tid=0x00007fbdd5845000 nid=0x5103 runnable  

"G1 Conc#0" os_prio=31 cpu=307.60ms elapsed=211.04s tid=0x00007fbdd5845800 nid=0x3003 runnable  

"G1 Conc#1" os_prio=31 cpu=307.48ms elapsed=210.12s tid=0x00007fbdd709d000 nid=0x6703 runnable  

"G1 Refine#0" os_prio=31 cpu=178709.69ms elapsed=211.03s tid=0x00007fbdd6889800 nid=0x4e03 runnable  

"G1 Refine#1" os_prio=31 cpu=165816.62ms elapsed=208.28s tid=0x00007fbdd91ca000 nid=0x9303 runnable  

"G1 Refine#2" os_prio=31 cpu=149297.68ms elapsed=208.28s tid=0x00007fbdd91b8800 nid=0x9203 runnable  

"G1 Refine#3" os_prio=31 cpu=128430.81ms elapsed=208.28s tid=0x00007fbdda1f2800 nid=0x9103 runnable  

"G1 Refine#4" os_prio=31 cpu=91789.70ms elapsed=208.28s tid=0x00007fbdda818000 nid=0x6c03 runnable  

"G1 Refine#5" os_prio=31 cpu=47891.63ms elapsed=208.28s tid=0x00007fbdd74b0000 nid=0x8f03 runnable  

"G1 Refine#6" os_prio=31 cpu=126.23ms elapsed=161.83s tid=0x00007fbdda16a800 nid=0x9c23 runnable  

"G1 Refine#7" os_prio=31 cpu=4.33ms elapsed=161.83s tid=0x00007fbddddf7800 nid=0x9d23 runnable  

"G1 Young RemSet Sampling" os_prio=31 cpu=40.41ms elapsed=211.03s tid=0x00007fbdd688a000 nid=0x3303 runnable  
"VM Periodic Task Thread" os_prio=31 cpu=115.83ms elapsed=210.97s tid=0x00007fbdd701d800 nid=0xa003 waiting on condition  

JNI global refs: 19, weak refs: 0

**Second log**

2021-07-29 17:52:42
Full thread dump Java HotSpot(TM) 64-Bit Server VM (11.0.12+8-LTS-237 mixed mode):

Threads class SMR info:
_java_thread_list=0x00007fbdd8c1c9c0, length=13, elements={
0x00007fbdd6017800, 0x00007fbdd5876800, 0x00007fbdd5879800, 0x00007fbdd6028800,
0x00007fbdd602b800, 0x00007fbdd602c000, 0x00007fbdd587f800, 0x00007fbdd602d000,
0x00007fbdd604a000, 0x00007fbdd6a75800, 0x00007fbddd065000, 0x00007fbddf176000,
0x00007fbddab59000
}

"main" #1 prio=5 os_prio=31 cpu=6762.59ms elapsed=491.73s allocated=966M defined_classes=6220 tid=0x00007fbdd6017800 nid=0x2003 in Object.wait()  [0x0000700001caa000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.12/Native Method)
	- waiting on <0x0000000712500000> (a java.lang.Thread)
	at java.lang.Thread.join(java.base@11.0.12/Thread.java:1305)
	- waiting to re-lock in wait() <0x0000000712500000> (a java.lang.Thread)
	at java.lang.Thread.join(java.base@11.0.12/Thread.java:1379)
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils.run(ParallelPersonAlgorithmUtils.java:113)
	at runSantiagoTests.SantiagoPrepareForSim.run(SantiagoPrepareForSim.java:151)
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:113)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89)
	at org.matsim.core.controler.NewControler.run(NewControler.java:82)
	at org.matsim.core.controler.Controler.run(Controler.java:249)
	at runSantiagoTests.RunMatsimFromScratch.main(RunMatsimFromScratch.java:126)

   Locked ownable synchronizers:
	- None

"Reference Handler" #2 daemon prio=10 os_prio=31 cpu=1.51ms elapsed=491.71s allocated=0B defined_classes=0 tid=0x00007fbdd5876800 nid=0x4a03 waiting on condition  [0x00007000023bf000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.12/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@11.0.12/Reference.java:241)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.12/Reference.java:213)

   Locked ownable synchronizers:
	- None

"Finalizer" #3 daemon prio=8 os_prio=31 cpu=0.61ms elapsed=491.70s allocated=280B defined_classes=1 tid=0x00007fbdd5879800 nid=0x4803 in Object.wait()  [0x00007000024c2000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.12/Native Method)
	- waiting on <0x0000000700161890> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.12/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x0000000700161890> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.12/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.12/Finalizer.java:170)

   Locked ownable synchronizers:
	- None

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 cpu=0.38ms elapsed=491.69s allocated=488B defined_classes=0 tid=0x00007fbdd6028800 nid=0x5603 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Service Thread" #5 daemon prio=9 os_prio=31 cpu=0.07ms elapsed=491.69s allocated=0B defined_classes=0 tid=0x00007fbdd602b800 nid=0xa803 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"C2 CompilerThread0" #6 daemon prio=9 os_prio=31 cpu=5977.55ms elapsed=491.69s allocated=0B defined_classes=0 tid=0x00007fbdd602c000 nid=0xa603 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
	- None

"C1 CompilerThread0" #9 daemon prio=9 os_prio=31 cpu=1972.87ms elapsed=491.69s allocated=25960B defined_classes=0 tid=0x00007fbdd587f800 nid=0xa403 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

   Locked ownable synchronizers:
	- None

"Sweeper thread" #10 daemon prio=9 os_prio=31 cpu=4.75ms elapsed=491.69s allocated=0B defined_classes=0 tid=0x00007fbdd602d000 nid=0xa203 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"Common-Cleaner" #11 daemon prio=8 os_prio=31 cpu=2.28ms elapsed=491.65s allocated=0B defined_classes=0 tid=0x00007fbdd604a000 nid=0x5c03 in Object.wait()  [0x0000700002cdd000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.12/Native Method)
	- waiting on <0x0000000700162510> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@11.0.12/ReferenceQueue.java:155)
	- waiting to re-lock in wait() <0x0000000700162510> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@11.0.12/CleanerImpl.java:148)
	at java.lang.Thread.run(java.base@11.0.12/Thread.java:834)
	at jdk.internal.misc.InnocuousThread.run(java.base@11.0.12/InnocuousThread.java:134)

   Locked ownable synchronizers:
	- None

"Log4j2-TF-1-Scheduled-1" #13 daemon prio=5 os_prio=31 cpu=3.45ms elapsed=491.08s allocated=28376B defined_classes=5 tid=0x00007fbdd6a75800 nid=0x9403 waiting on condition  [0x00007000034f5000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.12/Native Method)
	- parking to wait for  <0x0000000700a7e8c8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.12/LockSupport.java:234)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.12/AbstractQueuedSynchronizer.java:2123)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.12/ScheduledThreadPoolExecutor.java:1182)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.12/ScheduledThreadPoolExecutor.java:899)
	at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.12/ThreadPoolExecutor.java:1054)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.12/ThreadPoolExecutor.java:1114)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.12/ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(java.base@11.0.12/Thread.java:834)

   Locked ownable synchronizers:
	- None

"MemoryPrinter" #15 daemon prio=5 os_prio=31 cpu=11.70ms elapsed=481.40s allocated=643K defined_classes=35 tid=0x00007fbddd065000 nid=0x6517 waiting on condition  [0x00007000033f2000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(java.base@11.0.12/Native Method)
	at org.matsim.utils.MemoryObserver$MemoryPrinter.run(MemoryObserver.java:58)
	at java.lang.Thread.run(java.base@11.0.12/Thread.java:834)

   Locked ownable synchronizers:
	- None

"PersonPrepareForSim.0" #16 prio=5 os_prio=31 cpu=451155.24ms elapsed=479.02s allocated=47389K defined_classes=24 tid=0x00007fbddf176000 nid=0x8b03 runnable  [0x0000700003f12000]
   java.lang.Thread.State: RUNNABLE
	at org.matsim.core.router.Dijkstra.constructPath(Dijkstra.java:341)
	at org.matsim.core.router.Dijkstra.calcLeastCostPath(Dijkstra.java:242)
	at org.matsim.core.router.NetworkRoutingModule.calcRoute(NetworkRoutingModule.java:95)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:174)
	- locked <0x0000000709224be8> (a org.matsim.core.router.TripRouter)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:94)
	at org.matsim.core.population.algorithms.PersonPrepareForSim.run(PersonPrepareForSim.java:220)
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils$PersonAlgoThread.run(ParallelPersonAlgorithmUtils.java:145)
	at java.lang.Thread.run(java.base@11.0.12/Thread.java:834)

   Locked ownable synchronizers:
	- None

"Attach Listener" #17 daemon prio=9 os_prio=31 cpu=1.19ms elapsed=280.86s allocated=0B defined_classes=0 tid=0x00007fbddab59000 nid=0x6e07 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
	- None

"VM Thread" os_prio=31 cpu=372.29ms elapsed=491.71s tid=0x00007fbdd5871000 nid=0x3803 runnable  

"GC Thread#0" os_prio=31 cpu=172.34ms elapsed=491.72s tid=0x00007fbdd5810000 nid=0x5203 runnable  

"GC Thread#1" os_prio=31 cpu=178.21ms elapsed=491.39s tid=0x00007fbdd7017000 nid=0x5f03 runnable  

"GC Thread#2" os_prio=31 cpu=174.19ms elapsed=491.39s tid=0x00007fbdd7015000 nid=0x6103 runnable  

"GC Thread#3" os_prio=31 cpu=173.25ms elapsed=491.39s tid=0x00007fbdd7015800 nid=0x6203 runnable  

"GC Thread#4" os_prio=31 cpu=176.65ms elapsed=491.39s tid=0x00007fbdd709b000 nid=0x6303 runnable  

"GC Thread#5" os_prio=31 cpu=173.95ms elapsed=491.39s tid=0x00007fbdd709b800 nid=0x9803 runnable  

"GC Thread#6" os_prio=31 cpu=138.51ms elapsed=485.95s tid=0x00007fbddd9b2800 nid=0x3b07 runnable  

"GC Thread#7" os_prio=31 cpu=74.21ms elapsed=480.77s tid=0x00007fbddd216800 nid=0x8d03 runnable  

"G1 Main Marker" os_prio=31 cpu=1.21ms elapsed=491.72s tid=0x00007fbdd5845000 nid=0x5103 runnable  

"G1 Conc#0" os_prio=31 cpu=307.60ms elapsed=491.72s tid=0x00007fbdd5845800 nid=0x3003 runnable  

"G1 Conc#1" os_prio=31 cpu=307.48ms elapsed=490.81s tid=0x00007fbdd709d000 nid=0x6703 runnable  

"G1 Refine#0" os_prio=31 cpu=426459.98ms elapsed=491.72s tid=0x00007fbdd6889800 nid=0x4e03 runnable  

"G1 Refine#1" os_prio=31 cpu=413518.32ms elapsed=488.97s tid=0x00007fbdd91ca000 nid=0x9303 runnable  

"G1 Refine#2" os_prio=31 cpu=397283.21ms elapsed=488.97s tid=0x00007fbdd91b8800 nid=0x9203 runnable  

"G1 Refine#3" os_prio=31 cpu=376550.43ms elapsed=488.97s tid=0x00007fbdda1f2800 nid=0x9103 runnable  

"G1 Refine#4" os_prio=31 cpu=339417.75ms elapsed=488.97s tid=0x00007fbdda818000 nid=0x6c03 runnable  

"G1 Refine#5" os_prio=31 cpu=295136.44ms elapsed=488.97s tid=0x00007fbdd74b0000 nid=0x8f03 runnable  

"G1 Refine#6" os_prio=31 cpu=220479.23ms elapsed=442.52s tid=0x00007fbdda16a800 nid=0x9c23 runnable  

"G1 Refine#7" os_prio=31 cpu=138840.89ms elapsed=442.52s tid=0x00007fbddddf7800 nid=0x9d23 runnable  

"G1 Young RemSet Sampling" os_prio=31 cpu=87.16ms elapsed=491.72s tid=0x00007fbdd688a000 nid=0x3303 runnable  
"VM Periodic Task Thread" os_prio=31 cpu=228.88ms elapsed=491.65s tid=0x00007fbdd701d800 nid=0xa003 waiting on condition  

JNI global refs: 19, weak refs: 0

----

I try to run MATSim with a plans file only containing the "problematic agents" i.e. only those with the plans mentioned above, but changing the leg modes:
1. Changing all "walk" modes into "other" made the simulation stuck
2. I could go through the whole simulation (only 2 iterations for testing) when changing all "other" modes into "walk"

Also, I checked the mode attribute of the network links, and all of them have the modes "car,ride,taxi,other,colectivo" (putting aside the PT links that are exclusive for PT mode)

Thanks!

**Comment by kainagel** [comment]
Dear Leo, in our experience, the culprit is
```
at org.matsim.core.router.Dijkstra.constructPath(Dijkstra.java:341)
```

This can run into an infinite loop if link costs are zero or negative.  (Negative costs = positive utility.)

I am slightly surprised that we do not have put in enough consistency checks to test for that but maybe we haven't.  Often, but not always, you find warnings in your logfile about "links of length zero" or similar; could you please check that?  

A frequent culprit are so-called loop links, which are introduced to attach pt stops to nodes.  They are often introduced with length 0, but they should have _some_ length, e.g. 1m.

I will be on vacation for four weeks, but maybe others join the debugging.  Best wishes, Kai
