### ISSUE TITLE
DRT error

### ISSUE THREAD

**Issue by elyh1992** [matsim-org/matsim-code-examples#593]
Hi,

I have a simulation with car, pt, bike walk, and drt as main modes. I run this simulation for 100 iterations and then I would like to use the output plan file from this scenario as an input plan of other scenarios but I get this error: 

2021-07-09 10:46:34,599 ERROR MatsimRuntimeModifications:84 Shutdown possibly caused by the following Exception:
java.lang.ClassCastException: class org.matsim.core.population.routes.GenericRouteImpl cannot be cast to class org.matsim.contrib.drt.routing.DrtRoute (org.matsim.core.population.routes.GenericRouteImpl and org.matsim.contrib.drt.routing.DrtRoute are in unnamed module of loader 'app')
	at org.matsim.contrib.drt.passenger.DrtRequestCreator.createRequest(DrtRequestCreator.java:52)
	at org.matsim.contrib.drt.passenger.DrtRequestCreator.createRequest(DrtRequestCreator.java:37)
	at org.matsim.contrib.dvrp.passenger.PassengerEngine.handleDeparture(PassengerEngine.java:173)
	at org.matsim.core.mobsim.qsim.QSim.arrangeAgentDeparture(QSim.java:485)
	at org.matsim.core.mobsim.qsim.QSim.arrangeNextAgentAction(QSim.java:447)
	at org.matsim.core.mobsim.qsim.QSim.access$000(QSim.java:104)
	at org.matsim.core.mobsim.qsim.QSim$1.arrangeNextAgentState(QSim.java:157)
	at org.matsim.core.mobsim.qsim.ActivityEngineDefaultImpl.handleActivity(ActivityEngineDefaultImpl.java:155)
	at org.matsim.core.mobsim.qsim.QSim.arrangeAgentActivity(QSim.java:466)
	at org.matsim.core.mobsim.qsim.QSim.arrangeNextAgentAction(QSim.java:444)
	at org.matsim.core.mobsim.qsim.QSim.access$000(QSim.java:104)
	at org.matsim.core.mobsim.qsim.QSim$1.arrangeNextAgentState(QSim.java:157)
	at org.matsim.core.mobsim.qsim.DefaultTeleportationEngine.handleTeleportationArrivals(DefaultTeleportationEngine.java:140)
	at org.matsim.core.mobsim.qsim.DefaultTeleportationEngine.doSimStep(DefaultTeleportationEngine.java:124)
	at org.matsim.core.mobsim.qsim.QSim.doSimStep(QSim.java:402)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:262)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:126)
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:198)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:230)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:194)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:145)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:113)
	at org.matsim.core.controler.AbstractController.access$100(AbstractController.java:29)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:88)
	at org.matsim.core.controler.NewControler.run(NewControler.java:84)
	at org.matsim.core.controler.Controler.run(Controler.java:248)
	at org.matsim.run.RunMelbourne_multi_drt.main(RunMelbourne_multi_drt.java:78)

Do you have any idea how I can solve this problem?

Thank you for your help.

**Comment by michalmac** [comment]
Maybe you haven't added the drt route factory, see: https://github.com/matsim-org/matsim-libs/blob/45407de272602ff39d367d363c54ea695d91defc/contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtControlerCreator.java#L48-L51

**Comment by elyh1992** [comment]
> Maybe you haven't added the drt route factory, see: https://github.com/matsim-org/matsim-libs/blob/45407de272602ff39d367d363c54ea695d91defc/contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtControlerCreator.java#L48-L51

I think I have the drt route factory. Here is my run class:

public class RunMelbourne_multi_drt {
	private static final Logger log = Logger.getLogger(RunMelbourne_multi_drt.class) ;

	public static void main(String[] args) {
		for (String arg : args) {
			log.info( arg );
		}

		if ( args.length==0 ) {
			
			args = new String[] {"scenarios/2017-11-scenario-by-kai-from-vista/updated_config_ridesourcing_ridesplitting_RMIT.xml"} ;


		}
		// yyyyyy increase memory!

		Config config = prepareConfig(args);
		config.controler().setOverwriteFileSetting(OverwriteFileSetting.deleteDirectoryIfExists);



		Scenario scenario = prepareScenario(config);

		Controler controler = prepareControler(scenario);

		controler.run();
	}

	static Controler prepareControler(Scenario scenario) {
		Controler controler = RunMelbourne_new.prepareControler( scenario ) ;
		// drt + dvrp module
		controler.addOverridingModule(new MultiModeDrtModule());
		controler.addOverridingModule(new DvrpModule());
		controler.configureQSimComponents(DvrpQSimComponents.activateAllModes(MultiModeDrtConfigGroup.get(controler.getConfig())));
		controler.addOverridingModule(new DrtFareModule());

	/*	MelbournePlanScoringFunctionFactory initialPlanScoringFuctionFactory = new MelbournePlanScoringFunctionFactory(controler.getScenario());
		controler.addOverridingModule(new AbstractModule() {
			@Override
			public void install() {
				this.bindScoringFunctionFactory().toInstance(initialPlanScoringFuctionFactory);
			}
		});*/



		return controler;
	}

	static Scenario prepareScenario(Config config) {

		Scenario scenario = RunMelbourne_new.prepareScenario( config );
		RouteFactories routeFactories = scenario.getPopulation().getFactory().getRouteFactories();
		routeFactories.setRouteFactory(DrtRoute.class, new DrtRouteFactory());



		return scenario;
	}

	static Config prepareConfig(String[] args) {
		/*Config config = RunMelbourne_new.prepareConfig(args, new MultiModeDrtConfigGroup(), new DvrpConfigGroup() ) ;*/
		Config config = RunMelbourne_new.prepareConfig(args, new MultiModeDrtConfigGroup(), new DvrpConfigGroup(), new DrtFaresConfigGroup() ) ;

		DrtConfigs.adjustMultiModeDrtConfig(MultiModeDrtConfigGroup.get(config), config.planCalcScore(), config.plansCalcRoute());
		/*config.plansCalcRoute().setAccessEgressType(PlansCalcRouteConfigGroup.AccessEgressType.accessEgressModeToLink);*/
		config.plansCalcRoute().setInsertingAccessEgressWalk(true);

		
		return config ;


	}

}

**Comment by michalmac** [comment]
Are you using the same matsim version for the original and derived scenarios?

**Comment by kainagel** [comment]
I haven't followed the full discussion.  But if you are reading plans that include drt routes, then the route factory needs to be set _before_ those are read.

**Comment by elyh1992** [comment]
> Are you using the same matsim version for the original and derived scenarios?
Thank you for your answer.
Yes, I'm using the same version.

**Comment by elyh1992** [comment]
> I haven't followed the full discussion. But if you are reading plans that include drt routes, then the route factory needs to be set _before_ those are read.

Thank you for your reply.
Can you tell me how I should do that? Should I change the run class for that?

**Comment by michalmac** [comment]
> > I haven't followed the full discussion. But if you are reading plans that include drt routes, then the route factory needs to be set _before_ those are read.

Thanks @kainagel, this seems to be the issue here. First the scenario is read (`RunMelbourne_new.prepareScenario( config );`) and only later the drt route factory set.

> Can you tell me how I should do that? Should I change the run class for that?

One option is to create the scenario, add the drt route factory and then pass this scenario (instead of the config) to `RunMelbourne_new.prepareScenario()`.
