### ISSUE TITLE
DRT error (area based service)

### ISSUE THREAD

**Issue by elyh1992** [matsim-org/matsim-code-examples#595]
Hi,

I have a model with DRT. Before I used the door2door service and model was running without error. Now I wanted to switch to service area based DRT service. For this, I only added a shapefile that shows the boundaries of my DRT service and changed the operational scheme to service area based. I am getting following. Is there anything else that I need to add or modify to get the service area based work properly. How can I resolve this problem?
Thank you for your help in advance.
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, java.lang.IllegalArgumentException: Elements must not be empty
  at org.matsim.contrib.dvrp.run.AbstractDvrpModeModule.bindModal(AbstractDvrpModeModule.java:56) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.contrib.drt.run.MultiModeDrtModule -> org.matsim.contrib.drt.run.DrtModeModule)
  at org.matsim.contrib.dvrp.run.AbstractDvrpModeModule.bindModal(AbstractDvrpModeModule.java:56) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.contrib.drt.run.MultiModeDrtModule -> org.matsim.contrib.drt.run.DrtModeModule)
  while locating org.matsim.contrib.dvrp.router.DvrpRoutingModule$AccessEgressFacilityFinder annotated with @org.matsim.contrib.dvrp.run.DvrpMode(value=ridesplitting)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236)
	at org.matsim.core.controler.Injector.createInjector(Injector.java:74)
	at org.matsim.core.controler.Controler.run(Controler.java:246)
	at org.matsim.run.RunMelbourne_multi_drt.main(RunMelbourne_multi_drt.java:74)
Caused by: java.lang.IllegalArgumentException: Elements must not be empty
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at org.matsim.core.utils.collections.QuadTrees.createQuadTree(QuadTrees.java:42)
	at org.matsim.core.utils.collections.QuadTrees.createQuadTree(QuadTrees.java:36)
	at org.matsim.contrib.drt.run.DrtModeModule.lambda$install$1(DrtModeModule.java:113)
	at org.matsim.contrib.dvrp.run.ModalProviders$2.get(ModalProviders.java:56)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:53)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
	... 6 more

Process finished with exit code 1

**Comment by michalmac** [comment]
Looks like your shapefile and network do not fit to each other. No network link could be found inside the geometries from the shapefiles. Maybe check if the coordinate system is the same for both.
