### ISSUE TITLE
NullPointerException while locating SwissRailRaptorFactory

### ISSUE THREAD

**Issue by vsgo222** [matsim-org/matsim-code-examples#602]
Hi,
I am trying to run MATSim in the San Francisco city area with modes car, drt, pt: Subway, Tram, Bus. Since, SwissRailRaptor is now the default router, I have not made any override settings to call the module explicitly and therefore using MATSim-MAAS. However, I get the following error:
`1) [Guice/ErrorInCustomProvider]: NullPointerException while locating SwissRailRaptorFactory at SwissRailRaptorRoutingModuleProvider.<init>(SwissRailRaptorRoutingModuleProvider.java:28) \_ for 1st parameter while locating SwissRailRaptorRoutingModuleProvider while locating RoutingModule annotated with @Named(value="pt") while locating RoutingModule annotated with @Element(setName=,uniqueId=130, type=MAPBINDER, keyType=String) at TripRouter.<init>(TripRouter.java:103) while locating TripRouter`
The code says that RoutingModule could not be initialized but I am not very sure what can I do to overcome this object initialization error. Can someone help me in understanding why I get the error and how it could be handled?
I am also reviewing the MATSim-Berlin scenario which has PT, DRT modes but creates a custom config, scenario, and controller. There is a comment which states the following
`use the main mode identifier which knows how to handle intermodal trips generated by the used sbb pt raptor router the SwissRailRaptor already binds its IntermodalAwareRouterModeIdentifier, however, drt obviously replaces it with its own implementation,` so does it mean that I need a custom class similar to the one found for MATSim-Berlin? If yes, is there any guide that can help me to build it with all relevant dependencies or MATSim-Berlin (OpenBerlinScenario.java) could be used to run it?

Thank you,
Vedant

**Comment by mrieser** [comment]
Which version of MATSim do you use?
Which class to do you use to start your simulation?

In older versions of MATSim, both SwissRailRaptor and DRT were extensions to MATSim. In order to use them, a specialized class was needed to enable them both at the same time, similar to the Berlin-Scenario.
In the latest MATSim 13.0, SwissRailRaptor is now available and active by default. So if you are using this version of MATSim, it should be sufficient to just enable the DRT extension and then both should be able to work together.

Without seeing the code that you use to start your MATSim simulation it's difficult to pinpoint the exact reason for the error message.

**Comment by vsgo222** [comment]
> 
> 
> Which version of MATSim do you use?
> Which class to do you use to start your simulation?
> 
> In older versions of MATSim, both SwissRailRaptor and DRT were extensions to MATSim. In order to use them, a specialized class was needed to enable them both at the same time, similar to the Berlin-Scenario.
> In the latest MATSim 13.0, SwissRailRaptor is now available and active by default. So if you are using this version of MATSim, it should be sufficient to just enable the DRT extension, and then both should be able to work together.
> 
> Without seeing the code that you use to start your MATSim simulation, it's difficult to pinpoint the exact reason for the error message.

@mrieser, I cloned the latest version from the forum. So, in the dependency section, it shows org. matsim:matsim:14.0-PR1548. I tried both RunMAAS and RunDoorToDoorDrtExample class,

**Comment by michalmac** [comment]
I just run `RunDoorToDoorDrtExample` and it works fine. Also all tests in matsim-maas are green. I guess you must have changed something (code and/or input).
