### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 121

### ISSUE THREAD

**Issue by china-shuai** [matsim-org/matsim-code-examples#630]
Hello, I encountered the following problems when running matsim.
` ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.4 died with exception while handling events.
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 121
	at org.matsim.core.trafficmonitoring.TravelTimeDataArray.getTravelTime(TravelTimeDataArray.java:110) ~[classes/:?]
	at org.matsim.core.trafficmonitoring.AveragingTravelTimeGetter.getTravelTime(AveragingTravelTimeGetter.java:38) ~[classes/:?]
	at org.matsim.core.trafficmonitoring.TravelTimeCalculator.getLinkTravelTime(TravelTimeCalculator.java:375) ~[classes/:?]
	at org.matsim.core.trafficmonitoring.TravelTimeCalculator$1.getLinkTravelTime(TravelTimeCalculator.java:513) ~[classes/:?]
	at org.matsim.core.router.AStarEuclidean.addToPendingNodes(AStarEuclidean.java:152) ~[classes/:?]
	at org.matsim.core.router.Dijkstra.relaxNodeLogic(Dijkstra.java:420) ~[classes/:?]
	at org.matsim.core.router.Dijkstra.relaxNode(Dijkstra.java:391) ~[classes/:?]
	at org.matsim.core.router.AStarLandmarks.relaxNode(AStarLandmarks.java:137) ~[classes/:?]
	at org.matsim.core.router.Dijkstra.searchLogic(Dijkstra.java:315) ~[classes/:?]
	at org.matsim.core.router.Dijkstra.calcLeastCostPath(Dijkstra.java:234) ~[classes/:?]
	at org.matsim.core.router.AStarLandmarks.calcLeastCostPath(AStarLandmarks.java:124) ~[classes/:?]
	at org.matsim.core.router.NetworkRoutingModule.calcRoute(NetworkRoutingModule.java:104) ~[classes/:?]
	at ch.sbb.matsim.routing.pt.raptor.DefaultRaptorStopFinder.addInitialStopsForParamSet(DefaultRaptorStopFinder.java:190) ~[classes/:?]
	at ch.sbb.matsim.routing.pt.raptor.DefaultRaptorStopFinder.findIntermodalStops(DefaultRaptorStopFinder.java:122) ~[classes/:?]
	at ch.sbb.matsim.routing.pt.raptor.DefaultRaptorStopFinder.findAccessStops(DefaultRaptorStopFinder.java:81) ~[classes/:?]
	at ch.sbb.matsim.routing.pt.raptor.DefaultRaptorStopFinder.findStops(DefaultRaptorStopFinder.java:69) ~[classes/:?]
	at ch.sbb.matsim.routing.pt.raptor.SwissRailRaptor.findAccessStops(SwissRailRaptor.java:245) ~[classes/:?]
	at ch.sbb.matsim.routing.pt.raptor.SwissRailRaptor.calcRoute(SwissRailRaptor.java:67) ~[classes/:?]
	at ch.sbb.matsim.routing.pt.raptor.SwissRailRaptorRoutingModule.calcRoute(SwissRailRaptorRoutingModule.java:56) ~[classes/:?]
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:174) ~[classes/:?]
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:94) ~[classes/:?]
	at org.matsim.core.population.algorithms.PersonPrepareForSim.run(PersonPrepareForSim.java:233) ~[classes/:?]
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils$PersonAlgoThread.run(ParallelPersonAlgorithmUtils.java:145) ~[classes/:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2021-10-20T00:46:14,644 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.7 died with exception while handling events.
java.lang.ArrayIndexOutOfBoundsException: null
2021-10-20T00:46:18,470 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.10 died with exception while handling events.
java.lang.ArrayIndexOutOfBoundsException: null
2021-10-20T00:46:22,250 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.8 died with exception while handling events.
java.lang.ArrayIndexOutOfBoundsException: null
2021-10-20T00:46:23,423 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.14 died with exception while handling events.
java.lang.ArrayIndexOutOfBoundsException: null
2021-10-20T00:46:24,005 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.9 died with exception while handling events.
java.lang.ArrayIndexOutOfBoundsException: null
2021-10-20T00:46:28,719 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.12 died with exception while handling events.
java.lang.ArrayIndexOutOfBoundsException: null
2021-10-20T00:46:44,491 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.0 died with exception while handling events.
java.lang.ArrayIndexOutOfBoundsException: null
2021-10-20T00:46:55,050 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.13 died with exception while handling events.
java.lang.ArrayIndexOutOfBoundsException: null
2021-10-20T00:46:56,564 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.1 died with exception while handling events.
java.lang.ArrayIndexOutOfBoundsException: null
2021-10-20T00:47:00,862 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.2 died with exception while handling events.
java.lang.ArrayIndexOutOfBoundsException: null
2021-10-20T00:47:39,117 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.3 died with exception while handling events.
java.lang.ArrayIndexOutOfBoundsException: null
2021-10-20T00:47:43,469 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.15 died with exception while handling events.
java.lang.ArrayIndexOutOfBoundsException: null`
When I pick out these agents to run alone, there is no problem.

**Comment by china-shuai** [comment]
[0.config.txt](https://github.com/matsim-org/matsim-code-examples/files/7381631/0.config.txt)
