### ISSUE TITLE
Subpopulation error

### ISSUE THREAD

**Issue by khzannat** [matsim-org/matsim-code-examples#671]
Hello, 
I am trying to specify different scoring parameter for two subgroup. I have attached herewith a small proportion of my plan with attributes.
![image](https://user-images.githubusercontent.com/34195237/148701290-d78feaf0-276f-46a4-9205-3c887e912f53.png)

................................................
However, when I am running the code I am getting an error saying _Element type "attributes" must be declared._
My attributes are already declared in the plan file. Could you please let me know why I am having this error? The detail error is given below:
XML-ERROR: file:/D:/PhD%20Research/Dhaka_scenario_MATSIM/Dhaka/scenarios/Dhaka_input/database_with_walk_bike_moto_employ.xml, line 4, column 14:
org.xml.sax.SAXParseException; systemId: file:/D:/PhD%20Research/Dhaka_scenario_MATSIM/Dhaka/scenarios/Dhaka_input/database_with_walk_bike_moto_employ.xml; lineNumber: 4; columnNumber: 14; Element type "attributes" must be declared.
Exception in thread "main" org.matsim.core.utils.io.UncheckedIOException: org.xml.sax.SAXParseException; systemId: file:/D:/PhD%20Research/Dhaka_scenario_MATSIM/Dhaka/scenarios/Dhaka_input/database_with_walk_bike_moto_employ.xml; lineNumber: 4; columnNumber: 14; Element type "attributes" must be declared.
	at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:200)
	at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:169)
	at org.matsim.core.scenario.ScenarioLoaderImpl.loadPopulation(ScenarioLoaderImpl.java:202)
	at org.matsim.core.scenario.ScenarioLoaderImpl.loadScenario(ScenarioLoaderImpl.java:115)
	at org.matsim.core.scenario.ScenarioUtils.loadScenario(ScenarioUtils.java:79)
	at org.matsim.project.RunMatsim9.main(RunMatsim9.java:198)
Caused by: org.xml.sax.SAXParseException; systemId: file:/D:/PhD%20Research/Dhaka_scenario_MATSIM/Dhaka/scenarios/Dhaka_input/database_with_walk_bike_moto_employ.xml; lineNumber: 4; columnNumber: 14; Element type "attributes" must be declared.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.error(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.handleStartElement(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:194)
	... 5 more

**Comment by Janekdererste** [comment]
You are using an outdated plans format. The current version is v6. You can find an example of the current format below. 

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE population SYSTEM "http://www.matsim.org/files/dtd/population_v6.dtd">

<population desc="population written from streaming">

<!-- ====================================================================== -->

        <person id="10">
                <attributes>
                        <attribute name="MiD:hheink_gr2" class="java.lang.String">8</attribute>
                        <attribute name="MiD:hhgr_gr" class="java.lang.String">4</attribute>
                        <attribute name="microm:modeled:age" class="java.lang.Integer">30</attribute>
                        <attribute name="microm:modeled:sex" class="java.lang.String">m</attribute>
                        <attribute name="sim_carAvailability" class="java.lang.String">always</attribute>
                        <attribute name="sim_ptAbo" class="java.lang.String">none</attribute>
                        <attribute name="subpopulation" class="java.lang.String">person</attribute>
                </attributes>
                <plan score="0.0" selected="yes">
                        <activity type="home_28800.0" x="307562.0" y="5696497.0" end_time="09:15:00" >
                        </activity>
                        <leg mode="pt">
                                <attributes>
                                        <attribute name="routingMode" class="java.lang.String">pt</attribute>
                                </attributes>
                        </leg>
                        <activity type="work_13800.0" x="336939.0" y="5696045.0" start_time="09:57:00" end_time="13:43:00" >
                        </activity>
                        <leg mode="pt">
                                <attributes>
                                        <attribute name="routingMode" class="java.lang.String">pt</attribute>
                                </attributes>
                        </leg>
                        <activity type="business_8400.0" x="337225.0" y="5699052.0" start_time="13:53:00" end_time="16:12:00" >
                        </activity>
                        <leg mode="pt">
                                <attributes>
                                        <attribute name="routingMode" class="java.lang.String">pt</attribute>
                                </attributes>
                        </leg>
                        <activity type="business_3600.0" x="334993.0" y="5702041.0" start_time="16:23:00" end_time="17:26:00" >
                        </activity>
                        <leg mode="pt">
                                <attributes>
                                        <attribute name="routingMode" class="java.lang.String">pt</attribute>
                                </attributes>
                        </leg>
                        <activity type="home_28800.0" x="307562.0" y="5696497.0" start_time="18:11:00" >
                        </activity>
                </plan>

        </person>

<!-- ====================================================================== -->

... other persons
</population>
```
However, I think that v4 actually doesn't have ```<attributes/>``` as property 🤔

How do you generate your plans? If generated with the MATSim SDK you should receive the current format by default.

**Comment by khzannat** [comment]
I am generating my plan file using my own python code, not using MATSim SDK. Is it Ok to specify different scoring for all the attributes mentioned in your given example? age, gender, having car?
Or I have to specify score for just one attribute?

**Comment by Janekdererste** [comment]
We also have [python bindings](https://github.com/matsim-vsp/matsim-python-tools) for reading and writing common matsim files. Maybe this helps. 

The scoring parameters are set per sub population. Without programming I think every person can only belong to one sub population.

**Comment by khzannat** [comment]
I coded to set parameters per subpopulation using the following code. 
https://github.com/khzannat/matsim-example-project/blob/master/src/main/java/org/matsim/project/RunMatsim9.java
However, I have the following error
Exception in thread "main" java.lang.RuntimeException: Using several subpopulations in planCalcScore requires defining a "default " subpopulation. Otherwise, crashes can be expected.
	at org.matsim.core.config.groups.PlanCalcScoreConfigGroup.checkConsistency(PlanCalcScoreConfigGroup.java:618)
	at org.matsim.core.config.Config.checkConsistency(Config.java:208)
	at org.matsim.core.controler.Controler.run(Controler.java:230)
	at org.matsim.project.RunMatsim9.main(RunMatsim9.java:203)
This is my test plan:
https://github.com/khzannat/matsim-example-project/blob/master/scenarios/Dhaka_input/test.xml
and config file:
https://github.com/khzannat/matsim-example-project/blob/master/scenarios/Dhaka_input/config.xml

**Comment by Janekdererste** [comment]
You set scoring parameters for subpopulations. This removes the scoring parameters for the implicit 'default' subpopulation which receives the parameters from your `config.xml` file. 

To prevent the error you see, you have to add yet another subpopulation called `"default"` with scoring parameters to your scenario. It will be used as a fallback, in case any agent does not belong to one of the subpopulations defined by you. 

This behaviour is not very intuitive. Sorry about that.

**Comment by khzannat** [comment]
Thank you for your reply, in that case do I have to override the default scoring in controler? Because after defining parameters for the default subpopulation I am having an error
`Exception in thread "main" java.lang.NullPointerException: Cannot invoke "org.matsim.core.config.groups.PlanCalcScoreConfigGroup$ModeParams.getMarginalUtilityOfTraveling()" because the return value of "java.util.Map.get(Object)" is null`
I printed out each `ScoringParameterSet` for every `subppulation` and they are not null.
Also using `getMarginalUtilityOfTraveling()` I saw marginal utility of travel time for each subpopulation was set properly.

**Comment by Janekdererste** [comment]
If you update your `RunMatsim9` class I'll have a look tomorrow.

**Comment by khzannat** [comment]
Updated, I saw one 'config' with subpopulation and they have fixed `subpopulationAttributeName`, but this feature is no longer available in the current version. Not sure whether it will resolve the issue.

**Comment by khzannat** [comment]
Hi, I resolved the issue today. Thank you for your cooperation.

**Comment by cnabu** [comment]
Hi @khzannat, 

I'm having a similar problem as you had when I try to set separate mode parameters values for my two subpopulations. Can you kindly share your RunMatsim9.java and your config.xml file with me. I'll be truly grateful.

Kind regards,
Arsal
