### ISSUE TITLE
How to identify Error in simulation

### ISSUE THREAD

**Issue by aayushtewari01** [matsim-org/matsim-code-examples#675]
I have prepared a config file with network and population data. uploaded it in MATSim and this is one exception error I got.  How to identify the precise error and how we can rectify it.

`
The error what appears is that  
'There exists already a node with id = 4994026.
Existing node: [id=4994026][coord=[x=139.73328010539464 | y=35.70961856383456]][type=null][nof_inlinks=0][nof_outlinks=3]
Node to be added: [id=4994026][coord=[x=139.73328010539464 | y=35.70961856383456]][type=null][nof_inlinks=0][nof_outlinks=0].
Node is not added to the network.'

What does this mean?. I checked the network data on QGIS the node exists and the links also exists.
I checked the netwotk.xml data and there also node and associated link exists. So, where am I getting wrong. 

Would someone please guide me into it. 
Thankyou
Please guide

**Comment by aayushtewari01** [comment]
For the earlier error I recreated the network file by allotting separate link ids to those links which are bidirectional. I am not sure  if it is fine because I am stuck in another error after using the new network file.

The error is:
Please someone guide.


ERROR MatsimRuntimeModifications:81 ERROR --- This is an unexpected shutdown!
2022-02-05T21:11:28,494 ERROR MatsimRuntimeModifications:84 Shutdown possibly caused by the following Exception:
java.lang.NullPointerException: Cannot invoke "org.matsim.core.config.groups.PlanCalcScoreConfigGroup$ModeParams.getMarginalUtilityOfTraveling()" because the return value of "java.util.Map.get(Object)" is null
	at org.matsim.core.config.groups.PlanCalcScoreConfigGroup$ScoringParameterSet.getMarginalUtlOfWaitingPt_utils_hr(PlanCalcScoreConfigGroup.java:1358) ~[matsim-13.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

**Comment by khzannat** [comment]
Hi I am having the same error `org.matsim.core.config.groups.PlanCalcScoreConfigGroup$ModeParams.getMarginalUtilityOfTraveling()" because the return value of "java.util.Map.get(Object)" is null`
 how did you resolve the error?

**Comment by aayushtewari01** [comment]
@khzannat ..are you using Java16. 
java version 11 works well for MATSIM. can you clarify? if you are using Java11 and still get the error .Please drop in a comment. I might need to check my old files.

**Comment by khzannat** [comment]
Thank you very much for your reply. I am using Java 11

**Comment by aayushtewari01** [comment]
@khzannat in my case error was mainly because of three reasons:
1. I created a sample network in which agents near the edge were not able to find a proper route and the error was (i) network not connected (ii) or , no route exist from node__ to node__
2. I created a wrong config file which was not as per the default config file of MATSim.

3. In plan file : in activity I had an empty...._link "  "_

for 1. the solution was resolved when I created a larger sample network. Larger network lead to more memory consumption but the network error was resolved.

for 2. I copied the default config file and then excluded those syntax which were not required to create my config file.

3. for 3:  my plan file was very basic and only meant for one mode i.e car and only two activity i.e Home to Work and Work to Home. I deleted the empty link "  " , as Matsim allots nearest link as per the Origin coordinates of agent. 

In case there is some issue with config file,  you can paste your config file here , some experts can see it and better judge it.
I hope it helps to zero in into where to see, although I myself am struggling with output files now. 
Thanks

**Comment by Mamun180419** [comment]
[config.zip](https://github.com/matsim-org/matsim-code-examples/files/10883650/config.zip)

What's wrong with my config file, everytime i run MATSim it says "The simulation did not run properly. Error/Exit code: 1"

**Comment by kainagel** [comment]
Could you please provide the full logfile?  thanks

**Comment by khzannat** [comment]
Is it a new scenario? Or the equil scenario? And, yes it would be good to see your logfile with error?

**Comment by Mamun180419** [comment]
> Could you please provide the full logfile? thanks

The MATSim isn't generating an output file. So i'm just pasting the warnings from the GUI directly. And I'm working on the transit schedule problem but the node issues don't seem to improve

[errorlog.txt](https://github.com/matsim-org/matsim-code-examples/files/10887161/errorlog.txt)

**Comment by Mamun180419** [comment]
> Is it a new scenario? Or the equil scenario? And, yes it would be good to see your logfile with error?

It is new scenario. I am attaching the config and network file 
[config.zip](https://github.com/matsim-org/matsim-code-examples/files/10887140/config.zip)
[network.zip](https://github.com/matsim-org/matsim-code-examples/files/10887141/network.zip)

**Comment by Mamun180419** [comment]
[Guice/ErrorInCustomProvider]: IllegalArgumentException: There exists already a node with id = -137710.
Existing node: [id=-137710][coord=[x=9970981.20147787 | y=2609558.0569461863]][type=null][nof_inlinks=4][nof_outlinks=4]
Node to be added: [id=-137710][coord=[x=9970981.20147787 | y=2609558.0569461863]][type=null][nof_inlinks=0][nof_outlinks=0].
Node is not added to the network.

**Comment by aayushtewari01** [comment]
@Mamun180419 well in my case initially I had exactly same type of error. If you check the network and identify the node on a any GIS tool , it would be not easy to make any concluding inference from the error statement. The error node 137710 would always be there. In my case I was making following mistakes
1. Allotting same link id to two lanes which were opposite in direction but connected with common end nodes.
2. Creating a smaller network size due to memory constraints. Size of network needs to be increased. There is no definition of how large though. Only that it should enable the agents to traverse all possible network combination on the  OD set. This is one problem which I regularly faced since I was using part of the large network due to memory issue. But I had to recreate it 3-4 times to find the appropriate size and which also enabled agents routing.

On the other hand, honestly the error statement perse does not gives much conclusion and you should check other possible sources of error.

**Comment by Mamun180419** [comment]
@aayushtewari01 the error code is pointing towards the duplication of node ids. I have checked some of the nodes in the xml through find and replace function but there is no duplication of nodes. So I am facing a dead end.
By the way are you simulating public transit also?

**Comment by kainagel** [comment]
The first error message has to do with your transit_schedule.xml.  Could you please run with public transit switched off and the transit entries removed from the config.xml?  (Please always start with the simple examples and then add complexity.)
