### ISSUE TITLE
Matsim not running with 100 Agents

### ISSUE THREAD

**Issue by 100330627** [matsim-org/matsim-code-examples#680]
Hello I am new in matsim however I did my first simulations and I was able to run it until I got 100 agents, then I was not able to perform the simulation

This is the log trace where it does not work

2022-02-08T22:47:04,051  WARN LinkImpl:116 permlanes=0.5 of link id 117465803_0 may cause problems
2022-02-08T22:47:04,051  WARN LinkImpl:118  Future occurences of this logging statement are suppressed.
2022-02-08T22:47:04,054  WARN LinkImpl:125 length=0.0 of link id 117856615_0 may cause problems
2022-02-08T22:47:04,054  WARN LinkImpl:127  Future occurences of this logging statement are suppressed.
2022-02-08T22:47:04,286  WARN LinkImpl:98 capacity=0.0 of link id 54059930_0 may cause problems
2022-02-08T22:47:04,286  WARN LinkImpl:100  Future occurences of this logging statement are suppressed.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/C:/Users/alvaro/.m2/repository/com/google/inject/guice/4.2.2/guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2022-02-08T22:47:05,544  WARN PrepareForSimImpl:222 'usePersonIdForMissingVehicleId' is deprecated. It will be removed soon.
2022-02-08T22:47:05,577  WARN PreProcessEuclidean:59 There are links with stored length smaller than their Euclidean distance in this network. Thus, A* cannot guarantee to calculate the least-cost paths between two nodes.
2022-02-08T22:47:05,845  WARN RandomizingTimeDistanceTravelDisutilityFactory:112 There will be no routing randomness. The randomization of the travel disutility requires the monetary distance rate to be different than zero. Continuing anyway.
2022-02-08T22:47:05,845  WARN RandomizingTimeDistanceTravelDisutilityFactory:117 There will be no routing randomness. The randomization of the travel disutility requires the travel time cost rate to be different than zero. Continuing anyway.
2022-02-08T22:47:05,858  WARN PreProcessEuclidean:59 There are links with stored length smaller than their Euclidean distance in this network. Thus, A* cannot guarantee to calculate the least-cost paths between two nodes.
2022-02-08T22:47:06,680 ERROR BasicPlanAgentImpl:184 last activity of person driver agent id 6 has end time < infty; setting it to infty
2022-02-08T22:47:06,680 ERROR BasicPlanAgentImpl:185  This message given only once.
2022-02-08T22:47:08,204 ERROR SimStepParallelEventsManagerImpl$ExceptionHandler:420 Thread class org.matsim.core.events.SimStepParallelEventsManagerImpl$ProcessEventsRunnable0 died with exception while handling events.
java.lang.IllegalArgumentException: acttype "medical" is not known in utility parameters (module name="planCalcScore" in the config file).
	at org.matsim.core.scoring.functions.CharyparNagelActivityScoring.calcActScore(CharyparNagelActivityScoring.java:80) ~[matsim-13.0.jar:?]
	at org.matsim.core.scoring.functions.CharyparNagelActivityScoring.handleActivity(CharyparNagelActivityScoring.java:281) ~[matsim-13.0.jar:?]
	at org.matsim.core.scoring.SumScoringFunction.handleActivity(SumScoringFunction.java:99) ~[matsim-13.0.jar:?]
	at org.matsim.core.scoring.ScoringFunctionsForPopulation.handleActivity(ScoringFunctionsForPopulation.java:194) ~[matsim-13.0.jar:?]
	at org.matsim.core.scoring.EventsToActivities.handleEvent(EventsToActivities.java:85) ~[matsim-13.0.jar:?]
	at org.matsim.core.scoring.EventsToLegsAndActivities.handleEvent(EventsToLegsAndActivities.java:53) ~[matsim-13.0.jar:?]
	at org.matsim.core.events.EventsManagerImpl.callHandlerFast(EventsManagerImpl.java:283) ~[matsim-13.0.jar:?]
	at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:141) ~[matsim-13.0.jar:?]
	at org.matsim.core.events.SimStepParallelEventsManagerImpl$ProcessEventsRunnable.run(SimStepParallelEventsManagerImpl.java:330) ~[matsim-13.0.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2022-02-08T22:47:08,224  WARN QSim:263 exception in finally block - this may be a follow-up exception of an exception thrown in the try block.
java.lang.RuntimeException: Exception while processing events. Cannot guarantee that all events have been fully processed.
	at org.matsim.core.events.SimStepParallelEventsManagerImpl.finishProcessing(SimStepParallelEventsManagerImpl.java:212) ~[matsim-13.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.cleanupSim(QSim.java:350) ~[matsim-13.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:261) [matsim-13.0.jar:?]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124) [matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:211) [matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:243) [matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:207) [matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154) [matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121) [matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:81) [matsim-13.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-13.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89) [matsim-13.0.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-13.0.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-13.0.jar:?]
	at org.matsim.project.RunMatsim.main(RunMatsim.java:86) [classes/:?]
Caused by: java.lang.IllegalArgumentException: acttype "medical" is not known in utility parameters (module name="planCalcScore" in the config file).
	at org.matsim.core.scoring.functions.CharyparNagelActivityScoring.calcActScore(CharyparNagelActivityScoring.java:80) ~[matsim-13.0.jar:?]
	at org.matsim.core.scoring.functions.CharyparNagelActivityScoring.handleActivity(CharyparNagelActivityScoring.java:281) ~[matsim-13.0.jar:?]
	at org.matsim.core.scoring.SumScoringFunction.handleActivity(SumScoringFunction.java:99) ~[matsim-13.0.jar:?]
	at org.matsim.core.scoring.ScoringFunctionsForPopulation.handleActivity(ScoringFunctionsForPopulation.java:194) ~[matsim-13.0.jar:?]
	at org.matsim.core.scoring.EventsToActivities.handleEvent(EventsToActivities.java:85) ~[matsim-13.0.jar:?]
	at org.matsim.core.scoring.EventsToLegsAndActivities.handleEvent(EventsToLegsAndActivities.java:53) ~[matsim-13.0.jar:?]
	at org.matsim.core.events.EventsManagerImpl.callHandlerFast(EventsManagerImpl.java:283) ~[matsim-13.0.jar:?]
	at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:141) ~[matsim-13.0.jar:?]
	at org.matsim.core.events.SimStepParallelEventsManagerImpl$ProcessEventsRunnable.run(SimStepParallelEventsManagerImpl.java:330) ~[matsim-13.0.jar:?]
	at java.lang.Thread.run(Thread.java:832) ~[?:?]
2022-02-08T22:47:08,225 ERROR AbstractController:222 Mobsim did not complete normally! afterMobsimListeners will be called anyway.
java.lang.RuntimeException: java.util.concurrent.BrokenBarrierException
	at org.matsim.core.events.SimStepParallelEventsManagerImpl.afterSimStep(SimStepParallelEventsManagerImpl.java:234) ~[matsim-13.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.doSimStep(QSim.java:409) ~[matsim-13.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:254) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:211) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:243) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:207) [matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154) [matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121) [matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:81) [matsim-13.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-13.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89) [matsim-13.0.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-13.0.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-13.0.jar:?]
	at org.matsim.project.RunMatsim.main(RunMatsim.java:86) [classes/:?]
Caused by: java.util.concurrent.BrokenBarrierException
	at java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:250) ~[?:?]
	at java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:362) ~[?:?]
	at org.matsim.core.events.SimStepParallelEventsManagerImpl.afterSimStep(SimStepParallelEventsManagerImpl.java:232) ~[matsim-13.0.jar:?]
	... 15 more
2022-02-08T22:47:08,232  WARN CharyparNagelActivityScoring:228 There are opening or closing times defined for the first and last activity. The correctness of the scoring function can thus not be guaranteed.
2022-02-08T22:47:08,237  WARN CharyparNagelActivityScoring:229 first activity: act [type=home][coord=null][linkId=27924377_0][startTime=undefined][endTime=08:49:00][duration=undefined][facilityId=null]
2022-02-08T22:47:08,237  WARN CharyparNagelActivityScoring:230 last activity: act [type=home][coord=[x=434455.22 | y=4464104.55]][linkId=27924377_0][startTime=10:34:54][endTime=undefined][duration=undefined][facilityId=null]
2022-02-08T22:47:08,237  WARN CharyparNagelActivityScoring:246 The first and the last activity do not have the same type. 
2022-02-08T22:47:08,237  WARN CharyparNagelActivityScoring:247 Will score the first activity from midnight to its end, and the last activity from its start to midnight.
2022-02-08T22:47:08,237  WARN CharyparNagelActivityScoring:248 Because of the nonlinear function, this is not the same as scoring from start to end.
2022-02-08T22:47:08,237  WARN CharyparNagelActivityScoring:249 first activity: act [type=home][coord=null][linkId=27924377_0][startTime=undefined][endTime=07:00:00][duration=undefined][facilityId=null]
2022-02-08T22:47:08,237  WARN CharyparNagelActivityScoring:250 last activity: act [type=work][coord=[x=434632.0 | y=4463413.0]][linkId=932385639_2][startTime=07:53:00][endTime=undefined][duration=undefined][facilityId=null]
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:251 This may also happen when plans are not completed when the simulation ends.
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:253 Additional warnings of this type are suppressed.
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:228 There are opening or closing times defined for the first and last activity. The correctness of the scoring function can thus not be guaranteed.
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:229 first activity: act [type=home][coord=null][linkId=27924377_0][startTime=undefined][endTime=08:45:00][duration=undefined][facilityId=null]
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:230 last activity: act [type=home][coord=[x=434455.22 | y=4464104.55]][linkId=27924377_0][startTime=09:02:41][endTime=undefined][duration=undefined][facilityId=null]
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:228 There are opening or closing times defined for the first and last activity. The correctness of the scoring function can thus not be guaranteed.
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:229 first activity: act [type=home][coord=null][linkId=27924377_0][startTime=undefined][endTime=08:45:00][duration=undefined][facilityId=null]
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:230 last activity: act [type=home][coord=[x=434455.22 | y=4464104.55]][linkId=27924377_0][startTime=09:02:47][endTime=undefined][duration=undefined][facilityId=null]
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:228 There are opening or closing times defined for the first and last activity. The correctness of the scoring function can thus not be guaranteed.
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:229 first activity: act [type=home][coord=null][linkId=318509655_0][startTime=undefined][endTime=06:00:00][duration=undefined][facilityId=null]
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:230 last activity: act [type=home][coord=[x=434385.15 | y=4464116.94]][linkId=318509655_0][startTime=06:29:57][endTime=undefined][duration=undefined][facilityId=null]
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:228 There are opening or closing times defined for the first and last activity. The correctness of the scoring function can thus not be guaranteed.
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:229 first activity: act [type=home][coord=null][linkId=318509655_0][startTime=undefined][endTime=09:30:00][duration=undefined][facilityId=null]
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:230 last activity: act [type=home][coord=[x=434385.15 | y=4464116.94]][linkId=318509655_0][startTime=09:59:52][endTime=undefined][duration=undefined][facilityId=null]
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:228 There are opening or closing times defined for the first and last activity. The correctness of the scoring function can thus not be guaranteed.
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:229 first activity: act [type=home][coord=null][linkId=318509655_0][startTime=undefined][endTime=08:00:00][duration=undefined][facilityId=null]
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:230 last activity: act [type=home][coord=[x=434385.15 | y=4464116.94]][linkId=318509655_0][startTime=08:24:30][endTime=undefined][duration=undefined][facilityId=null]
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:228 There are opening or closing times defined for the first and last activity. The correctness of the scoring function can thus not be guaranteed.
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:229 first activity: act [type=home][coord=null][linkId=27924377_0][startTime=undefined][endTime=07:45:00][duration=undefined][facilityId=null]
2022-02-08T22:47:08,238  WARN CharyparNagelActivityScoring:230 last activity: act [type=home][coord=[x=434436.61 | y=4464064.96]][linkId=27924377_0][startTime=08:30:52][endTime=undefined][duration=undefined][facilityId=null]
2022-02-08T22:47:08,239  WARN CharyparNagelActivityScoring:228 There are opening or closing times defined for the first and last activity. The correctness of the scoring function can thus not be guaranteed.
2022-02-08T22:47:08,239  WARN CharyparNagelActivityScoring:229 first activity: act [type=home][coord=null][linkId=27924377_0][startTime=undefined][endTime=09:00:00][duration=undefined][facilityId=null]
2022-02-08T22:47:08,239  WARN CharyparNagelActivityScoring:230 last activity: act [type=home][coord=[x=434436.61 | y=4464064.96]][linkId=27924377_0][startTime=09:30:52][endTime=undefined][duration=undefined][facilityId=null]
2022-02-08T22:47:08,239  WARN CharyparNagelActivityScoring:228 There are opening or closing times defined for the first and last activity. The correctness of the scoring function can thus not be guaranteed.
2022-02-08T22:47:08,239  WARN CharyparNagelActivityScoring:229 first activity: act [type=home][coord=null][linkId=27924377_0][startTime=undefined][endTime=08:30:00][duration=undefined][facilityId=null]
2022-02-08T22:47:08,239  WARN CharyparNagelActivityScoring:230 last activity: act [type=home][coord=[x=434436.61 | y=4464064.96]][linkId=27924377_0][startTime=10:10:52][endTime=undefined][duration=undefined][facilityId=null]
2022-02-08T22:47:08,239  WARN CharyparNagelActivityScoring:228 There are opening or closing times defined for the first and last activity. The correctness of the scoring function can thus not be guaranteed.
2022-02-08T22:47:08,239  WARN CharyparNagelActivityScoring:229 first activity: act [type=home][coord=null][linkId=27924377_0][startTime=undefined][endTime=08:30:00][duration=undefined][facilityId=null]
2022-02-08T22:47:08,239  WARN CharyparNagelActivityScoring:230 last activity: act [type=home][coord=[x=434436.61 | y=4464064.96]][linkId=27924377_0][startTime=09:08:51][endTime=undefined][duration=undefined][facilityId=null]
2022-02-08T22:47:08,239  WARN CharyparNagelActivityScoring:228 There are opening or closing times defined for the first and last activity. The correctness of the scoring function can thus not be guaranteed.
2022-02-08T22:47:08,239  WARN CharyparNagelActivityScoring:229 first activity: act [type=home][coord=null][linkId=165263316_0][startTime=undefined][endTime=07:00:00][duration=undefined][facilityId=null]
2022-02-08T22:47:08,239  WARN CharyparNagelActivityScoring:230 last activity: act [type=home][coord=[x=434823.45 | y=4464615.41]][linkId=165263316_0][startTime=07:14:27][endTime=undefined][duration=undefined][facilityId=null]
2022-02-08T22:47:08,239  WARN CharyparNagelActivityScoring:232 Additional warnings of this type are suppressed.
2022-02-08T22:47:08,240 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
java.lang.RuntimeException: java.util.concurrent.BrokenBarrierException
	at org.matsim.core.events.SimStepParallelEventsManagerImpl.afterSimStep(SimStepParallelEventsManagerImpl.java:234) ~[matsim-13.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.doSimStep(QSim.java:409) ~[matsim-13.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:254) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:211) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:243) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:207) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:81) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-13.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89) [matsim-13.0.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-13.0.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-13.0.jar:?]
	at org.matsim.project.RunMatsim.main(RunMatsim.java:86) [classes/:?]
Caused by: java.util.concurrent.BrokenBarrierException
	at java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:250) ~[?:?]
	at java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:362) ~[?:?]
	at org.matsim.core.events.SimStepParallelEventsManagerImpl.afterSimStep(SimStepParallelEventsManagerImpl.java:232) ~[matsim-13.0.jar:?]
	... 15 more
2022-02-08T22:47:08,240 ERROR MatsimRuntimeModifications:81 ERROR --- This is an unexpected shutdown!
2022-02-08T22:47:08,240 ERROR MatsimRuntimeModifications:84 Shutdown possibly caused by the following Exception:
java.lang.RuntimeException: java.util.concurrent.BrokenBarrierException
	at org.matsim.core.events.SimStepParallelEventsManagerImpl.afterSimStep(SimStepParallelEventsManagerImpl.java:234) ~[matsim-13.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.doSimStep(QSim.java:409) ~[matsim-13.0.jar:?]
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:254) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:211) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:243) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:207) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:81) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-13.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89) [matsim-13.0.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-13.0.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-13.0.jar:?]
	at org.matsim.project.RunMatsim.main(RunMatsim.java:86) [classes/:?]
Caused by: java.util.concurrent.BrokenBarrierException
	at java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:250) ~[?:?]
	at java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:362) ~[?:?]
	at org.matsim.core.events.SimStepParallelEventsManagerImpl.afterSimStep(SimStepParallelEventsManagerImpl.java:232) ~[matsim-13.0.jar:?]
	... 15 more
2022-02-08T22:47:08,264 ERROR MatsimRuntimeModifications:99 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2022-02-08T22:47:08,264 ERROR MatsimRuntimeModifications:100 ERROR --- results should not be used for further analysis.
2022-02-08T22:47:08,264 ERROR MatsimRuntimeModifications:104 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.BrokenBarrierException
	at org.matsim.core.events.SimStepParallelEventsManagerImpl.afterSimStep(SimStepParallelEventsManagerImpl.java:234)
	at org.matsim.core.mobsim.qsim.QSim.doSimStep(QSim.java:409)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:254)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:124)
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:211)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:243)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:207)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:81)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89)
	at org.matsim.core.controler.NewControler.run(NewControler.java:82)
	at org.matsim.core.controler.Controler.run(Controler.java:249)
	at org.matsim.project.RunMatsim.main(RunMatsim.java:86)
Caused by: java.util.concurrent.BrokenBarrierException
	at java.base/java.util.concurrent.CyclicBarrier.dowait(CyclicBarrier.java:250)
	at java.base/java.util.concurrent.CyclicBarrier.await(CyclicBarrier.java:362)
	at org.matsim.core.events.SimStepParallelEventsManagerImpl.afterthis SimStep(SimStepParallelEventsManagerImpl.java:232)
	... 15 more

The simulation did not run properly. Error/Exit code: 1

Also, this is the config file very similar to the example

<?xml version="1.0" ?>
<!DOCTYPE config SYSTEM "http://www.matsim.org/files/dtd/config_v2.dtd">
<config>

	<module name="global">
		<param name="randomSeed" value="4711" />
		<param name="coordinateSystem" value="UTM" />
	</module>

	<module name="network">
		<param name="inputNetworkFile" value="network.xml" />
	</module>

	<module name="plans">
		<param name="inputPlansFile" value="population_mini.xml" />
	</module>

	<module name="controler">
		<param name="outputDirectory" value="./output" />
		<param name="firstIteration" value="0" />
		<param name="lastIteration" value="10" />
	</module>

	<module name="qsim">
		
		<param name="startTime" value="00:00:00" />
		<param name="endTime" value="00:00:00" />
		<param name="storageCapacityFactor" value="1.00" />
		<param name="flowCapacityFactor" value="1.00" />

	
		<param name = "snapshotperiod"	value = "00:00:00"/> 
	</module>

	<module name="planCalcScore">
		
		<param name="learningRate" value="1.0" />
		<param name="BrainExpBeta" value="2.0" />

		<param name="lateArrival" value="-3" />
		<param name="earlyDeparture" value="-0" />
		<param name="performing" value="+6" />
		<param name="waiting" value="-0" />
		<parameterset type="activityParams" >
			<param name="activityType"            value="home" /> 
			<param name="priority"        value="1" />
			<param name="typicalDuration" value="11:00:00" />
			<param name="openingTime"     value="20:00:00" />
			<param name="latestStartTime" value="07:00:00" />
		</parameterset>
		<parameterset type="activityParams" >
			<param name="activityType"            value="work" /> 
			<param name="priority"        value="1" />
			<param name="typicalDuration" value="8:00:00" />
			<param name="openingTime"     value="9:00:00" />
			<param name="latestStartTime" value="10:00:00" />
			<param name="earliestEndTime" value="15:00:00" />
			
		</parameterset>
		<parameterset type="activityParams" >
			<param name="activityType"            value="education" /> 
			<param name="priority"        value="1" />
			<param name="typicalDuration" value="08:00:00" />
			<param name="openingTime"     value="08:00:00" />
			<param name="latestStartTime" value="09:00:00" />
			<param name="earliestEndTime" value="16:00:00" />
	
		</parameterset>
<parameterset type="activityParams" >
			<param name="activityType"            value="leisure" /> 
			<param name="priority"        value="2" />
			<param name="typicalDuration" value="3:00:00" />
			<param name="openingTime"     value="17:00:00" />
			<param name="latestStartTime" value="20:00:00" />
			<param name="earliestEndTime" value="18:00:00" />
		</parameterset>
<parameterset type="activityParams" >
			<param name="activityType"            value="shopping" /> 
			<param name="priority"        value="2" />
			<param name="typicalDuration" value="1:00:00" />
			<param name="openingTime"     value="17:00:00" />
			<param name="latestStartTime" value="20:00:00" />
			<param name="earliestEndTime" value="21:00:00" />
	
		</parameterset>
	</module>
	
	<module name="strategy">
		<param name="maxAgentPlanMemorySize" value="0" /> 

		<param name="ModuleProbability_1" value="0.9" />
		<param name="Module_1" value="BestScore" />

		<param name="ModuleProbability_2" value="0.1" />
		<param name="Module_2" value="ReRoute" />
	</module>

</config>

**Comment by 100330627** [comment]
The first error looks smth like this: 

ERROR BasicPlanAgentImpl:184 last activity of person driver agent id 6 has end time < infty; setting it to infty

However, it was not set to infinity before and it performed with 30 agents and now I did it and still does not work

**Comment by michalmac** [comment]
> ERROR BasicPlanAgentImpl:184 last activity of person driver agent id 6 has end time < infty; setting it to infty

This is an error in the plan, but matsim "fixes" it and continues. 

The actual error is this:
> acttype "medical" is not known in utility parameters

You need to configure all activity types in the config (now there is only: work, home, education)
