### ISSUE TITLE
Error: undefined time

### ISSUE THREAD

**Issue by fayexin** [matsim-org/matsim-code-examples#723]
Hi, 

I am facing a  program error, and it shows an undefined time. What would could this problem be?

This is the log file with warnings and errors:

2022-05-08T09:53:09,642 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.0 died with exception while handling events.
java.util.NoSuchElementException: Undefined time
	at org.matsim.core.utils.misc.OptionalTime.seconds(OptionalTime.java:69) ~[matsim-13.0.jar:?]
	at org.matsim.core.router.TripRouter.calcEndOfPlanElement(TripRouter.java:216) ~[matsim-13.0.jar:?]
	at org.matsim.core.router.PlanRouter.calcEndOfActivity(PlanRouter.java:167) ~[matsim-13.0.jar:?]
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:98) ~[matsim-13.0.jar:?]
	at org.matsim.core.population.algorithms.PersonPrepareForSim.run(PersonPrepareForSim.java:220) ~[matsim-13.0.jar:?]
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils$PersonAlgoThread.run(ParallelPersonAlgorithmUtils.java:145) ~[matsim-13.0.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2022-05-08T09:53:14,538 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.1 died with exception while handling events.
java.util.NoSuchElementException: Undefined time
	at org.matsim.core.utils.misc.OptionalTime.seconds(OptionalTime.java:69) ~[matsim-13.0.jar:?]
	at org.matsim.core.router.TripRouter.calcEndOfPlanElement(TripRouter.java:216) ~[matsim-13.0.jar:?]
	at org.matsim.core.router.PlanRouter.calcEndOfActivity(PlanRouter.java:167) ~[matsim-13.0.jar:?]
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:98) ~[matsim-13.0.jar:?]
	at org.matsim.core.population.algorithms.PersonPrepareForSim.run(PersonPrepareForSim.java:220) ~[matsim-13.0.jar:?]
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils$PersonAlgoThread.run(ParallelPersonAlgorithmUtils.java:145) ~[matsim-13.0.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
2022-05-08T09:53:14,540 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
java.lang.RuntimeException: Exception while processing persons. Cannot guarantee that all persons have been fully processed.
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils.run(ParallelPersonAlgorithmUtils.java:120) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.PrepareForSimImpl.run(PrepareForSimImpl.java:172) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:113) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-13.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89) [matsim-13.0.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-13.0.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-13.0.jar:?]
	at org.matsim.run.smart_city.RunSmartCityTest_withPT.main(RunSmartCityTest_withPT.java:65) [classes/:?]
2022-05-08T09:53:14,540 ERROR MatsimRuntimeModifications:81 ERROR --- This is an unexpected shutdown!
2022-05-08T09:53:14,540 ERROR MatsimRuntimeModifications:84 Shutdown possibly caused by the following Exception:
java.lang.RuntimeException: Exception while processing persons. Cannot guarantee that all persons have been fully processed.
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils.run(ParallelPersonAlgorithmUtils.java:120) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.PrepareForSimImpl.run(PrepareForSimImpl.java:172) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.NewControler.prepareForSim(NewControler.java:113) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:80) ~[matsim-13.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69) [matsim-13.0.jar:?]
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52) [matsim-13.0.jar:?]
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89) [matsim-13.0.jar:?]
	at org.matsim.core.controler.NewControler.run(NewControler.java:82) [matsim-13.0.jar:?]
	at org.matsim.core.controler.Controler.run(Controler.java:249) [matsim-13.0.jar:?]
	at org.matsim.run.smart_city.RunSmartCityTest_withPT.main(RunSmartCityTest_withPT.java:65) [classes/:?]
2022-05-08T09:53:14,679 ERROR MatsimRuntimeModifications:99 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2022-05-08T09:53:14,679 ERROR MatsimRuntimeModifications:100 ERROR --- results should not be used for further analysis.
2022-05-08T09:53:14,679 ERROR MatsimRuntimeModifications:104 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.

**Comment by Janekdererste** [comment]
This usually indicates, that your activity durations are not properly defined. Usually, You need start and end time. Alternatively, you can either specify either start or end time and a duration for each activity.
