### ISSUE TITLE
Simulation didn't run properly. Error/Exit code:1

### ISSUE THREAD

**Issue by ElsayedAbulela** [matsim-org/matsim-code-examples#739]
Hello everyone,
I have a problem when I am trying to run some codes such as berlin. I attached all the warnings and errors that appeared while running on MATSim GUI.

2022-06-10T08:41:17,250  WARN PlansCalcRouteConfigGroup:342 The first mode routing params that are explicitly defined clear the default mode routing params.  This functionality was removed for 
2022-06-10T08:41:17,252  WARN PlansCalcRouteConfigGroup:343     some weeks in the development head, after release 11.x, and before release 12.x; it is now back.  If you want to avoid this 
2022-06-10T08:41:17,253  WARN PlansCalcRouteConfigGroup:344     warning, use clearModeRoutingParams(true) in code, and "clearDefaultTeleportedModeParams"=true in xml config.
2022-06-10T08:41:21,076  WARN LinkImpl:116 permlanes=0.5 of link id 100231 may cause problems
2022-06-10T08:41:21,076  WARN LinkImpl:118  Future occurences of this logging statement are suppressed.
2022-06-10T08:41:23,873  WARN LinkImpl:125 length=0.0 of link id pt_0 may cause problems
2022-06-10T08:41:23,874  WARN LinkImpl:127  Future occurences of this logging statement are suppressed.
2022-06-10T08:41:25,152  WARN PopulationReaderMatsimV6:213 coordinate transformation defined both in config and in input file: setting from input file will be used
2022-06-10T08:48:06,003  WARN VspConfigConsistencyCheckerImpl:100 you are not using FastAStarLandmarks as routing algorithm.  vsp default is to use FastAStarLandmarks.
2022-06-10T08:48:06,006  WARN VspConfigConsistencyCheckerImpl:201 You are not setting fractionOfIterationsToStartScoreMSA; vsp default is to set this to something like 0.8.  This means you have to add the following lines to your config file: 
2022-06-10T08:48:06,006  WARN VspConfigConsistencyCheckerImpl:203 <module name="planCalcScore">
2022-06-10T08:48:06,006  WARN VspConfigConsistencyCheckerImpl:204 	<param name="fractionOfIterationsToStartScoreMSA" value="0.8" />
2022-06-10T08:48:06,007  WARN VspConfigConsistencyCheckerImpl:205 </module>
2022-06-10T08:48:06,007  WARN VspConfigConsistencyCheckerImpl:247 found `PlansCalcRouteConfigGroup.AccessEgressType.none'; vsp should use `accessEgressModeToLink' or some other value or talk to Kai.
2022-06-10T08:48:06,007  WARN VspConfigConsistencyCheckerImpl:254 found qsim.usePersonIdForMissingVehicleId==true; this is only for backwards compatibility and should rather be set to false
2022-06-10T08:48:06,007  WARN VspConfigConsistencyCheckerImpl:259 found `qsim.usingTravelTimeCheckInTeleporation==false'; vsp should try out `true' and report.
2022-06-10T08:48:06,008 FATAL VspConfigConsistencyCheckerImpl:371 found a situation that leads to vsp-abort.  aborting ...
Exception in thread "main" java.lang.RuntimeException: found a situation that leads to vsp-abort.  aborting ...
	at org.matsim.core.config.consistency.VspConfigConsistencyCheckerImpl.checkConsistency(VspConfigConsistencyCheckerImpl.java:372)
	at org.matsim.core.config.Config.checkConsistency(Config.java:211)
	at org.matsim.core.controler.Controler.run(Controler.java:230)
	at org.matsim.project.RunMatsim.main(RunMatsim.java:72)

The simulation did not run properly. Error/Exit code: 1

**Comment by Janekdererste** [comment]
Looks like the berlin scenario has a consistency checker enabled, which we use internally to make sure our configurations adhere to a certain standard. 

Could you point to the config and the run class you've used?

**Comment by ElsayedAbulela** [comment]
> Looks like the berlin scenario has a consistency checker enabled, which we use internally to make sure our configurations adhere to a certain standard.
> 
> Could you point to the config and the run class you've used?

Firstly, Thanks for your response,
This problem has happened in many scenarios like Berlin, Los Angeles, and Kelheim.
Here, I am going to attach the link of the Kelheim config file for 25 pct.

https://github.com/matsim-scenarios/matsim-kelheim/blob/master/scenarios/input/kelheim-v2.x-25pct.config.xml

**Comment by Janekdererste** [comment]
I can't spot the exact error from the log and the config. Maybe @simei94 or @tschlenther can help here, since they work with the kehlheim scenario.
