### ISSUE TITLE
Unexpected shutdown due to replanning issues & no traveled distance outcome

### ISSUE THREAD

**Issue by sarah-heejeong** [matsim-org/matsim-code-examples#746]
Hello,

I keep getting an error saying that the simulation has stopped as I have not defined a replanning strategy.
```

2022-06-14T16:38:36,383 ERROR MatsimRuntimeModifications:100 ERROR --- results should not be used for further analysis.
2022-06-14T16:38:36,383  INFO MatsimRuntimeModifications:102 S H U T D O W N   ---   shutdown completed.
2022-06-14T16:38:36,383 ERROR MatsimRuntimeModifications:104 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
Exception in thread "main" java.lang.RuntimeException: No strategy found! Have you defined at least one replanning strategy per subpopulation? Current subpopulation = null
	at org.matsim.core.replanning.GenericStrategyManager.run(GenericStrategyManager.java:214)
	at org.matsim.core.replanning.StrategyManager.run(StrategyManager.java:191)
	at org.matsim.core.replanning.StrategyManager.run(StrategyManager.java:173)
	at org.matsim.core.controler.corelisteners.PlansReplanningImpl.notifyReplanning(PlansReplanningImpl.java:58)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerReplanningEvent(ControlerListenerManagerImpl.java:206)
	at org.matsim.core.controler.AbstractController$3.run(AbstractController.java:149)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:243)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:146)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:81)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89)
	at org.matsim.core.controler.NewControler.run(NewControler.java:82)
	at org.matsim.core.controler.Controler.run(Controler.java:249)
	at org.matsim.project.RunMatsim.main(RunMatsim.java:86)

The simulation did not run properly. Error/Exit code: 1
```

I built the config.xml file by modifying the one in sweden scenario, but used my own network and population files and changed some parameters in config.xml accordingly. 

Another issue I face is that I still get the output data, but the traveled distance doesn't give me any information (photo attached).
![route_206 traveldistancestatstrips](https://user-images.githubusercontent.com/70648901/173633165-26624f07-6724-4208-bad2-bee4b2d846c4.png)
Does that mean I put the wrong coordinate value when setting up the plan in population.xml, or my network.xml file doesn't work properly?

Thank you.

**Comment by Janekdererste** [comment]
We need more information to help. Please share at least the config.xml, so that I can have a look at it. Even better would be to have the entire scenario (all input files) and your run class. 

It might be the case that your travelled distance issue will be solved after we fix your config.xml

**Comment by sarah-heejeong** [comment]
Hi @Janekdererste, 

Thank you for your response. 
I have attached the input data files I ran.
[Input.zip](https://github.com/matsim-org/matsim-code-examples/files/8907783/Input.zip)

+
Do you mind going over `population.xml` file if I wrote the codes correctly for my plan?
I'm trying to build the scenario with one agent driving a vehicle.
This agent leaves "home" at a fixed time (07:08:47, for this scenario), and arrives at "work" at 14:47:34, but goes back home as soon as the agent arrives home.
Can I have some suggestions to set how long it should take to arrive at "work" or specify the nodes that the agent should use to get the destination?
One possible error I am assuming is the coordinates of "home" and "work" are not those of facilities, but in the middle of the highways?
