### ISSUE TITLE
MATSim Error v0.10

### ISSUE THREAD

**Issue by Vuduong96** [matsim-org/matsim-code-examples#762]
Hi there, I am using MATSim 0.10 with java 17 and I have the following error after the line "controler.run()", do you know how to fix this? Thank you

Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.getProtectionDomain(FastClass.java:73)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:206)
	at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:65)
	at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:252)
	at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:203)
	at com.google.inject.internal.ProviderMethod.create(ProviderMethod.java:69)
	at com.google.inject.internal.ProviderMethodsModule.createProviderMethod(ProviderMethodsModule.java:275)
	at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:144)
	at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:123)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:349)
	at org.matsim.core.controler.AbstractModule.install(AbstractModule.java:124)
	at org.matsim.core.mobsim.DefaultMobsimModule.install(DefaultMobsimModule.java:36)
	at org.matsim.core.controler.AbstractModule.configure(AbstractModule.java:113)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at org.matsim.core.controler.AbstractModule.install(AbstractModule.java:124)
	at org.matsim.core.controler.ControlerDefaultsModule.install(ControlerDefaultsModule.java:43)
	at org.matsim.core.controler.AbstractModule.configure(AbstractModule.java:113)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at org.matsim.core.controler.AbstractModule.install(AbstractModule.java:124)
	at org.matsim.core.controler.Controler$1.install(Controler.java:195)
	at org.matsim.core.controler.AbstractModule.configure(AbstractModule.java:113)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at org.matsim.core.controler.AbstractModule$4.install(AbstractModule.java:241)
	at org.matsim.core.controler.AbstractModule.configure(AbstractModule.java:113)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.spi.Elements.getElements(Elements.java:101)
	at org.matsim.core.controler.Injector.createMapBindingsForType(Injector.java:107)
	at org.matsim.core.controler.Injector.insertMapBindings(Injector.java:99)
	at org.matsim.core.controler.Injector.createInjector(Injector.java:73)
	at org.matsim.core.controler.Controler.run(Controler.java:189)
	at au.gov.vic.ivabm.run.RunScenario.run(RunScenario.java:245)
	at au.gov.vic.ivabm.run.RunScenario.main(RunScenario.java:82)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @58134517
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at com.google.inject.internal.cglib.core.$ReflectUtils$1.run(ReflectUtils.java:52)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.google.inject.internal.cglib.core.$ReflectUtils.<clinit>(ReflectUtils.java:42)
	... 38 more

**Comment by Vuduong96** [comment]
Hi there,

I solved the problem. However, I run into a new one, which is out of memory. Do you know how to fix this? Thank you. 

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "PersonPrepareForSim.35"

**Comment by Janekdererste** [comment]
This error indicates that your program runs out of RAM. You can assign more ram to a Java program by using the `-Xmx` flag. To start your program with 20GB of ram, you could use the following command:
```
$ java -Xmx20G -cp /path/to/your.jar package.and.RunClass 
```
Note: You can assign more memory than your computer has ram available. This will be slow though.

**Comment by Vuduong96** [comment]
Hi there,

Thank you for your answer. Is this the same as setting Runtime Parameters for the Java Runtime Environment Window?

**Comment by Vuduong96** [comment]
I would like to scale down my simulation. Which file should I adjust? I have reduced the # of iterations, and population file, but it is not enough. 

Thank you

**Comment by michalmac** [comment]
> I solved the problem. However, I run into a new one, which is out of memory. Do you know how to fix this? Thank you.

How did you solve this problem? matsim 0.10 does not work on java 17 (i.e. JDK 17). Right now only matsim 14.0 runs with JDK 17. Have you downgraded your Java?

>  Is this the same as setting Runtime Parameters for the Java Runtime Environment Window?

Java Control Panel was removed in Java 11. I do not have it, so I cannot say. I suggest you to follow this advice: https://github.com/matsim-org/matsim-code-examples/issues/762#issuecomment-1180131551 as it works regardless of what Java version you have.

**Comment by Vuduong96** [comment]
Hi there,

Yes, I did downgrade my java to java 8.  And I also download separated jre and added to use in the project, then it worked. 
I have a question regarding the .jar path, do I need to export my .jar file from the current project and then copy the path to run the command above?

Thank you

**Comment by michalmac** [comment]
> I have a question regarding the .jar path, do I need to export my .jar file from the current project and then copy the path to run the command above?

Yes, given that your IDE offers something like exporting a whole project as one fat jar containing everything.
Otherwise, you may use the maven shade plugin to create such a jar: https://maven.apache.org/plugins/maven-shade-plugin/usage.html

**Comment by Janekdererste** [comment]
> Yes, I did downgrade my java to java 8

If you don't have a special reason to use matsim 0.10, I would recommend to switch to the most recent version, wich is 14. This version will run with the most recent (17) Java version.

**Comment by Vuduong96** [comment]
Hi There,

I have special reason to use matsim 0.10 cause the code that I am working on was built using this version. It is quite a complex project. 

I will try to rebuild the code using the new version. Thank you
