### ISSUE TITLE
Pt-Drt model

### ISSUE THREAD

**Issue by ghost** [matsim-org/matsim-code-examples#763]
Hello, 
When simulating a model with pt (busses) and drt, passengers have to use pt in their initial plans, but they have the right to change to drt when a pt is not the optimal choice. I got this error:

```
ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.0 died with exception. Will stop after all threads finished.
java.lang.NullPointerException: link: 7331 does not exist in the network of mode: drt
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:1243) ~[guava-30.0-jre.jar:?]
	at org.matsim.contrib.dvrp.router.DefaultMainLegRouter.calcRoute(DefaultMainLegRouter.java:74) ~[dvrp-14.0-PR1674.jar:?]
	at org.matsim.contrib.dvrp.router.DvrpRoutingModule.calcRoute(DvrpRoutingModule.java:120) ~[dvrp-14.0-PR1674.jar:?]
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:182) ~[matsim-14.0-PR1674.jar:?]
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:101) ~[matsim-14.0-PR1674.jar:?]
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234) ~[matsim-14.0-PR1674.jar:?] at java.lang.Thread.run(Thread.java:834) [?:?]
```
It says that link 7331 doesn't exist in the network of mode drt, but in my network drt is allowed at all the links including 7331! Is there any hidden issue behind this error?

Thank you.

**Comment by michalmac** [comment]
Can you share your network and config files?
