### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vuduong96** [matsim-org/matsim-code-examples#769]
Hello Dev Team, 

This is my error, I got this error when I run one of scenario. I do not know where should I have a look?

Thank you for your time

2022-08-03 20:48:27,772 ERROR ParallelPersonAlgorithmUtils$ExceptionHandler:164 Thread PersonPrepareForSim.0 died with exception while handling events.
java.lang.RuntimeException: 657.4271989218494 m is not covered by any egress / access mode.
	at org.matsim.contrib.av.intermodal.router.FixedDistanceBasedVariableAccessModule.getModeForDistance(FixedDistanceBasedVariableAccessModule.java:132)
	at org.matsim.contrib.av.intermodal.router.FixedDistanceBasedVariableAccessModule.getAccessEgressModeAndTraveltime(FixedDistanceBasedVariableAccessModule.java:94)
	at org.matsim.contrib.av.intermodal.router.VariableAccessTransitRouterImpl.getAccessEgressLeg(VariableAccessTransitRouterImpl.java:120)
	at org.matsim.contrib.av.intermodal.router.VariableAccessTransitRouterImpl.locateWrappedNearestTransitNodes(VariableAccessTransitRouterImpl.java:100)
	at org.matsim.contrib.av.intermodal.router.VariableAccessTransitRouterImpl.calcRoute(VariableAccessTransitRouterImpl.java:135)
	at org.matsim.contrib.av.intermodal.router.VariableAccessTransitRouterWrapper.calcRoute(VariableAccessTransitRouterWrapper.java:95)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:217)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:87)
	at org.matsim.core.population.algorithms.PersonPrepareForSim.run(PersonPrepareForSim.java:141)
	at org.matsim.core.population.algorithms.ParallelPersonAlgorithmUtils$PersonAlgoThread.run(ParallelPersonAlgorithmUtils.java:145)
	at java.lang.Thread.run(Unknown Source)

**Comment by Janekdererste** [comment]
Please provide your config, population, network and logfile, so that I can take a look.
