### ISSUE TITLE
otfvis can not run example 

### ISSUE THREAD

**Issue by ywf** [matsim-org/matsim-code-examples#797]
Hello, I have met with an error when i run otfvis example.the error is as follows 
`
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1
	at jogamp.opengl.windows.wgl.awt.WindowsAWTWGLGraphicsConfigurationFactory.chooseGraphicsConfigurationImpl(WindowsAWTWGLGraphicsConfigurationFactory.java:171)
	at com.jogamp.nativewindow.GraphicsConfigurationFactory.chooseGraphicsConfiguration(GraphicsConfigurationFactory.java:424)
	at com.jogamp.opengl.awt.GLCanvas.chooseGraphicsConfiguration(GLCanvas.java:1513)
	at com.jogamp.opengl.awt.GLCanvas.addNotify(GLCanvas.java:609)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/javax.swing.JRootPane.addNotify(JRootPane.java:729)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/java.awt.Window.addNotify(Window.java:791)
	at java.desktop/java.awt.Frame.addNotify(Frame.java:495)
	at java.desktop/java.awt.Window.pack(Window.java:829)
	at org.matsim.vis.otfvis.OTFClientLive$1.run(OTFClientLive.java:104)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

`
Thanks

**Comment by abdelkader4004** [comment]
I'am also getting similar problem when enabling OTFVis

2023-01-02T13:56:09,130 ERROR MatsimRuntimeModifications$1:62 Getting uncaught Exception in Thread AWT-EventQueue-0
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1
	at jogamp.opengl.windows.wgl.awt.WindowsAWTWGLGraphicsConfigurationFactory.chooseGraphicsConfigurationImpl(WindowsAWTWGLGraphicsConfigurationFactory.java:171) ~[jogl-all-2.4.0-matsim-1.jar:2.4.0-rc-20200306]
	at com.jogamp.nativewindow.GraphicsConfigurationFactory.chooseGraphicsConfiguration(GraphicsConfigurationFactory.java:424) ~[jogl-all-2.4.0-matsim-1.jar:2.4.0-rc-20200306]
	at com.jogamp.opengl.awt.GLCanvas.chooseGraphicsConfiguration(GLCanvas.java:1513) ~[jogl-all-2.4.0-matsim-1.jar:2.4.0-rc-20200306]
	at com.jogamp.opengl.awt.GLCanvas.addNotify(GLCanvas.java:609) ~[jogl-all-2.4.0-matsim-1.jar:2.4.0-rc-20200306]
	at java.awt.Container.addNotify(Container.java:2804) ~[?:?]
	at javax.swing.JComponent.addNotify(JComponent.java:4846) ~[?:?]
	at java.awt.Container.addNotify(Container.java:2804) ~[?:?]
	at javax.swing.JComponent.addNotify(JComponent.java:4846) ~[?:?]
	at java.awt.Container.addNotify(Container.java:2804) ~[?:?]
	at javax.swing.JComponent.addNotify(JComponent.java:4846) ~[?:?]
	at java.awt.Container.addNotify(Container.java:2804) ~[?:?]
	at javax.swing.JComponent.addNotify(JComponent.java:4846) ~[?:?]
	at javax.swing.JRootPane.addNotify(JRootPane.java:721) ~[?:?]
	at java.awt.Container.addNotify(Container.java:2804) ~[?:?]
	at java.awt.Window.addNotify(Window.java:791) ~[?:?]
	at java.awt.Frame.addNotify(Frame.java:495) ~[?:?]
	at java.awt.Window.pack(Window.java:829) ~[?:?]
	at org.matsim.vis.otfvis.OTFClientLive$1.run(OTFClientLive.java:104) ~[otfvis-14.0.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:720) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:714) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]

**Comment by petrhaj** [comment]
Hey, I found a fix for Win 11 64-bit:
Put the following arguments to the VM arguments when running your script (In Eclipse: Run->Run Configurations->[your script]->Arguments->VM Arguments)

--add-exports java.base/java.lang=ALL-UNNAMED
--add-exports java.desktop/sun.awt=ALL-UNNAMED
--add-exports java.desktop/sun.java2d=ALL-UNNAMED

Hope it helps :-)

**Comment by abdelkader4004** [comment]
thank you, it works in windows 10 also.

**Comment by ZHYXNJD** [comment]
thanks a lot I have fixed that bug
