### ISSUE TITLE
PSIM

### ISSUE THREAD

**Issue by RGB3Q** [matsim-org/matsim-code-examples#804]
Hi, I have been trying to use PSIM to accelerate system evolving, I added the dependency through POM. Then initialized PSimConfigGroup() and added RunPSim(config,pSimConfigGroup).run() in my main function. But errors occurred.

I would really appreciate if anyone can show me the light.

The exception was as follows:

`Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Explicit bindings are required and org.matsim.contrib.pseudosimulation.mobsim.transitperformance.TransitEmulator is not explicitly bound.
  while locating org.matsim.contrib.pseudosimulation.mobsim.transitperformance.TransitEmulator
    for field at org.matsim.contrib.pseudosimulation.mobsim.PSimProvider.transitEmulator(PSimProvider.java:22)
  at org.matsim.contrib.pseudosimulation.RunPSim$1.install(RunPSim.java:90) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.contrib.pseudosimulation.RunPSim$1)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:237)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:242)
	at org.matsim.core.controler.Injector.createInjector(Injector.java:74)
	at org.matsim.core.controler.Controler.run(Controler.java:247)
	at org.matsim.contrib.pseudosimulation.RunPSim.run(RunPSim.java:121)
	at org.matsim.project.RunMatsim.main(RunMatsim.java:95)`

**Comment by Janekdererste** [comment]
This error comes from our dependency injection framework [guice](https://github.com/google/guice/wiki/Motivation). 

The error message complains, that there was no `TransitEmulator` specified in your set up. Please provide a link to your repository as well as to the run class you were executing, then I will have a look at your set up.

**Comment by RGB3Q** [comment]
> This error comes from our dependency injection framework [guice](https://github.com/google/guice/wiki/Motivation).
> 
> The error message complains, that there was no `TransitEmulator` specified in your set up. Please provide a link to your repository as well as to the run class you were executing, then I will have a look at your set up.


Thanks, problem fixed now. It seems there were some dependencies not successfully installed though MAVEN due to network error
