### ISSUE TITLE
PT Sub-Modes error

### ISSUE THREAD

**Issue by RailRoadMan2882** [matsim-org/matsim-code-examples#844]
Hello!!

I was trying to define a monetary distance rate for different public transit sub modes (bus and train). However, after following the instruction in this link [differentiating-pt-sub-modes](https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions/blob/develop/README.md#differentiating-pt-sub-modes) , the below error occured.

-------------------------------------------------------------------------------------------------------------------------------------------------

Exception in thread "main" java.lang.NullPointerException
	at org.matsim.core.config.groups.PlanCalcScoreConfigGroup$ScoringParameterSet.getMarginalUtlOfWaitingPt_utils_hr(PlanCalcScoreConfigGroup.java:1358)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.matsim.core.config.ReflectiveConfigGroup.getValue(ReflectiveConfigGroup.java:350)
	at org.matsim.core.config.ConfigGroup.addParameterToMap(ConfigGroup.java:81)
	at org.matsim.core.config.ReflectiveConfigGroup.getParams(ReflectiveConfigGroup.java:408)
	at org.matsim.core.config.ConfigWriterHandlerImplV2.writeModule(ConfigWriterHandlerImplV2.java:81)
	at org.matsim.core.config.ConfigWriterHandlerImplV2.processParameterSets(ConfigWriterHandlerImplV2.java:154)
	at org.matsim.core.config.ConfigWriterHandlerImplV2.writeModule(ConfigWriterHandlerImplV2.java:95)
	at org.matsim.core.config.ConfigWriterHandlerImplV2.writeModule(ConfigWriterHandlerImplV2.java:297)
	at org.matsim.core.config.ConfigWriter.write(ConfigWriter.java:111)
	at org.matsim.core.config.ConfigWriter.writeStream(ConfigWriter.java:75)
	at org.matsim.core.controler.ControlerUtils.checkConfigConsistencyAndWriteToLog(ControlerUtils.java:82)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:79)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:69)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:52)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:89)
	at org.matsim.core.controler.NewControler.run(NewControler.java:82)
	at org.matsim.core.controler.Controler.run(Controler.java:249)
	at org.matsim.run.Controler.run(Controler.java:54)
	at org.matsim.run.Controler.main(Controler.java:58)

The simulation did not run properly. Error/Exit code: 1

------------------------------------------------------------------------------------------------------------------------------------------------

Could anyone please point out the cause of this error and the way to correct it?
Thank you in advanced.

P.S. The error code file is attached below.

[Error Model.zip](https://github.com/matsim-org/matsim-code-examples/files/10301951/Error.Model.zip)

and this is the working code file before the sub mode mapping.

[Working Model.zip](https://github.com/matsim-org/matsim-code-examples/files/10301961/Working.Model.zip)

**Comment by Janekdererste** [comment]
Can you try to set `waitingPt' explicitly in your config?

```
<module name="planCalcScore" >
		...
		<parameterset type="scoringParameters" >
			...
			<param name="waitingPt" value="-6.0" />
                        ...
		</parameterset>
</module>

**Comment by RailRoadMan2882** [comment]
>

**Comment by RailRoadMan2882** [comment]
> Can you try to set `waitingPt' explicitly in your config?
> 
> ```
> <module name="planCalcScore" >
> 		...
> 		<parameterset type="scoringParameters" >
> 			...
> 			<param name="waitingPt" value="-6.0" />
>                         ...
> 		</parameterset>
> </module>
> ```

I tried your method. However, the error remained the same.

**Comment by RailRoadMan2882** [comment]
I finally correct the error by adding `changeMode`. The code is attached below.
[Test Model.zip](https://github.com/matsim-org/matsim-code-examples/files/10336155/Test.Model.zip)
