### ISSUE TITLE
Issues with EV extensions

### ISSUE THREAD

**Issue by mkilani-dev** [matsim-org/matsim-code-examples#906]
Hi, 
I am running a simulation with EV extensions. It stops with an error at the end of iteration 0 with message given below. I am using the command line. Could you see the reason for this error.
Regards
Moez

2023-04-02T18:26:06,433  INFO Counter:69 [PersonPrepareForSim] handled person # 65536
2023-04-02T18:26:06,544  INFO Counter:69 [PersonPrepareForSim] handled person # 131072
2023-04-02T18:26:06,809  INFO Counter:69 [PersonPrepareForSim] handled person # 262144
2023-04-02T18:26:06,858  INFO Counter:74 [PersonPrepareForSim] handled person # 299071
2023-04-02T18:26:06,916 ERROR AbstractController:209 Mobsim did not complete normally! afterMobsimListeners will be called anyway.
java.lang.NoSuchMethodError: 'java.util.stream.Collector com.google.common.collect.ImmutableMap.toImmutableMap(java.util.function.Function, java.util.function.Function)'
    at org.matsim.contrib.ev.fleet.ElectricFleets.createDefaultFleet(ElectricFleets.java:39) ~[ev-12.0.jar:?]
    at org.matsim.contrib.ev.fleet.ElectricFleetModule$1$1.get(ElectricFleetModule.java:65) ~[ev-12.0.jar:?]
    at org.matsim.contrib.ev.fleet.ElectricFleetModule$1$1.get(ElectricFleetModule.java:53) ~[ev-12.0.jar:?]
    at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85) ~[guice-4.2.2.jar:?]
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:57) ~[guice-4.2.2.jar:?]
    at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59) ~[guice-4.2.2.jar:?]
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:47) ~[guice-4.2.2.jar:?]

**Comment by Janekdererste** [comment]
This is most probably a version conflict with some dependency. Which MATSim Version are you using?

**Comment by mkilani-dev** [comment]
Matsim 12.0 and ev-12.0

With matsim 14.0 (and the same ev package) I obtain another error:

2023-04-03T10:14:45,078  INFO PreProcessLandmarks:163 done in 910 ms
2023-04-03T10:14:45,082 ERROR MatsimRuntimeModifications:75 Getting uncaught Exception in Thread main
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NoSuchMethodError: 'boolean PlansCalcRouteConfigGroup.isInsertingAccessEgressWalk()'
  at TripRouter.<init>(TripRouter.java:104)
  while locating TripRouter

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
PlansCalcRouteConfigGroup: "org.matsim.core.config.groups.PlansCalcRouteConfigGroup"
TripRouter:                "org.matsim.core.router.TripRouter"

**Comment by Janekdererste** [comment]
I would advise to use the latest matsim version which is at least 14.0. The version of the ev-contrib and Matsim should be the same. Also, you should use java-17 or higher to run matsim 14.x. Can you please try with that configuration? 

Please attach the entire log file for the next error.

**Comment by mkilani-dev** [comment]
I cannot find where to download ev-14; do you have a link please ?

**Comment by Janekdererste** [comment]
It is part of the main matsim project https://github.com/matsim-org/matsim-libs/tree/master/contribs/ev
