### ISSUE TITLE
Running Emission Exception: Not yet implemented. Aborting...

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#910]
I got this weird error when running emission contrib. It seems like it is from pt vehicle but I am not sure... How should I correct it?

```
202023-04-04T18:45:04,117  WARN ColdEmissionHandler:137 No vehicle defined for id veh_14927_bus. The vehicle will be ignored.
Exception in thread "main" java.lang.RuntimeException: Not yet implemented. Aborting...
	at org.matsim.contrib.emissions.ColdEmissionHandler.handleNullVehicleECG(ColdEmissionHandler.java:143)
	at org.matsim.contrib.emissions.ColdEmissionHandler.handleEvent(ColdEmissionHandler.java:189)
	at org.matsim.core.events.EventsManagerImpl.callHandlerFast(EventsManagerImpl.java:252)
	at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:119)
	at org.matsim.core.events.EventsReaderXMLv1.startEvent(EventsReaderXMLv1.java:118)
	at org.matsim.core.events.EventsReaderXMLv1.startTag(EventsReaderXMLv1.java:80)
	at org.matsim.core.events.MatsimEventsReader$XmlEventsReader.startTag(MatsimEventsReader.java:141)
	at org.matsim.core.utils.io.MatsimXmlParser.startElement(MatsimXmlParser.java:348)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:198)
	at org.matsim.core.utils.io.MatsimXmlParser.readFile(MatsimXmlParser.java:150)
	at org.matsim.core.events.MatsimEventsReader.readFile(MatsimEventsReader.java:80)
	at org.matsim.emission.RunAverageEmissionToolOfflineExample.main(RunAverageEmissionToolOfflineExample.java:169)
23-04-04T18:45:04,117  WARN ColdEmissionHandler:137 No vehicle defined for id veh_14927_bus. The vehicle will be ignored.
Exception in thread "main" java.lang.RuntimeException: Not yet implemented. Aborting...
	at org.matsim.contrib.emissions.ColdEmissionHandler.handleNullVehicleECG(ColdEmissionHandler.java:143)
	at org.matsim.contrib.emissions.ColdEmissionHandler.handleEvent(ColdEmissionHandler.java:189)
	at org.matsim.core.events.EventsManagerImpl.callHandlerFast(EventsManagerImpl.java:252)
	at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:119)
	at org.matsim.core.events.EventsReaderXMLv1.startEvent(EventsReaderXMLv1.java:118)
	at org.matsim.core.events.EventsReaderXMLv1.startTag(EventsReaderXMLv1.java:80)
	at org.matsim.core.events.MatsimEventsReader$XmlEventsReader.startTag(MatsimEventsReader.java:141)
	at org.matsim.core.utils.io.MatsimXmlParser.startElement(MatsimXmlParser.java:348)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:198)
	at org.matsim.core.utils.io.MatsimXmlParser.readFile(MatsimXmlParser.java:150)
	at org.matsim.core.events.MatsimEventsReader.readFile(MatsimEventsReader.java:80)
	at org.matsim.emission.RunAverageEmissionToolOfflineExample.main(RunAverageEmissionToolOfflineExample.java:169)

```

BTW, I have already set the below config:

`emissionsConfig.setNonScenarioVehicles( EmissionsConfigGroup.NonScenarioVehicles.ignore );`

**Comment by kainagel** [comment]
which version of matsim are you using?

**Comment by jingjunL** [comment]
> which version of matsim are you using?

Hi Kai, the (nearest) latest version, actually. To be more specific, it is

`<matsim.version>15.0-2023w12</matsim.version>`

**Comment by kainagel** [comment]
Thanks.  To me this looks like a bug.  I found
```
        switch ( emissionsConfigGroup.getNonScenarioVehicles() ) {
            case abort:
                throw new RuntimeException(
                        "No vehicle defined for id " + vehicleId + ". " +
                                "Please make sure that requirements for emission vehicles in " + EmissionsConfigGroup.GROUP_NAME + " config group are met."
                                + " Or set the parameter + 'nonScenarioVehicles' to 'ignore' in order to skip such vehicles."
                                + " Aborting..." );
            case ignore:
                if ( noVehWarnCnt < 10 ){
                    logger.warn(
                            "No vehicle defined for id " + vehicleId + ". The vehicle will be ignored." );
                    noVehWarnCnt++;
                    if ( noVehWarnCnt == 10 ) logger.warn( Gbl.FUTURE_SUPPRESSED );
                } 
            default:
                throw new RuntimeException( "Not yet implemented. Aborting..." );
        }
```
To me, this looks like for the `ignore` case it will run into the `default` case anyways, and thus trigger the error.   I added the `break`.  See https://github.com/matsim-org/matsim-libs/pull/2490 .  Unfortunately, I don't have the time to add a test case for this.  Also, not sure if other tests may fail; we will see.  If there is no failing test, then PR-2490 will eventually be deployed, and you could try.

**Comment by jingjunL** [comment]
> Thanks. To me this looks like a bug. I found
> 
> ```
>         switch ( emissionsConfigGroup.getNonScenarioVehicles() ) {
>             case abort:
>                 throw new RuntimeException(
>                         "No vehicle defined for id " + vehicleId + ". " +
>                                 "Please make sure that requirements for emission vehicles in " + EmissionsConfigGroup.GROUP_NAME + " config group are met."
>                                 + " Or set the parameter + 'nonScenarioVehicles' to 'ignore' in order to skip such vehicles."
>                                 + " Aborting..." );
>             case ignore:
>                 if ( noVehWarnCnt < 10 ){
>                     logger.warn(
>                             "No vehicle defined for id " + vehicleId + ". The vehicle will be ignored." );
>                     noVehWarnCnt++;
>                     if ( noVehWarnCnt == 10 ) logger.warn( Gbl.FUTURE_SUPPRESSED );
>                 } 
>             default:
>                 throw new RuntimeException( "Not yet implemented. Aborting..." );
>         }
> ```
> 
> To me, this looks like for the `ignore` case it will run into the `default` case anyways, and thus trigger the error. I added the `break`. See [matsim-org/matsim-libs#2490](https://github.com/matsim-org/matsim-libs/pull/2490) . Unfortunately, I don't have the time to add a test case for this. Also, not sure if other tests may fail; we will see. If there is no failing test, then PR-2490 will eventually be deployed, and you could try.

Hi Kai, it works now with the new version. Thanks very much for that :)
