### ISSUE TITLE
public transit，java.lang.NullPointerException

### ISSUE THREAD

**Issue by sssshui** [matsim-org/matsim-code-examples#919]
Hello, I want to use Matsim to simulate public transportation. I have written my own files such as population, transitvehicle, and transitschedule.（I have attached them） During the process of running config, I encountered the following error message:
2023-04-13 14:57:32,791 ERROR QSim:314 got exception while cleaning up
java.lang.NullPointerException
	at org.matsim.core.mobsim.qsim.qnetsimengine.QNetsimEngine.afterSim(QNetsimEngine.java:251)
	at org.matsim.core.mobsim.qsim.QSim.cleanupSim(QSim.java:311)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:243)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:120)
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:199)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:231)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:195)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121)
	at org.matsim.core.controler.AbstractController.access$0(AbstractController.java:119)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:91)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:99)
	at org.matsim.core.controler.NewControler.run(NewControler.java:79)
	at org.matsim.core.controler.Controler.run(Controler.java:205)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2023-04-13 14:57:32,795 ERROR AbstractController:210 Mobsim did not complete normally! afterMobsimListeners will be called anyway.
java.lang.NullPointerException
	at org.matsim.pt.UmlaufInterpolator.insertWenden(UmlaufInterpolator.java:45)
	at org.matsim.pt.UmlaufInterpolator.addUmlaufStueckToUmlauf(UmlaufInterpolator.java:38)
	at org.matsim.pt.ReconstructingUmlaufBuilder.createUmlaeufe(ReconstructingUmlaufBuilder.java:86)
	at org.matsim.pt.ReconstructingUmlaufBuilder.build(ReconstructingUmlaufBuilder.java:71)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.getOrCreateUmlaufCache(TransitQSimEngine.java:145)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.createVehiclesAndDriversWithUmlaeufe(TransitQSimEngine.java:124)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.insertAgentsIntoMobsim(TransitQSimEngine.java:216)
	at org.matsim.core.mobsim.qsim.QSim.createAgents(QSim.java:271)
	at org.matsim.core.mobsim.qsim.QSim.prepareSim(QSim.java:256)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:220)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:120)
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:199)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:231)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:195)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121)
	at org.matsim.core.controler.AbstractController.access$0(AbstractController.java:119)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:91)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:99)
	at org.matsim.core.controler.NewControler.run(NewControler.java:79)
	at org.matsim.core.controler.Controler.run(Controler.java:205)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2023-04-13 14:57:32,801 ERROR MatsimRuntimeModifications:54 Getting uncaught Exception in Thread main
java.lang.NullPointerException
	at org.matsim.pt.UmlaufInterpolator.insertWenden(UmlaufInterpolator.java:45)
	at org.matsim.pt.UmlaufInterpolator.addUmlaufStueckToUmlauf(UmlaufInterpolator.java:38)
	at org.matsim.pt.ReconstructingUmlaufBuilder.createUmlaeufe(ReconstructingUmlaufBuilder.java:86)
	at org.matsim.pt.ReconstructingUmlaufBuilder.build(ReconstructingUmlaufBuilder.java:71)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.getOrCreateUmlaufCache(TransitQSimEngine.java:145)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.createVehiclesAndDriversWithUmlaeufe(TransitQSimEngine.java:124)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.insertAgentsIntoMobsim(TransitQSimEngine.java:216)
	at org.matsim.core.mobsim.qsim.QSim.createAgents(QSim.java:271)
	at org.matsim.core.mobsim.qsim.QSim.prepareSim(QSim.java:256)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:220)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:120)
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:199)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:231)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:195)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121)
	at org.matsim.core.controler.AbstractController.access$0(AbstractController.java:119)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:91)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:99)
	at org.matsim.core.controler.NewControler.run(NewControler.java:79)
	at org.matsim.core.controler.Controler.run(Controler.java:205)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2023-04-13 14:57:32,802 ERROR MatsimRuntimeModifications:60 ERROR --- This is an unexpected shutdown!
2023-04-13 14:57:32,802 ERROR MatsimRuntimeModifications:63 Shutdown possibly caused by the following Exception:
java.lang.NullPointerException
	at org.matsim.pt.UmlaufInterpolator.insertWenden(UmlaufInterpolator.java:45)
	at org.matsim.pt.UmlaufInterpolator.addUmlaufStueckToUmlauf(UmlaufInterpolator.java:38)
	at org.matsim.pt.ReconstructingUmlaufBuilder.createUmlaeufe(ReconstructingUmlaufBuilder.java:86)
	at org.matsim.pt.ReconstructingUmlaufBuilder.build(ReconstructingUmlaufBuilder.java:71)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.getOrCreateUmlaufCache(TransitQSimEngine.java:145)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.createVehiclesAndDriversWithUmlaeufe(TransitQSimEngine.java:124)
	at org.matsim.core.mobsim.qsim.pt.TransitQSimEngine.insertAgentsIntoMobsim(TransitQSimEngine.java:216)
	at org.matsim.core.mobsim.qsim.QSim.createAgents(QSim.java:271)
	at org.matsim.core.mobsim.qsim.QSim.prepareSim(QSim.java:256)
	at org.matsim.core.mobsim.qsim.QSim.run(QSim.java:220)
	at org.matsim.core.controler.NewControler.runMobSim(NewControler.java:120)
	at org.matsim.core.controler.AbstractController$8.run(AbstractController.java:199)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:231)
	at org.matsim.core.controler.AbstractController.mobsim(AbstractController.java:195)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:154)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:121)
	at org.matsim.core.controler.AbstractController.access$0(AbstractController.java:119)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:91)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:99)
	at org.matsim.core.controler.NewControler.run(NewControler.java:79)
	at org.matsim.core.controler.Controler.run(Controler.java:205)
	at org.matsim.run.Controler.run(Controler.java:56)
	at org.matsim.run.Controler.main(Controler.java:60)
2023-04-13 14:57:32,805 ERROR MatsimRuntimeModifications:78 ERROR --- MATSim unexpectedly terminated. Please check the output or the logfile with warnings and errors for hints.
2023-04-13 14:57:32,806 ERROR MatsimRuntimeModifications:79 ERROR --- results should not be used for further analysis.
2023-04-13 14:57:32,806 ERROR MatsimRuntimeModifications:83 ERROR --- This was an unexpected shutdown! See the log file for a possible reason.
I hope you can give me some suggestions to solve this problem
Sincerely thank you
[新建文件夹 (2).zip](https://github.com/matsim-org/matsim-code-examples/files/11219385/2.zip)

**Comment by kainagel** [comment]
Hello, the offending line is
```
java.lang.NullPointerException
at org.matsim.pt.UmlaufInterpolator.insertWenden(UmlaufInterpolator.java:45)
```
To have something meaningful at line 45 of that class, I need to go back to version 11 of matsim.  If this is the right version, it fails at
```
Node startNode = this.network.getLinks().get(fromLinkId).getToNode();
```
I.e. there is something inconsistent between the network you are using, and the network that the transit schedule is expecting.  Running the transit schedule validator on your transit schedule and your network returns
```
ERROR	Transit line Blue Line, route 5to0: Stop 10 cannot be reached along network route.
ERROR	Transit line Blue Line, route 0to5: Stop 1 cannot be reached along network route.
ERROR	Transit line Green Line, route 8to0: Stop 4 cannot be reached along network route.
ERROR	Transit line Green Line, route 0to8: Stop 3 cannot be reached along network route.
ERROR	Transit line Red Line, route 7to0: Stop 11 cannot be reached along network route.
ERROR	Transit line Red Line, route 0to7: Stop 11 cannot be reached along network route.
```
I don't know how you run your code; if you are running it from GUI, then the transit schedule validator is under "tools".  Maybe you need a more recent version than 11.

I think this closes the issue; please re-open if not resolved.

**Comment by sssshui** [comment]
Based on your suggestion, I have redesigned my network and transit schedule and validated their consistency by using “tools “ (display success)
However when I running it from GUI .there are some errors 
java.lang.Runtime Exception:some thread crashed, thus not all plans may have been handled 
java.lang.Runtime Exception:from link 46 
 missing

should I continue to adjust my transitschedule ?Thanks for your reply

**Comment by kainagel** [comment]
could you please attach the full logfile?

**Comment by sssshui** [comment]
[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/11234268/logfile.log)

**Comment by kainagel** [comment]
I am sorry but I cannot find a version of MATSim that has your error messages on lines 85 or 87 of "NetworkRoutingModule".

In general, it looks like you have persons with activities on links that are not or no longer in your network file.  However, I cannot say exactly since I cannot find "fromLink XX missing" in the code.

If this is the case, remove the links from your activities.  As long as the activities have coordinates, matsim will re-create the links.

**Comment by sssshui** [comment]
Your suggestion is helpful. Thank you so much

**Comment by sssshui** [comment]
Hello, may I ask why the first time I wrote the network, population, mytransitschedule, and myvehicle files into config.xml, I successfully ran it. When I wanted to change my transitschedule and put the changed schedule into config, why did I still use the unmodified transitschedule in the GUI run results
How should I do it? Thank you for your reply
