### ISSUE TITLE
Error while changing running different innovation strategies. 

### ISSUE THREAD

**Issue by jinkai89** [matsim-org/matsim-code-examples#93]
I'm running a different innovation strategies in MATSim. In the config file, each time I use a innovation strategy that involves mode choice(i.e. subtourmodechoice, changeTripMode ...), I get an error. I have attached below the logfile. The same error comes up when I run using both version 0.10.0 and 0.10.1 but not when I use version 0.9.0. If I just keep the innovation strategies to ReRoute and TimeAllocationMutator, the simulation runs smoothly as well. 

I have attached a small sample of the simulation files (population, network, config, transit schedule and vehicle files). Please let me know if anyone gets the same error while running the simulation. Thanks. 
[BUILT.logfile.log](https://github.com/matsim-org/matsim-code-examples/files/2911099/BUILT.logfile.log)
[NYC.zip](https://github.com/matsim-org/matsim-code-examples/files/2911102/NYC.zip)

**Comment by mrieser** [comment]
The actual error is:
```
2019-02-25 22:27:04,878 ERROR AbstractMultithreadedModule$ExceptionHandler:210 Thread PlanRouter.3 died with exception. Will stop after all threads finished.
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at org.matsim.pt.router.AbstractTransitRouter.convertPassengerRouteToLegList(AbstractTransitRouter.java:110)
	at org.matsim.pt.router.TransitRouterImpl.calcRoute(TransitRouterImpl.java:138)
	at org.matsim.core.router.TransitRouterWrapper.calcRoute(TransitRouterWrapper.java:81)
	at org.matsim.core.router.TripRouter.calcRoute(TripRouter.java:217)
	at org.matsim.core.router.PlanRouter.run(PlanRouter.java:87)
	at org.matsim.core.replanning.modules.AbstractMultithreadedModule$PlanAlgoThread.run(AbstractMultithreadedModule.java:234)
	at java.lang.Thread.run(Thread.java:745)
```

So it is an error within the transit router, and not per se with the mode choice process itself.
But why the transit router produces the error suddenly in iteration 2 and not before, I don't yet understand. Most likely is is some very special case with the data or routing algorithm.

**Comment by jinkai89** [comment]
If an agent is assigned public transit during innovation mode choice process, but there is no public transit in its search radius, will this this error come up?

**Comment by balacmi** [comment]
This should not be the problem, as the search radius is extended until the public transit stops are found. Is it possible that maybe you are using an older version of the transit_schedule that is only compatible with the MATSim 0.9.0? I would guess that there is some problem with some compatibility as I am assuming you are not adding any special code to MATSim core for your runs?

**Comment by JWJoubert** [comment]
An alternative that I recently found valuable was to just check the validity of my transit schedule file.

```
        TransitScheduleValidator.ValidationResult result = TransitScheduleValidator.validateAll(transitSchedule, sc.getNetwork());
        if (!result.isValid()) {
            for(String error : result.getErrors()){
                LOG.error(error);
            }
            throw new RuntimeException("Could not generate a valid transit schedule");
        }
        TransitScheduleValidator.printResult(result);
```

**Comment by jinkai89** [comment]
> An alternative that I recently found valuable was to just check the validity of my transit schedule file.
> 
> ```
>         TransitScheduleValidator.ValidationResult result = TransitScheduleValidator.validateAll(transitSchedule, sc.getNetwork());
>         if (!result.isValid()) {
>             for(String error : result.getErrors()){
>                 LOG.error(error);
>             }
>             throw new RuntimeException("Could not generate a valid transit schedule");
>         }
>         TransitScheduleValidator.printResult(result);
> ```

I ran the TransitScheduleValidator in the pt2matsim extension and the schedule was valid.

**Comment by jinkai89** [comment]
> This should not be the problem, as the search radius is extended until the public transit stops are found. Is it possible that maybe you are using an older version of the transit_schedule that is only compatible with the MATSim 0.9.0? I would guess that there is some problem with some compatibility as I am assuming you are not adding any special code to MATSim core for your runs?

I used the transitschedule v2. I used the MATSim SBB extension instead of default pt router and the simulation was successful.
