### ISSUE TITLE
error in running stop based drt example (Exception in thread "main" com.google.inject.CreationException: Unable to create injector)

### ISSUE THREAD

**Issue by Sharmeela16** [matsim-org/matsim-code-examples#96]
I am getting this error in running stop based drt simulation? how can i solve this?

Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Explicit bindings are required and org.matsim.contrib.drt.routing.DrtRoutingModule is not explicitly bound.
  while locating org.matsim.contrib.drt.routing.DrtRoutingModule
    for the 2nd parameter of org.matsim.contrib.drt.routing.StopBasedDrtRoutingModule.<init>(StopBasedDrtRoutingModule.java:49)
  at org.matsim.contrib.drt.run.DrtModule.install(DrtModule.java:52) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.contrib.drt.run.DrtModule)

2) Explicit bindings are required and org.matsim.contrib.drt.routing.StopBasedDrtRoutingModule$AccessEgressStopFinder is not explicitly bound.
  while locating org.matsim.contrib.drt.routing.StopBasedDrtRoutingModule$AccessEgressStopFinder
    for the 4th parameter of org.matsim.contrib.drt.routing.StopBasedDrtRoutingModule.<init>(StopBasedDrtRoutingModule.java:49)
  at org.matsim.contrib.drt.run.DrtModule.install(DrtModule.java:52) (via modules: com.google.inject.util.Modules$CombinedModule -> com.google.inject.util.Modules$CombinedModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.core.controler.AbstractModule$4 -> com.google.inject.util.Modules$OverrideModule -> org.matsim.contrib.drt.run.DrtModule)

2 errors
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236)
	at org.matsim.core.controler.Injector.createInjector(Injector.java:73)
	at org.matsim.core.controler.Controler.run(Controler.java:189)
	at sharmeela.thesis.drtstopbased.run(drtstopbased.java:18)
	at sharmeela.thesis.drtstopbased.main(drtstopbased.java:22)

**Comment by jfbischoff** [comment]
This should not happen. However, it's hard to provide a meaningful answer without additional information on your setup.
